Azure/azure-osconfig

.github/PULL_REQUEST_TEMPLATE.md
Fix link to `CONTRIBUTING.md` in PR template.
=> Update link to CONTRIBUTING.md

README.md, src/agents/pnp/PnpAgent.c, src/agents/pnp/daemon/osconfig.json
Makes local reporting configurable by user and by default disabled
=> Watcher: making local reporting configurable and by default disabled

.devcontainer/devcontainer.json
* Added support for building C++ in dev containers without first cloning submodules which enables building the agent in Codespaces.
- [ x] I have read the [contribution guidelines](https://github.com/Azure/azure-osconfig/blob/main/CONTRIBUTING.md).
- [ x] I have merged the latest `main` branch prior to this PR submission.
- [ x] I submitted this PR against the `main` branch.
=> Initialized submodule from dev container

src/modules/commandrunner/src/so/CommandRunnerModule.cpp, src/modules/hostname/src/so/HostNameModule.cpp, src/modules/ztsi/src/so/ZtsiModule.cpp
Remove `OsConfigLogInfo(...)` from modules on calls to `MmiSet` when full logging is not enabled.
=> Update module logging on calls to MmiSet

src/modules/ztsi/tests/ZtsiTests.cpp
Fix tests for invalid client name to check for the correct date strings.
=> Fix ZTSI tests for invalid client name

src/platform/modulesmanager/src/ModulesManager.cpp
Log format string in ModelsManger was breaking builds on specific ARM builds. This PR fixes that issue.
=> Fix log format string

src/agents/pnp/daemon/osconfig.json
Adds reported objects (`Enabled` and `ServiceUrl`) to `/etc/osconfig/osconfig.json` so that objects are reported by default.
=> Add ZTSI reported objects 

src/CMakeLists.txt
Remove `ENABLE_PAYLOAD_LOGGING` from CMakeLists. This was replaced by run time configuration.
=> Remove payload logging from CMakeLists.txt

devops/pipeline/binary_package.yaml, devops/pipeline/binary_package_arm.yaml, devops/pipeline/binary_package_consolidated.yaml, devops/pipeline/e2etest.yaml, devops/pipeline/source_packaging.yaml
Fixes `$(Build.BuildNumber)` to use correct revision number format so that debian package versions are not broken when build artifacts are published.
=> Update build revision number format

devops/pipeline/e2etest.yaml
Added the azcli output suppression flag to the 'az iot hub device-identity create' command to suppress device identity details in E2E Cloud Tests pipeline logs. Verified the fix by running the pipeline with the updated yaml and confirmed device identity details were removed from logs and all pipeline tasks succeeded.
=> Removed device identity details from E2E Cloud Tests pipeline logs 

src/modules/ztsi/src/lib/Ztsi.cpp, src/modules/ztsi/src/lib/Ztsi.h, src/modules/ztsi/tests/ZtsiTests.cpp
Cache enabled state on every `SetEnabled()` call to allow enabling prior to setting of the service URL. This allows the module to handle `SetEnabled()` and `SetServiceUrl()` in any order they may arrive, alone or together.
=> Cache enabled state

src/modules/ztsi/src/lib/Ztsi.cpp, src/modules/ztsi/tests/ZtsiTests.cpp
Update return values of `SetEnabled` to return success even when a value is cached and not immediately applied to the configuration file.
=> Update return values for cached enabled state

src/common/logging/Logging.c
Small hardening fix in the logging library to primarily rely on stat for getting log file size instead of ftell.
=> Fix log file trimming to rely on stat primarily instead of ftell to get log file size

src/common/logging/Logging.c
Resetting the internal trim log counter once the log file is trimmed
=> Resetting the internal trim log counter

src/common/logging/Logging.c
The log files may lose root access-only protection after being trimmed and manually deleted before osconfig starts
This commit fixes both these situations
=> The log files may lose root access-only protection after being trimmed and manually deleted before osconfig starts

src/platform/modulesmanager/src/ModulesManager.cpp, src/platform/modulesmanager/tests/ModuleManagerTests/src/MpiTests.cpp
Fixes validation on desired configuration to align with [modules.md 3.2.3](https://github.com/Azure/azure-osconfig/blob/main/docs/modules.md#323-serialized-mim-payload-at-run-time). 
Fixes logging of JSON payloads without `IsFullLoggingEnabled()`.
=> Fix MPI desired configuration validation

src/modules/hostname/src/lib/HostNameBase.cpp
Fixing one of the logging outputs of the `HostName` module. If `MmiSet` is called with an invalid object name, the logging output can be misleading.
Actual:
`[2022-01-05 16:52:03] [HostNameBase.cpp:90] [ERROR] Set called with an invalid object name: 'INVALID_OBJECT_NAME' (expected 'Name' or 'Hosts')`
Expected:
`[2022-01-05 16:52:03] [HostNameBase.cpp:90] [ERROR] Set called with an invalid object name: 'INVALID_OBJECT_NAME' (expected 'DesiredName' or 'DesiredHosts')`
=> Fix HostName logging for invalid object names during MmiSet

src/common/commonutils/CommonUtils.c, src/modules/settings/tests/CommonUtilsUT.cpp
Making commonutils!ExecuteCommand capture as text output both stdout and stderr
=> Making commonutils!ExecuteCommand capture as text output both stdout and stderr

src/platform/modulesmanager/inc/ModulesManager.h, src/platform/modulesmanager/src/ModulesManager.cpp, src/platform/modulesmanager/tests/ModuleManagerTests/src/ModulesManagerTests.cpp
Fix JSON strings in MpiGetReported and is ModulesManagerTests to use correct payload size bytes.
=> Fix JSON strings in MpiGetReported

src/agents/pnp/PnpAgent.c, src/common/commonutils/CommonUtils.c, src/modules/settings/tests/CommonUtilsUT.cpp
Hardening http proxy parsing and allowing domain names and escaped characters in username and password
=> Hardening http proxy parsing and allowing domain names and escaped characters in username and password

src/common/commonutils/CommonUtils.c, src/modules/commandrunner/tests/CommandRunnerTests.cpp
Commands without specified timeout default to be terminated in 60 seconds and can be canceled during execution
=> Commands without specified timeout default to be terminated in 60 seconds and can be canceled during execution

src/agents/pnp/PnpAgent.c, src/common/commonutils/CommonUtils.c, src/common/commonutils/CommonUtils.h, src/modules/commandrunner/tests/CommandRunnerTests.cpp, src/modules/settings/tests/CommonUtilsUT.cpp
Restricting system commands with timeout or cancelation executed from main process thread
=> Restricting system commands with timeout or cancelation executed from main process thread

README.md, src/agents/pnp/PnpUtils.c, src/common/commonutils/CommonUtils.c
Readme instructions for using an HTTP proxy for OSConfig
=> Readme instructions for using an HTTP proxy for OSConfig

src/agents/pnp/PnpAgent.c, src/agents/pnp/PnpUtils.c
Avoiding re-entrant twin callbacks that can crash us
=> Avoiding re-entrant twin callbacks that can crash us

src/common/commonutils/CommonUtils.cpp
Preventing repeated error logging for a new device with no desired configuration
=> Preventing repeated error logging for a new device with no desired configuration

src/common/commonutils/CommonUtils.cpp, src/modules/schema/mim.object.schema.json, src/modules/settings/tests/CommonUtilsUT.cpp
Allow MIM object JSON payloads to contain `null` values in maps.
=> Allow maps to contain null values

.devcontainer/Dockerfile
* Made the dotnet install more portable. Now installing through script since arm variants are not on packages.microsoft.com for the dotnet-sdk.
=> Added support for arm64 dev containers

devops/pipeline/e2etest.yaml
* Multiple packages are being produced by the `Package Build` pipeline, both signed and unsigned as such, the `DownloadPipelineArtifact` stage should pick one of the packages. Added `head -n 1` to capture the first package.
* Removed `continueOnError` to have an explicit failure when packages fail to be copied or device identities fail to be created as they would fail anyways at further stages.
=> Fixed E2E tests when multiple packages exist

src/common/commonutils/CommonUtils.c, src/modules/settings/tests/CommonUtilsUT.cpp
The way we were encoding the space character was correct but not understood by all decoders. This fixes that and also adds support for encoding the EOL character.
=> Fixing UrlEncode and UrlDecode for space character and adding support for EOL character

devops/pipeline/e2etest.yaml, devops/terraform/host/OSConfigHost.tf
* Removed static `aziot-identity-service_1.2.3` install on Ubuntu 20.04, which would randomly fail on dpkg issues during install. Replaced with installing the latest stable version on packages.microsoft.com
* Onboarded Debian 9 as additional test target
* Removed Azure policy to auto-shutdown VM in favor of pipelines deallocating VMs after tests
=> Fixed e2e test reliability, added Debian9 target

src/modules/ztsi/src/lib/Ztsi.cpp
Fix `SerializeJsonObject()` to treat `maxPayloadSizeBytes == 0` as *unlimited* payload size.
=> Fix SerializeJsonObject() for unlimited max payload size

src/modules/settings/src/lib/Settings.cpp, src/modules/settings/src/lib/Settings.h, src/modules/settings/src/so/SettingsModule.cpp, src/modules/settings/tests/SettingsTests.cpp
Fixes settings module `.so` to allocate/delete `MMI_HANDLE` on every `MmiOpen/Close()`. Removed globals and use `clientSession` that is passed to `MmiSet()`
=> Fix settings module usage of MMI_HANDLE

src/platform/modulesmanager/src/ModulesManager.cpp
Fix `maxPayloadSizeBytes` that is passed to `MpiSession`'s on `MpiSetDesired()`.
=> Fix max payload size for MpiSetDesired sessions

src/modules/commandrunner/src/lib/Command.cpp, src/modules/commandrunner/src/lib/Command.h, src/modules/commandrunner/src/lib/CommandRunner.cpp, src/modules/commandrunner/src/lib/CommandRunner.h, src/modules/commandrunner/tests/CommandRunnerTests.cpp, src/modules/commandrunner/tests/CommandTests.cpp
- Duplicate commands (same `CommandArguments` payload from `MmiSet()`): return `MMI_OK` and only log info if full logging is enabled
- Commands with a duplicate `CommandId` (different payload, same ID): return `EINVAL` and log error message
=> Fix CommandRunner to handle duplicate commands and commands with a duplicate id

src/platform/modulesmanager/inc/ModulesManager.h, src/platform/modulesmanager/src/ModulesManager.cpp, src/platform/modulesmanager/tests/ModuleManagerTests/src/MockModulesManager.cpp
Fixes reported object order to maintain the order descibed by `osconfig.json` in payloads from `MpiGetReported()`.
=> Fix reported object order from osconfig.json for MpiGetReported

devops/pipeline/e2etest.yaml, devops/pipeline/stages/binary_build.yaml, devops/pipeline/stages/e2etest_baremetal.yaml, devops/pipeline/stages/e2etest_cloud.yaml, devops/pipeline/stages/e2etest_iothub_create.yaml, devops/pipeline/stages/e2etest_iothub_delete.yaml, devops/pipeline/stages/e2etest_testdriver.yaml, devops/scripts/install_deps_debian9.sh, devops/scripts/install_deps_ubuntu1804.sh, devops/scripts/install_deps_ubuntu2004.sh
* Refactored stages into templates:
* Allows to easily scale targets be reusing templates (See stages folder below).
* Allows retry failed targets, in case of timeouts or any other random failures without needing a new run.
* Base pipelines much smaller and easier to understand (400 lines vs 120)
* Ability to target specific tests (Test Expression)
* Added ability to throw dynamic targets at the pipelines, by default contains:
```
- distroName: ubuntu-18.04
image_publisher: Canonical
image_offer: UbuntuServer
image_sku: 18.04-LTS
image_version: latest
packagePattern: '**/*bionic_x86_64.deb'
device_id: ubuntu1804
pre_script: >-
export DEBIAN_FRONTEND=noninteractive &&
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg &&
sudo cp ./microsoft.gpg …
```
=> E2E Test Pipeline Refactoring

devops/pipeline/stages/binary_build.yaml, src/CMakeLists.txt
* Fixes the missing last two digits in the TWEAK version. Now contains the daily revision as a prefix.
=> Fixed missing 2-digits in TWEAK_VERSION prefix

devops/pipeline/e2etest.yaml
Fix E2E pipeline triggers to only run-on merges to main (not on every PR).
[Azure Pipelines - Specify events that trigger pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops)
[Azure Pipelines - GitHub (opting out of PR validation)](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#opting-out-of-pr-validation)
=> Fix E2E pipeline trigger for pull-requests

devops/pipeline/stages/binary_build.yaml
* Removed the unit tests from the package build pipeline. Allows for building packages without coupling changes the CI pipeline has already validated in order to reduce package build time.
=> Remove unit tests from package build

src/agents/pnp/PnpAgent.c
This was observed on HCI to be true: SIGUSR1 once handled once, reverts to default handler - which causes OSConfig to abruptly exit (crash). This PR fixes resetting that event on each handling and also doing this for SIGHUP.
=> Resetting the signal for desired configuration

devops/pipeline/source_packaging.yaml
Re-enable CI tests in pipeline (excluding `Ubuntu 20.04 ARM` due to a known bug).
=> Re-enable CI tests in pipeline

src/tests/e2etest/CommandRunnerTests.cs, src/tests/e2etest/E2ETest.cs, src/tests/e2etest/FirewallTests.cs, src/tests/e2etest/HostNameTests.cs, src/tests/e2etest/NetworkingTests.cs, src/tests/e2etest/SettingsTests.cs, src/tests/e2etest/TpmTests.cs, src/tests/e2etest/ZtsiTests.cs
* Use PascalCase for C# Properties
* Use camelCase when serializing to or deserializing from json
* Use Newtonsoft json library consistently to benefit from CamelCasePropertyNamesContractResolver
=> Unify serialization in e2e tests

.devcontainer/devcontainer.json
* Git integrations in vscode do not work without having the `safe.directory` directive in the `.gitconfig`. Added to `postCreateCommand`
=> Fixed dev container git integrations

.github/workflows/package.yml
Create a [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows) (`workflow_call` ) for producing package artifacts across multiple OSs and variants (architecture/platform).
=> Create reusable package workflow

src/agents/pnp/MpiProxy.c
=> Add temporary workaround to retry with MPI C API call when MPI REST API fails

src/modules/commandrunner/src/lib/CommandRunner.cpp
Update the CommandRunner's persisted cache schema to store an array of command statuses to prevent re-executing commands from local desired configuration when OSConfig restarts.
=> Update persisted command status cache schema

.github/workflows/deploy-github-main.yml, .github/workflows/deploy-insiders-fast.yml, .github/workflows/e2etest-fetch-targets.yml, .github/workflows/e2etest-provision-hosts.yml, .github/workflows/e2etest-provision-hub.yml, .github/workflows/e2etest-run-tests.yml, devops/e2e/github-main.json, devops/e2e/insiders-fast.json, devops/e2e/prod.json, devops/terraform/host/GenericRunnerHost.tf, devops/terraform/host/variables.tf
* Added ARM64 test target
* Refactored Terraform to support variable VM sizes/location
* Moved hub-identity creation to hub-provisioning job as ARM64 hosts do not have full AZ CLI support
* Improved E2E workflow job naming to make it prettier
=> Added E2E ARM64 support

src/agents/pnp/daemon/osconfig.json
=> Incrementing the OSConfig DTMI model version to 8 to capture the updated DeviceInfo

devops/e2e/github-main.json
* Noticed latest e2e on `[GitHub-Main](https://github.com/Azure/azure-osconfig/actions/workflows/deploy-github-main.yml)` are only running the TpmTests. Remove the test filter.
=> Removed test filter from GitHub-Main

.github/workflows/ci.yml
Allow CI jobs to fail on the first failure (default behavior).
=> Remove fail-fast: false from CI workflow

devops/e2e/prod.json
* `e2e-prod` tests were failing because of missing github runner in test medatata
=> Fix missing github runner in e2e prod for x64 targets

.github/workflows/e2etest-run-tests.yml
* When e2e tests failed, the logs were never copied over to the staging directory. Added a separate step to stage logs.
=> Fixed missing log files in e2e tests

src/platform/Main.c, src/platform/MpiServer.c, src/platform/inc/MpiServer.h
Examples of traces written to the Platform log when a module crashes the process (here simulated with DeviceInfo) :
[ERROR] OSConfig Platform crash due to segmentation fault (SIGSEGV) during MpiGet to DeviceInfo.osVersion
[ERROR] OSConfig Platform crash due to segmentation fault (SIGSEGV) during MpiGetReported
=> Adding information to Platform log source of crash that may be initiated during MPI calls

.devcontainer/Dockerfile, devops/scripts/generate_moduletest_metadata.sh, src/modules/CMakeLists.txt, src/modules/mim/networking.json, src/modules/mim/packagemanagerconfiguration.json, src/modules/mim/sample.json, src/modules/test/CMakeLists.txt, src/modules/test/Common.h, src/modules/test/MimParser.cpp, src/modules/test/MimParser.h, src/modules/test/RecipeInvoker.cpp, src/modules/test/main.cpp, src/modules/test/recipes/FirewallTests.json, src/modules/test/recipes/HostnameTests.json, src/modules/test/recipes/NetworkingTests.json, src/modules/test/recipes/PackageManagerConfigurationTests.json, src/modules/test/recipes/SampleTests.json, src/modules/test/recipes/TpmTests.json, src/modules/test/unit-tests/CMakeLists.txt, src/modules/test/unit-tests/MimParserTests.cpp
* Added map and array field support for MimObjects
* Added support for embedded objects
* Added additional test recipes for Firewall, Hostname, PMC, Networking, Tpm
* Changed Mim parsing tests to use the Sample module for more complete coverage
=> Added map, array field support to moduletest

.github/workflows/e2etest-provision-hosts.yml, devops/e2e/github-main.json, devops/e2e/insiders-fast.json, devops/e2e/prod.json
* Fixes the `SkuNotAvailable` ARM provisioning error from the `DS1_v2`. Allows us to override the default `West Us 2` used to provision the VMs for the e2e tests
=> Added location to e2e test targets

src/agents/pnp/PnpAgent.c, src/agents/pnp/daemon/osconfig.json
=> Ensuring local RC/DC are processed on OSConfig start before the first Desired Twin callback

.github/actions/footprint-check/action.yml, .github/workflows/build-package.yml, devops/binary-footprint-baseline/baseline.json, devops/scripts/generate_binary_footprints.sh
* Adds binary baseline validation to `Package` workflow, using `1.0.3.2022061601` as current baseline.
* Binary baselines published in `devops/binary-footprint-baseline/baseline.json`
* Added script to update binary baselines (using latest published as default or by using an optional regex filter as first argument)
* Using current delta as 10%, meaning package workflows will fail if they exceed/drop the current footprint by more than 10%
* Fixed package build to use correct `CMAKE_BUILD_TYPE` argument
=> Added binary baseline validations

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/deploy-github-main.yml, .github/workflows/e2etest-provision-hosts.yml, .github/workflows/e2etest-run-tests.yml, devops/e2e/debian-stretch-cloud-init.tpl, devops/e2e/github-main.json, devops/e2e/insiders-fast.json, devops/e2e/prod.json, devops/e2e/ubuntu-bionic-cloud-init.tpl, devops/e2e/ubuntu-focal-arm64-cloud-init.tpl, devops/e2e/ubuntu-focal-cloud-init.tpl, devops/scripts/install_deps_debian9.sh, devops/scripts/install_deps_ubuntu1804.sh, devops/scripts/install_deps_ubuntu2004.sh, devops/terraform/host/GenericRunnerHost.tf, devops/terraform/host/variables.tf, src/tests/e2etest/E2ETest.csproj
* Added Debian 9 support (amd64)
* Added shared image gallery support in E2E test infrastructure
* Added cloud-init support to test VMs
* Added cloud-init scripts for Ubuntu 18.04/20.04 (amd64), Debian 9 (amd64) and Ubuntu 18.04 arm64 hosts
* Added DotNet 6.0 support to E2E test application
* Updated container definitions for DotNet 6.0
* Added IoTHub provisioning dependency before VM provisioning
=> Added e2e cloud-init support

.github/workflows/build-containers.yml
Create workflow to build and push devops containers to the OSConfig Azure CR. This workflow is triggered when changes to devops/docker/**/Dockerfile are merged to main.
The `docker` job uses the self-hosted, 1ES managed runner pool (`azure-osconfig-pool`) to build and push updated container images.
=> Create build-containers workflow

devops/e2e/insiders-fast.json, devops/e2e/prod.json
* Fix package path for Debian9 on prod/insiders-fast workflows
=> Fixed debian9 e2e package path

.github/workflows/build-containers.yml, .github/workflows/build-package.yml, .github/workflows/package.yml
Update package build workflow to sign packages using 1ES hosted Windows runner. Calling the `build-package` workflow with `signed: true` will produce an artifact containing the signed packages (`<inputs.artifact>-signed`).
=> Update package build workflow to use self-hosted runner during signing job

devops/e2e/debian-stretch-cloud-init-insiders-fast.tpl, devops/e2e/insiders-fast.json, devops/e2e/ubuntu-bionic-cloud-init-insiders-fast.tpl, devops/e2e/ubuntu-focal-arm64-cloud-init-insiders-fast.tpl, devops/e2e/ubuntu-focal-cloud-init-insiders-fast.tpl
* Added separate cloud-init templates for insiders-fast with the added insiders-fast apt repo
* Fixed arm64 cloud-init script, removed the sudoers `secure_path` override.
=> Fixed insiders-fast workflows and arm64 e2e targets

src/modules/networking/src/lib/Networking.cpp, src/modules/networking/src/lib/Networking.h, src/modules/networking/src/so/NetworkingModule.cpp, src/modules/networking/tests/NetworkingTests.cpp, src/modules/test/recipes/NetworkingTests.json
Moved Networking!MmiGet argument validation from the module's shared-object library to the internal static lib, where core logic is contained. This change minimizes the MMI for Networking and aligns with the pattern illustrated by the rest of the core module set.
=> Moved MmiGet argument validation from so to lib

.github/workflows/deploy-e2etest-prod.yml, .github/workflows/deploy-github-main.yml, .github/workflows/deploy-insiders-fast.yml, .github/workflows/deploy-reliability-modules.yml, .github/workflows/deploy-reliability-platform.yml, .github/workflows/e2etest-run-tests.yml
* Added suffix to test report names to properly identity variants of the test jobs (github-main, prod, insiders-fast)
=> Added suffix to test jobs to properly identify report

devops/scripts/generate_moduletest_metadata.sh, src/modules/test/CMakeLists.txt
* Removed explicit build path dependency, now works on any build path
=> Fixed modulestest explicit path

src/cmake/templates/osconfig.spec.in
* Added missing `osconfig-platform` binary to RPM spec
=> Added missing osconfig-platform ref to spec

src/CMakeLists.txt, src/modules/firewall/src/lib/Firewall.cpp, src/modules/firewall/src/lib/Firewall.h, src/modules/firewall/tests/FirewallTests.cpp, src/modules/hostname/src/lib/HostNameBase.cpp, src/modules/hostname/src/lib/HostNameBase.h, src/modules/hostname/src/so/HostNameModule.cpp, src/modules/hostname/tests/HostNameBaseTests.cpp, src/modules/settings/src/lib/Settings.h, src/modules/settings/src/so/SettingsModule.cpp, src/platform/tests/ManagementModuleTests.cpp, src/platform/tests/ModulesManagerTests.cpp, src/platform/tests/cmake/ModulesManagerTests.h.in
Add the compiler flag `-Wunused-const-variable=2` and fix unused constants in modules manager tests and in modules (firewall, hostname, settings).
=> Fix unused constant variables in platform and modules

.github/workflows/deploy-reliability-modules.yml, .github/workflows/deploy-reliability-platform.yml, .github/workflows/e2etest-run-tests.yml
* Decrease runtime of reliability tests to 4-hours until a fix for the workflow jobs not respecting `timeout-minutes` is found. 23hrs -> 4hrs
* Fixes bash loop arguments
* Fixes test log collection to capture all test iterations
=> Reliability test fixes

.github/workflows/e2etest-run-tests.yml
* Fixes the test report path when collecting test results, only multiple iteration passes were getting picked up (which contain a suffix `-$runNumber`) and not the single passes (no suffix)
=> Fix e2e test report path

src/modules/test/CMakeLists.txt, src/modules/test/README.md, src/modules/test/main.cpp
* Made `testplate-json` load from the root application path
* Added basic README.md for modulestest with usage examples and prerequisites
* Removed CMake warning for `jq` (needed to generate testplate.json)
* Added warning in `modulestest` when `testplate.json` is missing.
=> Added Modulestest readme and fixes

src/cmake/templates/osconfig.spec.in
* Fixes RPM spec to also create AIS config.d folder if AIS is not installed
=> fixed spec to create ais folder if not present

src/modules/test/RecipeInvoker.cpp
* Added automatic `payloadSizeBytes` deduction when undefined in test recipe
=> Deduced size when no payloadSizeBytes is defined

.github/workflows/deploy-reliability-modules.yml
* Current workflows fail if any of the jobs fail - see https://github.com/Azure/azure-osconfig/actions/runs/2731475995
=> no fail-fast on module-reliability workflows

src/tests/e2etest/E2ETest.csproj
* Fix current vulnerabilities for e2e test app
```
➜ dotnet list package --include-transitive --vulnerable
The following sources were used:
https://api.nuget.org/v3/index.json
Project `E2ETest` has the following vulnerable packages
[net6.0]: 
Transitive Package                                   Resolved   Severity   Advisory URL                                     
> Newtonsoft.Json                                    12.0.3     High       https://github.com/advisories/GHSA-5crp-9r3c-p9vr
> System.Security.Cryptography.X509Certificates      4.1.0      High       https://github.com/advisories/GHSA-7mfr-774f-w5r9
> System.Text.RegularExpressions                     4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
```
* [Improper Handling of Exceptional Conditions in …
=> Fix e2e test app vulnerabilities

devops/scripts/generate_moduletest_metadata.sh, src/modules/test/CMakeLists.txt, src/modules/test/Common.h, src/modules/test/ManagementModule.cpp, src/modules/test/ManagementModule.h, src/modules/test/RecipeInvoker.cpp, src/modules/test/RecipeInvoker.h, src/modules/test/RecipeModuleSessionLoader.cpp, src/modules/test/RecipeModuleSessionLoader.h, src/modules/test/TestRecipeParser.h, src/modules/test/main.cpp, src/modules/test/recipes/CommandRunnerTests.json
* Created separate module sessions for every test recipe
* Sessions are reused from the same test recipe
* Added ability to call `ComponentName`'s from other known modules from a test recipe
=> ModulesTest Test Recipe enhancements

.github/workflows/e2etest-run-tests.yml
* Change the test report verbosity level to prevent the test-report generation from failing
* Only keep the last e2e test report
=> Removed report verbosity and limited to latest run only

src/modules/test/RecipeInvoker.cpp
* Only validate the main recipes MimObjects and not other referenced `ComponentName`'s
=> Limit validation to module recipe only

.github/workflows/deploy-reliability-platform.yml, .github/workflows/e2etest-run-tests.yml, src/tests/e2etest/CommandRunnerTests.cs, src/tests/e2etest/datasource/IotHubDataSource.cs, src/tests/e2etest/datasource/LocalDataSource.cs
* Added additional logging to capture reported/desired on timeouts for both Hub/Local datasources
* Improved local datasource reliability
* Reduced platform reliability tests to run for 2hrs
=> Improved E2E reliability

src/agents/pnp/CMakeLists.txt
* Binplaces the AIS `osconfig.toml` at build-time to `/etc/aziot/identityd/config.d/` similar to our CMake post-install scripts
=> copy AIS toml at build-time

.github/actions/container-run/action.yml, .github/workflows/ci.yml, .github/workflows/deploy-reliability-modules.yml, src/modules/CMakeLists.txt, src/modules/mim/commandrunner.json, src/modules/mim/deviceinfo.json
* Changed default container to use `289651` (added jsonschema) and not `latest`. We want to make sure we use a specific version tag and not latest which might represent a broken reference.
* Added build-time validation of MIMs when jsonschema is installed (optional, CMake outputs a warning if jsonschema is not installed)
* Corrected `commandrunner` and `deviceinfo` MIMs to pass schema validation
=> Added build-time MIM validation

src/modules/test/TestRecipeParser.cpp, src/modules/test/TestRecipeParser.h, src/modules/test/main.cpp, src/modules/test/unit-tests/TestRecipeParserTests.cpp
* Previously, test recipes would use a `ComponentName.ObjectName` naming. Which can be confusing in the global test namespace if similar recipes include recipes without a `ComponentName` and/or `ObjectName` or a conflicting name. The new convention uses `ModuleName.ComponentName.ObjectName` and uses `<null>` values if `ComponentName` and/or `ObjectName` is blank (empty string "")
=> Improved modulestest recipe naming

.github/workflows/deploy-github-main.yml, .github/workflows/deploy-reliability-platform.yml, .github/workflows/e2etest-run-tests.yml
* Added configurable (default: 10s) delay for performance sampling to avoid initial OSConfig perf hit. Usually stable ~3s, made it 10s to be conservative and not hamper test runtime.
=> Delayed performance sampling for 10s

src/modules/test/TestRecipeParser.cpp, src/modules/test/unit-tests/CMakeLists.txt, src/modules/test/unit-tests/TestRecipeParserTests.cpp, src/modules/test/unit-tests/recipes/testInvalid.json
* Added required properties and validation to `modulestest` recipe parsing
=> Adding recipe validation to modulestest

src/modules/daemonconfiguration/Cargo.lock, src/modules/daemonconfiguration/Cargo.toml, src/modules/daemonconfiguration/src/daemonconfiguration.rs, src/modules/mim/daemonconfiguration.json
Switch the Mim and mmi implementation to use the string enum instead of an int enum. Also optimized crate for build size
=> Daemon config module switch enum type

src/modules/daemonconfiguration/src/common.rs, src/modules/daemonconfiguration/src/daemonconfiguration.rs
Added payload filtering to only report enabled daemons that don't have state "other" or "dead". Added a new payload size exceeded error type and message. Fixed wrong component and object names. Changed unit tests to reflect filtering.
=> Daemon config module payload filter

src/modules/daemonconfiguration/src/common.rs, src/modules/daemonconfiguration/src/daemonconfiguration.rs, src/modules/daemonconfiguration/src/lib.rs
Implemented set for the daemon config module and added unit tests. Fixed component and object names. Modified Systemctlinfo to take instances of self for testing
=> Daemon config module set

src/modules/networking/src/lib/Networking.cpp, src/modules/networking/tests/NetworkingTests.cpp
In some environments, multiple DNS servers are listed on a single line in output from "systemd-resolve --status," which is not expected by the current module and causes the parsing method for Networking.dnsServers to return empty data. This PR updates Networking to support the scenario.
=> [Networking] Add support for variable line break patterns in source data for dnsServers

src/modules/firewall/src/lib/Firewall.cpp, src/modules/firewall/src/lib/Firewall.h
Increase logging (during full logging) to not rely on reported `configurationStatusDetail` for error messages that occur during parsing and `iptables` command execution.
=> Increase firewall logging during parsing and bug fixes

.gitmodules, src/CMakeLists.txt
Corrosion is no longer fetched, instead it's a subdirectory. BUILD_RUST is no longer a manual flag, it's conditionally set on the presence of cargo and rustc
=> Conditional rust build and Corrosion

src/modules/hostname/src/lib/HostNameBase.cpp, src/modules/hostname/tests/HostNameBaseTests.cpp
Fixed a check that failed in the *HostName* module on *MmiSet* when a session was created with a maximum payload size of zero. Corrected by skipping the check if the maximum payload size is zero and created a test to verify fix.
=> Fix payload size check in HostName module

src/modules/firewall/src/lib/Firewall.cpp
The firewall module should report `state: enabled` only if `iptables` is present and there are rules specified in the `INPUT/OUTPUT` chains of the `filter` table. This change fixes the module's behavior to report `state: disabled` when no rules are specified in the `INPUT/OUTPUT` chains.
=> Fix firewall reported state detection

devops/e2e/debian-stretch-cloud-init-insiders-fast.tpl, devops/e2e/debian-stretch-cloud-init.tpl, devops/e2e/ubuntu-focal-arm64-cloud-init-insiders-fast.tpl, devops/e2e/ubuntu-focal-arm64-cloud-init.tpl
* Updated debian9 (using debian10 package) and ubuntu 20.04 arm64 distros to use IotEdge runtime 1.4
* Tested and works across all distros
=> Updated e2e tests to use iotedge 1.4

devops/debian/postinst, devops/debian/prerm, src/cmake/templates/osconfig.spec.in
* Removed osconfig module identity on Debian/RPM package removal
=> Removed module identity on package removal

src/modules/test/RecipeInvoker.cpp, src/modules/test/recipes/SampleTests.json
Use payload size when parsing reported JSON payload.
=> Fix inconsistent modulestest failures

.github/workflows/ci.yml
Re-add verbose ctest logs to CI `unit-test` artifact. Log artifacts were replaced by XML test output during #256. Both forms of logs are necessary for proper debugging.
=> Re-add ctest logs to CI artifacts

.github/workflows/e2etest-run-modulestest.yml
Store the log output from modules test runs during CI in an artifact for debugging.
=> Store modules test logs as an artifact

src/modules/test/RecipeInvoker.cpp
* Solidified MIM parsing for modulestest, will have warnings when parsing invalid MIMs
* Installed osconfig on modulestest CI VM hosts to enable `Configuration` module tests
=> Added additional MIM validations and warning for modulestest

src/modules/configuration/src/lib/Configuration.c
Removing from the Configuration module ability to restart OSConfig, for that to be done in a safer way with CommandRunner and reboot.
=> Removing from the Configuration module ability to restart OSConfig

src/tests/e2etest/AdhsTests.cs
Valid range for `optIn` values is `0-2`. Previous check was incorrect and may cause timeouts as it would miss valid values in `optIn`.
=> Fix range in Adhs E2E test 

.github/actions/container-run/action.yml, .github/actions/footprint-check/action.yml, .github/workflows/build-containers.yml, .github/workflows/build-package.yml, .github/workflows/ci.yml, .github/workflows/e2etest-fetch-targets.yml, .github/workflows/e2etest-provision-ais.yml, .github/workflows/e2etest-provision-hosts.yml, .github/workflows/e2etest-run-tests.yml, devops/e2e/github-main.json, devops/e2e/insiders-fast.json, devops/e2e/modulestest.json, devops/e2e/prod.json
* Removed deprecated `set-output` command, in favor of the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)
* Updated e2e github runners (all environments) to `298.2` (from `291.1`)
* Cleaned up github variables
=> Updated workflows to use new environment files

.github/workflows/e2etest-run-modulestest.yml, src/modules/test/RecipeInvoker.cpp
* Fixing the recipe payload validation to use standard string comparison instead of parsons `json_value_equals` which fails on occasion despite the JSON strings being equivalent.
=> Fixing payload validation for ModulesTest app

.github/workflows/deploy-github-main.yml, devops/e2e/github-main.json, devops/e2e/insiders-fast.json, devops/e2e/modulestest.json, devops/e2e/prod.json
* The `latest` version of the test target `Canonical:UbuntuServer:18.04-LTS:18.04.202210180` was always running into apt/dpkg lock issues. Downgraded the version to the previous working version `18.04.202210140`
=> Updated 18.04 image tag for more reliability

devops/pipeline/binary_package.yaml
* Updated Azure Pipelines containers to use the latest tag `289651`
=> Updated Azure pipelines tag to use latest containers

src/modules/test/TestRecipeParser.cpp, src/modules/test/recipes/AdhsTests.json, src/modules/test/recipes/CommandRunnerTests.json, src/modules/test/recipes/ConfigurationTests.json, src/modules/test/recipes/DeliveryOptimizationTests.json, src/modules/test/recipes/DeviceInfoTests.json, src/modules/test/recipes/FirewallTests.json, src/modules/test/recipes/HostNameTests.json, src/modules/test/recipes/NetworkingTests.json, src/modules/test/recipes/PmcTests.json, src/modules/test/recipes/SampleTests.json, src/modules/test/recipes/TpmTests.json, src/modules/test/recipes/ZtsiTests.json, src/modules/test/unit-tests/TestRecipeParserTests.cpp, src/modules/test/unit-tests/recipes/test.json, src/modules/test/unit-tests/recipes/testInvalid.json
- Each test recipe gets its first test object for setup of the module under test. Teardown is implied at the end of the recipe.
- CommandRunner invocation from other modules' test recipes is replaced with direct commands to be run by ModulesTest using commonutils.
- Test recipes using 4 spaces per tab are corrected to 2 spaces per tab.
=> Refactoring the test recipes with explicit setup and teardown and running commands without CommandRunner

.github/workflows/deploy-reliability-modules.yml, .github/workflows/deploy-reliability-platform.yml, .github/workflows/e2etest-run-modulestest.yml, .github/workflows/e2etest-run-tests.yml
* Reliability tests use minutes instead of hours allowing for more accurate timeouts
* Added collection to all osconfig logs (missing backup)
=> Tests use mins instead of hrs

.github/actions/gtest-xml/action.yml
`getchildren()` method was removed from `xml.etree.ElementTree.Element` (deprecated in version version 3.2 and then removed in 3.9). Fixed with `list()`.
=> Update xml parsing for CI test reports 

src/modules/networking/src/lib/Networking.cpp, src/modules/networking/tests/NetworkingTests.cpp
Added logic to check if the systemd-resolved service is running before attempting DnsServers data collection. If the service is stopped, the module will start it. If the service is not available on the system, the module will write an error in the Networking log file and continue.
=> Start systemd-resolved service for DnsServers data collection

.github/workflows/e2etest-run-modulestest.yml
Update usage of `moduletest` in reliability workflow.
=> Fix failing module test reliability workflow

.github/workflows/e2etest-run-modulestest.yml
=> Fix passing files as argument in module-test reliability workflow

src/modules/adhs/src/lib/Adhs.c
When *MmiGet* is called in the *Adhs* module with an invalid MIM object name, the error log would output the MIM component name.
=> Fix wrong argument in error log for Adhs

src/modules/mim/commandrunner.json, src/modules/mim/deliveryoptimization.json, src/modules/mim/logcollector.json, src/modules/schema/mim.schema.json
- add missing `"type": "object"` to MIM (commandrunner, deliveryoptimization, logcollector)
- update MIM schema to require `"type"` property on object schemas
=> Update MIM schema object type

.github/workflows/ci.yml
Make ctest log output visible in the workflow output (do not need to wait until workflow is complete to see logs).
=> Show ctest logs in workflow output

.github/workflows/package-build.yml, .github/workflows/publish.yml
Fixes package version tweak in `insiders-fast` packages to include the GitHub Actions `run_attempt`.
=> Include run attempt in package version tweak

dtmi/osconfig/securitybaseline-1.json, src/modules/mim/securitybaseline.json, src/modules/securitybaseline/src/lib/SecurityBaseline.c, src/modules/securitybaseline/tests/SecurityBaselineTests.cpp, src/modules/test/recipes/SecurityBaselineTests.json, src/platform/ModulesManager.c
This adds the remaining 125 remediation checks to the SecurityBaseline module, including unit-tests and test recipe functional tests, plus all the management channels supported by OSConfig, including Digital Twins, GitOps and Local Management. The only parts that remain to be added are the implementation for the check functions. A README.md will follow.
=> Plugging-in all remaining 125 remediation checks for the SecurityBaseline

.github/workflows/package-publish.yml
Fixes error in the publishing workflow during the update step. The PMC CLI expects a list of IDs during the final update step when packages are associated with the repo. Packages are then published separately in the final step.
=> Add --id-only flag to PMC upload command

devops/docker/debian-12-amd64/Dockerfile, devops/docker/debian-12-arm64/Dockerfile, devops/docker/ubuntu-22.04-amd64/Dockerfile, devops/docker/ubuntu-22.04-arm64/Dockerfile
Add Ubuntu 22.04 (`jammy`) and Debian 12 (`bookworm`) build containers (amd64 and arm64). 
_Workflow changes will follow after the containers are published to `ghcr.io`._
=> Add Ubuntu 22.04 and Debian 12 build containers

src/adapters/mc/OsConfig.schema.mof, src/adapters/mc/OsConfigPolicy.mof, src/adapters/mc/OsConfigPolicyFull.mof, src/adapters/mc/OsConfigResource.c, src/adapters/mc/OsConfigResource.h, src/adapters/mc/schema.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/FileUtils.c, src/common/commonutils/Internal.h, src/common/commonutils/SshUtils.c, src/common/commonutils/SshUtils.h, src/common/tests/CommonUtilsUT.cpp, src/modules/securitybaseline/src/lib/SecurityBaseline.c, src/modules/test/recipes/SecurityBaselineTests.json
The SecurityBaseline MIM has reported and desired simple MIM objects (containing one string MIM setting each) for each audit and respectively remediation check. For the desired objects, that string will be used to specify desired values at run time for audit and remediation. For the reported objects, the original requirement was for them to return something simple, stating audit passed of failed, thus the "PASS" and "FAIL". Since then the reported strings have been repurposed to hold reason phrases for failed audits (and when the NRP sees they are not "PASS", considers that audit failed with the stated reason). In this PR the reported strings for the passed audits are expanded with the reason following the "PASS" prefix (which is not included in the reported reason).
The Universal NRP …
=> Preparing the Universal NRP to accept custom parameter values for audit and remediation and reporting reasons for passed SSH audits

src/common/commonutils/SshUtils.c
Ensuring consistency between the fallback and OSConfig cases for audits with internal errors. In general, all audit calls must succeed, and any internal errors are to be logged. Additionally, when an audit check fails because an internal reason without a logged reason, a default blank fail reason is to be provided.
=> Ensuring consistency between the fallback and OSConfig cases for audits with internal errors

src/common/commonutils/SshUtils.c
Refactoring the remediation for the SSH policy checks from editing /etc/ssh/sshd_config to add a new /etc/ssh/sshd_config.d/*,conf file containing the remediated values and include that at top of /etc/ssh/sshd_config. This avoids remediation being overwritten by distro or user added .conf files.
=> Refactoring the remediation for the SSH policy checks

.github/actions/footprint-check/action.yml, .github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/insiders-fast.yml, .github/workflows/module-test.yml, .github/workflows/prod.yml
* Added Ubuntu 22.04 Jammy (amd64/arm64) to packaging workflows. Will now get published in `insiders-fast` and `prod` channels on packages.microsoft.com
=> Added Ubuntu 22.04 Jammy amd64/arm64 to packaging workflows

src/adapters/mc/OsConfigResource.c, src/common/commonutils/SshUtils.c, src/common/commonutils/SshUtils.h
When the user attempts to change default parameter values for policy we need to submit pre-audit the user desired values. This change here targets the NRP fallback case. For the OSConfig case the best course of action will be to add new set of initFoo (alongside auditFoo and remediateFoo) MIM desired objects to receive the desired values.
=> Adding initialization for SSH policy parameter values in fallback case

src/adapters/mc/OsConfigResource.c, src/modules/mim/securitybaseline.json, src/modules/securitybaseline/src/lib/SecurityBaseline.c, src/modules/securitybaseline/tests/SecurityBaselineTests.cpp, src/modules/test/recipes/SecurityBaselineTests.json
Adding to the SecurityBaseline 19 new desired MIM objects for initialization of the SSH audit checks so they can accept new values from Azure Policy assignment at run time.
=> Making the SecurityBaseline module to accept initialization for the SSH policy audit checks

.github/workflows/e2e-run.yml, .github/workflows/e2e.yml, devops/e2e/cloudtest/ubuntu-18_04.json, devops/e2e/cloudtest/ubuntu-22_04.json
- Fix E2E tests (pass connection string secret between jobs)
- Temporarily remove Ubuntu 22.04 E2E test job
- Add Ubuntu 22.04 cloudtest managed image definition
=> Temporarily removing Ubuntu 22.04 from the E2E tests due to AIS unavailability

.github/workflows/build-containers.yml
Remove unused workflow steps for pushing containers to an ACR. This method for storing/managing out build containers was temporarily disabled, then fully replaced by GHCR.
=> Remove unused workflow steps

.github/workflows/ci-report.yml, .github/workflows/e2e-report.yml
Add explicit token permissions for workflows that publish test reports. 
> Starting February 1, 2024 the default permission for the GITHUB_TOKEN will change from Read/Write to Read-only for all our Open Source GitHub orgs.
>
> https://aka.ms/github-token-perms-changes
=> Add explicit token permissions for publishing reports

src/common/commonutils/SshUtils.c
A backup of original configuration allows us to add in the case when the server does not support the Include keyword repeated remediations without piling them on top of each other.
=> Adding use of backup for original SSH server configuration and more stabilization for the SSH server security policy

.github/workflows/insiders-fast.yml
* Fixing the package publication channel behavior to use package type instead of distro. RPM based distros do not require channels.
=> Fixing the package publication channel based on package type instead of distro

src/common/commonutils/SshUtils.c
=> Addressing problem when the SSH banner text is edited in Portal EOL characters are changed to '\\' and 'n' removing the end of lines

.github/workflows/ci.yml
Downgrade upload-artifact to v3 to allow multiple uploads to a single `unit-test` artifact (used for generating the test report).
> https://github.com/actions/upload-artifact/issues/478
=> Downgrade upload-artifact from v4 to v3

src/modules/test/recipes/SecurityBaselineTests.json
Making the SecurityBaseline test recipe closer to what happens in reality for SSH checks under MC: a set of remediations with real values, then a reload of the module to cause a SSH server restart, then an init sequence to tell audit what to check for, then the actual audits. 
WARNING: running this test recipe more than one time in a quick sequence (without waiting at least 15 minutes between runs) and/or in parallel with NRP execution of the SSH policy on same VM/device can risk blocking the SSH service from running and will require a fix by OS reboot on that VM/device.
=> Making the SecurityBaseline test recipe to remediate and audit real SSH server configuration values

.github/actions/sign-package/action.yml, .github/workflows/e2e-run.yml, .github/workflows/module-test-run.yml, .github/workflows/package-build.yml, .github/workflows/package-publish.yml, .github/workflows/prod.yml
* v4 upload/download actions are not backward compatible with downstream actions not using v4 (ex dorny-testreporter - https://github.com/dorny/test-reporter/issues/363). Downgraded all to v3 given the unintended consequences. Will upgrade at later time.
=> Downgraded download/upload-artifact to v3

devops/docker/almalinux-9-amd64/Dockerfile, devops/docker/amazonlinux-2-amd64/Dockerfile
* Backporting GTest on older distros (almalinux-9, amazonlinux-2)
=> Backport GTest on older distros

devops/docker/rhel-9-amd64/Dockerfile
* Downgrade GTest on RHEL 9 container
=> Downgrading GTest on RHEL 9

.github/workflows/module-test.yml, devops/e2e/cloudtest/centos-8.json, devops/e2e/cloudtest/sles-15.json
* Onboarded the following distros to run test recipes:
* centos-8
* oraclelinux-8
* rhel 8, 9
* suse 15
* Added cloudtest artifact manifests for suse-15 (sles) and centos-8 (not needed for other distros)
=> Adding additional target distros for recipe module tests

src/common/commonutils/CommonUtils.h, src/common/commonutils/DeviceInfoUtils.c, src/common/tests/CommonUtilsUT.cpp, src/modules/securitybaseline/src/lib/SecurityBaseline.c
A select set of Security Baseline checks require different actions per distro. This PR adds that and applies it to one check from the ones that need it: AuditEnsurePasswordCreationRequirements, The pretty name values are for future uses which need the exact distro name.
=> Adding way for Security Baseline checks to easily detect on which OS distro they are running

.github/workflows/ci-report.yml, .github/workflows/ci.yml, .github/workflows/universalnrp-test-run.yml, src/tests/universal-nrp-e2e/UniversalNRP.Tests.ps1
* Added both agent and agentless Machine Configuration E2E Tests
* Changed tests to use jUnit instead of NUnit (as the testreporter breaks with NUnit 2.5)
* Remove `Verbose` flag from GuestConfiguration cmdlets
=> Adding Universal NRP E2E test variants with and without OSConfig package installed

.github/workflows/ci.yml, .github/workflows/universalnrp-test-run.yml
* Removed Universal NRP tests from CI
* Added suffix to artifact naming to prevent job conflicts
=> Removing the functional Universal NRP tests from the CI

src/platform/MpiServer.c
=> Avoiding SEGFAULT calling pthread_join on an expired thread with id 0

.github/workflows/ci-report.yml, .github/workflows/universalnrp-test-report.yml, .github/workflows/universalnrp-test-run.yml, .github/workflows/universalnrp-test.yml, devops/e2e/cloudtest/debian-10.json, devops/e2e/cloudtest/debian-11.json, devops/e2e/cloudtest/debian-12.json, devops/e2e/cloudtest/mariner-2.json, devops/e2e/cloudtest/oraclelinux-8.json, devops/e2e/cloudtest/rhel-8.json, devops/e2e/cloudtest/rhel-9.json, devops/e2e/cloudtest/rockylinux-9.json, devops/e2e/cloudtest/sles-15.json
* Added Machine Configuration e2e workflow targeting the following distros (daily + workflow dispatch):
* Centos 8
* Debian 10, 11
* Mariner 2 (aka Azure Linux)
* Oracle Linux 8
* Red Hat Enterprise Linux 8, 9
* Suse Linux Enterprise (aka sles) 15
* Ubuntu 20.04, 22.04
* Removed MC e2e from CI
* Updated Cloudtest manifests
=> MC E2E Distro Expansion

.github/workflows/insiders-fast.yml, .github/workflows/package-build.yml, .github/workflows/prod.yml
* Added explicit `ref` to perform package-building on a particular git ref
* Added `workflow_dispatch` for manual `insider-fast` publishing
=> Added workflow ability to build explicit git refs

.github/workflows/prod.yml
* Removed GitHub expression from workflow input, set to `main` branch
=> Removed expression from workflow default value

.github/workflows/prod.yml
* Corrected apt repos to use the distribution name for `prod` releases
=> Corrected apt release channel to use distribution name

.github/workflows/ci.yml
* Added `arm64` CI for scheduled runs only to prevent long CI time for PRs
=> Add arm64 CI on scheduled runs

.github/workflows/insiders-fast.yml
* Fixed `insiders-fast` publishing when previous runs have failed
=> Fixed workflow publishing when previous run failed

.github/workflows/insiders-fast.yml, .github/workflows/package-build.yml, .github/workflows/package-publish.yml, .github/workflows/prod.yml, .github/workflows/publish.yml, .github/workflows/universalnrp-test-run.yml, .github/workflows/universalnrp-test.yml, devops/README.md, devops/e2e/cloudtest/build-infra.json, devops/e2e/cloudtest/centos-8.json, devops/e2e/cloudtest/debian-10.json, devops/e2e/cloudtest/debian-11.json, devops/e2e/cloudtest/debian-12.json, devops/e2e/cloudtest/mariner-2.json, devops/e2e/cloudtest/oraclelinux-8.json, devops/e2e/cloudtest/rhel-8.json, devops/e2e/cloudtest/rhel-9.json, devops/e2e/cloudtest/rockylinux-9.json, devops/e2e/cloudtest/sles-15.json, devops/e2e/cloudtest/ubuntu-20_04.json, devops/e2e/cloudtest/ubuntu-22_04.json, src/adapters/mc/asb/CMakeLists.txt, src/adapters/mc/ssh/CMakeLists.txt
* Use new `build-infra` image for our container build infrastructure host instead of overloading the `ubuntu-22.04` image
* Added multi policy support for the Universal NRP test workflows allowing for testing both `LinuxSecurityBaselinePolicy.zip` and `LinuxSshServerSecurityBaselinePolicy.zip`
* Added `insiders-fast` / `prod` github environment mappings to package-build workflows for better PMC deployment tracking.
* Fixed `insiders-fast` publishing, added missing gh token.
* Updated VM image definitions to also include their base image reference
=> Various workflow updates, updated cloudtest definitions

devops/docker/debian-12-amd64/Dockerfile, devops/docker/debian-12-arm64/Dockerfile
Not sure if it was intentional, but switching to the debian 12 (bookworm) base image. (`bullseye` is debian 11)
=> devops/docker/debian-12*: actually use debian 12 base

.github/workflows/e2e.yml
* Removed push triggers from E2E tests
=> Removed push triggers from e2e tests

src/common/asb/Asb.h, src/common/commonutils/CommonUtils.h, src/platform/MpiServer.c
Build break on Mariner 2 and Debian 12 with new hardened compiler warnings. Bad structure in MPI Server code potentially causing segfault crash on low memory conditions. Plus some minor cleanup for ASB.
=> Fix for MPI server code

src/common/commonutils/DeviceInfoUtils.c
Some of the values being checked are not available on non-Debian/Ubuntu distros. Restricting the check to the kernel name for now, with possibility to add version in the future, helps auditing on the other distros.
=> Fixing the ASB AuditEnsureKernelCompiledFromApprovedSources check to run on all targeted distros

src/common/asb/Asb.c
=> Fixing one reversed Security Baseline audit check (AuditEnsureBind9NotInstalled is reversed)

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/FileUtils.c, src/common/commonutils/PassUtils.c
This PR started with ensuring the manner in which system files are not directly updated but instead, copied to a temporary copy, edited there then atomically renamed at the very end. Adding implementation for EnsurePasswordReuseIsLimited's remediation and consolidating audit, plus fixing implementation for the EnsureAvahiDaemonServiceIsDisabled  and EnsureCupsServiceisDisabled's remediation, also adding several remediations based on added configuration files to disable certain components, under /etc/modprobe.d.
=> Adding for Azure Security Baseline v2's EnsurePasswordReuseIsLimited check remediation and consolidating audit

.github/workflows/universalnrp-test-run.yml
* Logs were missing on test failure, added condition to log staging to prevent skipping
=> Fixed Universal NRP E2E logs on failure

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/FileUtils.c, src/common/commonutils/Internal.h, src/common/commonutils/MountUtils.c, src/common/commonutils/UserUtils.c
Making the save and restore of original ownership and access universal for all code paths that invoke the atomic renames at the end of editing such system files.
Also making the functions that use the rename() call for secure system file editing to ensure the source and target files are in the same folder to avoid errors such as EXDEV 18 /* Cross-device link */ as on some Linux installations certain system folders can be separately mounted.
=> Improved way of safe writing to system files to keep and restore original owner, group and access mode permissions

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/FileUtils.c, src/common/commonutils/OtherUtils.c, src/common/commonutils/PassUtils.c
Here are fixes for the following audit checks:
AuditEnsureSystemNotActingAsNetworkSniffer
AuditEnsureIpv6ProtocolIsEnabled
AuditEnsureZeroconfNetworkingIsDisabled
And completed implementations for the following remediation checks (with the exception of first, which is by design disabled due to possible disastrous effect):
RemediateEnsureDefaultDenyFirewallPolicyIsSet (no remediation)
RemediateEnsurePacketRedirectSendingIsDisabled
RemediateEnsureIcmpRedirectsIsDisabled
RemediateEnsureSourceRoutedPacketsIsDisabled
RemediateEnsureAcceptingSourceRoutedPacketsIsDisabled
RemediateEnsureIgnoringBogusIcmpBroadcastResponses
RemediateEnsureIgnoringIcmpEchoPingsToMulticast
RemediateEnsureMartianPacketLoggingIsEnabled
RemediateEnsureReversePathSourceValidationIsEnabled …
=> Advancing implementation for ASB v2 remediation and audit stabilization 

src/adapters/mc/asb/OsConfigPolicy.mof, src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/OtherUtils.c, src/modules/mim/securitybaseline.json
Adding a new initialization object and new policy parameter for ensuring default firewall policy is set to drop all to allow forcing remediation with first taking a snapshot and allowing all current channels and then blocking all new channels from there on. AuditEnsureDefaultDenyFirewallPolicyIsSet remains the same, RemediateEnsureDefaultDenyFirewallPolicyIsSet either does the same no-op or acts depending on this policy parameter which is currently set to disabled (0). Also fixing AuditEnsureIpv6ProtocolIsEnabled to not look for a system file that may not be correctly updated.
=> Adding a new ASBv2 policy parameter for EnsureDefaultDenyFirewallPolicyIsSet and fixing AuditEnsureIpv6ProtocolIsEnabled

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/OtherUtils.c, src/common/commonutils/PackageUtils.c
The invoked commands to disable wireless interfaces may be not present by default on all Linux distributions. One is optional (Network Manager) and we use it only if present, the other (RF Kill) is supposed to be present and if it's not, we try to install it and then execute it to disable all wireless interfaces.
=> Improving disabling all wireless interfaces for ASB v2

src/common/asb/Asb.c, src/common/commonutils/OtherUtils.c, src/common/commonutils/PackageUtils.c
Making ASB v2 audit checks that contains multiple sub-checks in an AND situation to fail at first sub-check fail in order to prevent a passing next sub-check from overwriting that audit result.
Also, changing the way presence of enabled wireless interfaces is checked to increase compatibility with various distros.
Plus, fixing a bug affecting remediation checks that need to install packages.
=> Preventing ASB v2 audit checks from overwriting themselves and other improvements

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/FileUtils.c, src/common/commonutils/UserUtils.c, src/common/commonutils/UserUtils.h, src/common/tests/CommonUtilsUT.cpp
Changes in this PR advance remediation implementation for ASB v2, completing the following checks:
RemediateEnsureFilePermissionsForAllRsyslogLogFiles
RemediateEnsureAllRsyslogLogFilesAreOwnedByAdmGroup
RemediateEnsureAllRsyslogLogFilesAreOwnedBySyslogUser
RemediateEnsureRsyslogNotAcceptingRemoteMessages
RemediateEnsureSyslogRotaterServiceIsEnabled
RemediateEnsureTelnetServiceIsDisabled
RemediateEnsureRcprshServiceIsDisabled
RemediateEnsureTftpServiceisDisabled
RemediateEnsureAtCronIsRestrictedToAuthorizedUsers
And also adding reasons for audits that fail when users and groups cannot be enumerated due to potential database corruption.
=> Advancing remediation implementation for ASB v2 and adding reasons for corrupted user and group databases

docs/architecture.md, src/common/asb/Asb.c, src/common/tests/CommonUtilsUT.cpp, src/modules/securitybaseline/README.md
Stabilizing audit and remediation for ASB v2, including fixes for:
- AuditEnsureSyslogRotaterServiceIsEnabled
- RemediateEnsureSyslogRotaterServiceIsEnabled
- RemediateEnsurePacketRedirectSendingIsDisabled 
Plus: 
- Adding unit-test coverage for a corner case of replacing escape sequences from strings and files, when the backslash character is alone at the end of the file or string.
- Updating documentation to bring it up to date with the code.
=> Continuing stabilization for ASB v2 audit and remediation

src/common/commonutils/UserUtils.c
This PR fixes the problem when Mariner accounts 'systemd-coredump' (79, 79) and 'systemd-oom' (80, 80) were detected non-system/can login due to missing shell being checked.
=> Fixing situation when on Mariner certain system accounts are not detected as such

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/FileUtils.c, src/common/commonutils/MountUtils.c, src/common/commonutils/PassUtils.c, src/common/commonutils/UserUtils.c, src/common/tests/CommonUtilsUT.cpp
Continued stabilization for ASB v2, including:
- Correcting the Samba service to look for in order to decide when Samba is active.
- Several improvements to file system mounting option remediations to cut unnecessary code and prevent a recursive buildup when lines without paths exist at top of the mounting table.
=> Fixing Samba service name used to check if Samba is running and more stabilization for ASB v2

src/common/asb/Asb.c, src/common/commonutils/SshUtils.c, src/common/commonutils/UserUtils.c
Fix in the APIs used by auditing and remediating user accounts desired to be removed, also a re-arrangement in the reasons issued for the SSH protocol audit to make them friendlier in audit-only case when OSConfig remediation does not exist.
=> Fixing ASB v2 audit and remediation for user accounts to be removed and reasons for SSH protocol audit

src/common/asb/Asb.c
The order in which rpcbind daemons are stopped and disabled matter on some of the distros.
=> Stabilizing the ASB v2 RemediateEnsurePortmapServiceIsDisabled check

src/adapters/mc/OsConfigResource.c, src/common/logging/Logging.c
Our CI needs to have access to NRP logs and cannot elevate to root after running the ASB v2 remediation. There is no reason to restrict the /var/log/ NRP logs to root-only. Once the NRP is done and is about to exit, we give others access to read the logs. Then once again the NRP resumes writing to the logs access gets automatically restricted back to root-only, the default.
=> Allowing read access to the NRP logs under /var/log

src/modules/test/CMakeLists.txt, src/modules/test/Common.h, src/modules/test/main.c
Making the module tester to be able to run the test recipe for Security Baseline and validate results in full for audit, except the 4 special case checks missing automatic remediation, alongside existing remediation verification.
Also fixing couple of memory leaks in the test and improving test logging for ASB.
Example of last line for an audit reported MIM object check pass:
[2024-06-13 14:26:19] [main.c:467] Assertion passed with reason: 'None of the requested user accounts ('games,test') is present'
=> Making the MIM test recipe for Security Baseline module test in full ASB v2, including confirming audits passing

src/common/asb/Asb.c, src/modules/test/main.c
Stabilization for ASB v2's auditEnsurePermissionsOnBootloaderConfig and remediateEnsurePermissionsOnBootloaderConfig
=> Stabilization for ASB v2's auditEnsurePermissionsOnBootloaderConfig and remediateEnsurePermissionsOnBootloaderConfig

src/common/asb/Asb.c, src/common/commonutils/FileUtils.c, src/common/commonutils/PassUtils.c, src/modules/test/main.c
Continued stabilization for ASB v2, here for auditEnsurePasswordCreationRequirements and remediateEnsurePasswordCreationRequirements. 
Plus enabling for test the stabilized auditEnsureReversePathSourceValidationIsEnabled and 
remediateEnsureReversePathSourceValidationIsEnabled.
=> Stabilizing ASB v2's auditEnsurePasswordCreationRequirements and remediateEnsurePasswordCreationRequirements

src/common/asb/Asb.c, src/modules/test/main.c
Stabilizing ASB v2's auditEnsureLoggingIsConfigured and remediateEnsureLoggingIsConfigured
=> Stabilizing ASB v2's auditEnsureLoggingIsConfigured and remediateEnsureLoggingIsConfigured

src/common/asb/Asb.c, src/common/commonutils/DaemonUtils.c, src/common/commonutils/PackageUtils.c, src/modules/test/main.c
Stabilizing ASB v2's auditEnsureAuditdInstalled and remediateEnsureAuditdInstalled, also auditEnsureAuditdServiceIsRunning and remediateEnsureAuditdServiceIsRunning.
=> Stabilizing ASB v2's auditEnsureAuditdInstalled and remediateEnsureAuditdInstalled

src/adapters/mc/asb/OsConfigPolicy.mof, src/common/asb/Asb.c, src/common/commonutils/PackageUtils.c, src/modules/test/main.c
Stabilizing ASB v2's auditEnsureRemoteLoginWarningBannerIsConfigured and remediateEnsureRemoteLoginWarningBannerIsConfigured . SLES 15 does not have /etc/issue.net.
=> Stabilizing ASB v2's auditEnsureRemoteLoginWarningBannerIsConfigured and remediateEnsureRemoteLoginWarningBannerIsConfigured 

src/common/asb/Asb.c, src/modules/test/main.c
Stabilizing ASB v2's auditEnsureSyslogRotaterServiceIsEnabled and remediateEnsureSyslogRotaterServiceIsEnabled. 
On Red Hat based distributions, the logrotate.timer service is not required for log rotation. The logrotate package handles log rotation automatically without the need to manually enable or start the timer service.
=> Stabilizing ASB v2's auditEnsureSyslogRotaterServiceIsEnabled and remediateEnsureSyslogRotaterServiceIsEnabled

.github/actions/sign-package/action.yml, devops/e2e/cloudtest/debian-10.json
* Fixed broken insiders publishing (incompatibility between actions/download-artifact@v3 and v4)
* Updated Debian-10 image to use `debian-10-daily` channel
=> Fixed signing and updated debian-10 base image

.github/actions/sign-package/action.yml
* Fixed `insiders-fast` publishing, updated missing `actions/upload-artifact` v3 to v4 conversion
=> Fixed upload-artifact to use v4

.github/actions/container-run/action.yml, .github/workflows/ci.yml, .github/workflows/package-build.yml
* Running into docker rate-limiting on occasion, removed the excessive pulling of binfmt from `docker/setup-qemu-action@v3`
=> Run native amd64 containers without QEMU

.github/workflows/package-build.yml
* Fixed invalid workflow reference `matrix.target.arch` from previous PR #737
=> Fixed invalid conditional for "Setup QEMU" action

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/asb/Asb.c, src/common/commonutils/PackageUtils.c, src/common/commonutils/UserUtils.c
Fix for ASB v2's remediateEnsureCupsServiceisDisabled (package uninstallation broken) and auditEnsureCupsServiceisDisabled (make it check just the essential, which is if service is active, ignoring the package) plus updated ASB and SSH policy names. 
Also adding support to remediateEnsurePasswordExpiration and auditEnsurePasswordExpiration for when a user's password has no expiration.
=> Fix for ASB v2's remediateEnsureCupsServiceisDisabled and auditEnsureCupsServiceisDisabled plus updated ASB and SSH policy names

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/asb/Asb.c, src/common/commonutils/UserUtils.c, src/common/commonutils/UserUtils.h
For ASB v2's remediateEnsurePasswordExpiration ensure that all user passwords have dates of last changes and if none, set those to today's dates at the time the remediation is ran. This together with setting the maximum number of days between password changes ensure the right expiration for user passwords. So new user accounts that never changed their password and have their passwords to never expire also get the correct expiration applied in the desired number of days from today.
Also removing from auditEnsurePasswordExpiration the previous workaround to assume that when there is no last password change then the expiration is from today as this is not only not necessary anymore, but can also hide audit failures for first time passwords without expiration dates.
=> For ASB v2's remediateEnsurePasswordExpiration ensure that all user passwords have dates of last changes

src/common/commonutils/PassUtils.c
Fixing a bug in the ASB v2's remediateEnsureLockoutForFailedPasswordAttempts implementation for Red Hat based distributions leading to corrupted /etc/pam.d/system-auth and denial of users to execute sudo.
=> Fixing ASB v2's remediateEnsureLockoutForFailedPasswordAttempts for Red Hat based distributions

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/asb/Asb.c, src/common/asb/Asb.h, src/common/commonutils/PassUtils.c
Two details that differentiate Ubuntu 16.04 and 18.04 from the other distributions targeted by ASB v2:
- The inbox PAM modules are stored under '/lib/x86_64-linux-gnu/security/'.
- The 'logrotate.timer' service is not installed by the 'logrotate' package.
- Normal procedure for setting lockout for failed password attempts may not work when none of the PAM modules that support the required features are available.
=> Fixing for ASB v2 default PAM modules location and logrotate.timer expectation for Ubuntu 16.04 and Ubuntu 18.04

src/common/asb/Asb.c, src/common/commonutils/PackageUtils.c
Ensuring the package managers presence is only checked once per ASB instance run.
Also reducing the risk to hit 'service started too quickly' for auditd and improving remediateEnsureAuditdServiceIsRunning
=> Ensuring the package managers presence is only checked once per ASB instance run

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/asb/Asb.c, src/common/commonutils/PassUtils.c
Adding the kernel version alongside pretty name to log at start of the ASB v2 run to more precisely identify the OS image ASB is running on.
=> Adding the kernel version alongside pretty name to log at start of the ASB v2 run to more precisely identify the OS image ASB is running on

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/commonutils/PassUtils.c
Fixing missed reason for ASB v2's auditEnsurePasswordReuseIsLimited leading to 'audit failure without a reason'.
Problem reported for the private preview policy package. Repro obtained in the CI automation:
[FileUtils.c:434] CheckFileExists: file '/etc/pam.d/common-password' exists
[FileUtils.c:434] CheckFileExists: file '/usr/lib/x86_64-linux-gnu/security/pam_unix.so' exists
[PassUtils.c:52] FindPamModule: the PAM module 'pam_unix.so' is present on this system as '/usr/lib/x86_64-linux-gnu/security/pam_unix.so'
[Asb.c:4422] [ERROR] AsbMmiGet(SecurityBaseline, auditEnsurePasswordReuseIsLimited): audit failure without a reason <<<
[Asb.c:4471] AsbMmiGet(SecurityBaseline, auditEnsurePasswordReuseIsLimited, "FAIL", 6) returning 0
And then fix confirmed in CI automation for this PR: …
=> Fixing missed reason for ASB v2's auditEnsurePasswordReuseIsLimited leading to 'audit failure without a reason'

.github/actions/pmc/entrypoint.sh
* Due to an internal change to the pmc image used for publishing, the pmc cli auth_type is required even though msal_client_id is set.  Added an explicit `msal` auth-type.
=> Fixed pmc bug, added explicit msal auth_type for pmc

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/commonutils/PackageUtils.c
For distros that have multiple package managers installed, add tracing that logs precisely for each invoked package manager operation which package manager and what command are being invoked. In order to help easier diagnose of PM operations on RHEL, SUSE and other distros.
=> Add more log tracing for the invoked package managers operations

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/commonutils/PackageUtils.c
Disabling the subscription manager plugin for YUM and DNF on RedHat-based distributions for ASB v2's package installed checks.  This parameter was found experimenting how we can speed up those checks on RAM constrained Hyper-V classic VMs hitting a timeout with AzPolicy otherwise. This is being tested by a deployed test policy deployed against VMs on such a RAM constrained Windows host.
=> Disabling the subscription manager plugin for YUM and DNF on RedHat-based distributions for ASB v2's package installed checks

src/adapters/mc/asb/19params/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
Re-adding the SSH port policy parameter for the SSH and ASB v2 test policies. This parameter was previously removed from the test policies in order to pass the maximum 20 parameters per policy limit from AzPolicy. The port is very important to be configurable for SSH though. So it's re-added here in two variants for each test definition: one with 19 SSH parameters as reference that cannot be published (gets to 21 with the 2 params for MC/AzP) and another with 18 SSH parameters that has port but excludes another SSH parameter of less significance. 
This change is being tested with newly published test policies for both SSH and ASB v2.
=> Re-adding the SSH port policy parameter for the SSH and ASB v2 test policies

src/adapters/mc/asb/19params/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/asb/Asb.c, src/common/commonutils/DeviceInfoUtils.c, src/common/commonutils/FileUtils.c, src/common/tests/CommonUtilsUT.cpp
Prevent CheckFileContents cause an invalid reason to fail json_value_init_string and cascade into a false passing audit. Random contents from checked system files can cause breaks into the JSON envelope for transport if included in the reason, skip those. Also, if still an invalid reason arrives, switch it to a generic fail reason.
Also, write directly to '/proc/sys/kernel/randomize_va_space' rather than staged via a temp file to avoid case where on SUSE the staged write may fail due to parent directory access.
=> Prevent CheckFileContents cause an invalid reason to fail json_value_init_string and cascade into a false passing audit

src/adapters/mc/asb/19params/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/asb/Asb.c, src/common/asb/Asb.h, src/common/commonutils/CommonUtils.h, src/common/commonutils/DaemonUtils.c, src/common/commonutils/DeviceInfoUtils.c, src/common/commonutils/SshUtils.c
Fixing ASB v2's auditEnsureSystemdJournaldServicePersistsLogMessages and remediateEnsureSystemdJournaldServicePersistsLogMessages and adding detection (for now, just with tracing, ASB customization if any to come in later) for Azure Commodore.
=> Fixing ASB v2's auditEnsureSystemdJournaldServicePersistsLogMessages and remediateEnsureSystemdJournaldServicePersistsLogMessages

.github/workflows/universalnrp-test.yml
The policy package name for ASB v2 was recently changed in order to match the name of the ASB v1 package that it will replace. There was one missed instance that affects the automated MC CI pipeline. This PR fixes that.
=> Updating the ASB v2 policy package name for the MC CI automation tests

src/common/commonutils/CommandUtils.c, src/common/commonutils/DeviceInfoUtils.c, src/common/commonutils/FileUtils.c, src/common/commonutils/PassUtils.c, src/common/commonutils/SshUtils.c, src/common/commonutils/UrlUtils.c, src/modules/commandrunner/tests/CommandRunnerTests.cpp, src/modules/configuration/src/lib/Configuration.c, src/platform/MpiServer.c, src/platform/tests/PlatformTests.cpp
The following changes fix miscellaneous issues detected by the address sanitizer in the unit tests.
=> Fix various issues reported by address sanitizer reported from the unit tests

src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/common/commonutils/FileUtils.c
Fixing ASB v2 temporary file creation race condition that may lead to /etc/shadow file exposure to unprivileged users. There is a window of time during which an unprivileged user may get a file descriptor of our temp file, wait for us to finish writing to it, and then read. That file content we just wrote may be of protected files such as /etc/shadow, that are not normally allowed to be read by normal users.
Many thanks to [robertwoj-microsoft](https://github.com/robertwoj-microsoft) who spotted this bug and proposed the fix.
The fix is being tested with the CI, plus manual running of unit-tests, functional test recipe tests, and also building and deploying a custom policy package containing the fix and validating results of that.
=> Fixing ASB v2 temporary file creation race condition that may lead to /etc/shadow file exposure to unprivileged users

src/common/commonutils/FileUtils.c
If we call both close() and fclose() on the same file descriptor and file stream, it can lead to undefined behavior:
- fclose(): This function flushes the stream, writes any buffered output data, and closes the underlying file descriptor. After calling fclose(), any further access to the stream results in undefined behavior.
- close(): This function closes the file descriptor. If we call close() after fclose(), we are attempting to close an already closed file descriptor, which can lead to errors or unexpected behavior.
=> Avoiding double close on temp file handle

.github/workflows/build-containers.yml, .github/workflows/github.yml, .github/workflows/insiders-fast.yml, .github/workflows/package-build.yml, .github/workflows/package-publish-pmc.yml, .github/workflows/prod.yml, .github/workflows/publish-github.yml, .github/workflows/publish-pmc.yml, devops/docker/ubuntu-14.04-amd64/Dockerfile
* Added Ubuntu 14.04 Trusty build support (GCC 4.8) for building Machine Configuration policy packages
* Added `Publish (GitHub)` workflow which doesn't publish just yet but currently builds the MC policy packages for Ubuntu 14.04 Trusty
* Fixed `Build Containers` workflow to build the specified containers when the `distro_list` input is provided
* Added a `buildForMachineConfiguration` input to the `package-build.yml` workflow to control whether to build the policy packages for MC or Debian/RPM packages
* Renamed the `publish.yml` workflow to `publish-pmc.yml` to reflect the the new GItHub publishing variant with PMC
=> Adding Ubuntu 14.04 and 'OSConfig for MC' policy packages build workflow

.github/workflows/ci-sanitizers.yml, .github/workflows/github.yml, .github/workflows/nrp-build.yml, .github/workflows/package-build.yml, devops/docker/ubuntu-14.04-amd64/Dockerfile, src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
This PR cuts unnecessary dependencies for NRP and policy packages build on Ubuntu 14 workflow. As fewer dependencies we have to install there, as safer we are on such an old distribution. With this occasion also adjusting some of the names (as the workflow is for building 'OSConfig for MC' aka NRP and policy packages, not publishing it), cutting unnecessary steps (building CMake 3, signing off the policy package, etc.), enabling for PRs and nightly runs the new sanitizers CI, and also used to run our full CI validation on the new policy packages stored at https://github.com/Azure/azure-osconfig/releases/tag/test_policy_package.
=> Cutting unnecessary dependencies for NRP and policy packages build on Ubuntu 14 workflow

.github/workflows/build-containers.yml, devops/docker/ubuntu-14.04-amd64/Dockerfile
Re-adding building from source CMake 3 for Ubuntu 14 build of the NRP and the policy packages to the Ubuntu 14 Docker container.
=> Re-adding building from source CMake 3 for Ubuntu 14 build of the NRP and the policy packages

src/common/commonutils/DeviceInfoUtils.c
In case the lscpu command fails or is not present on a system, the rule called auditEnsureKernelSupportForCpuNx will trigger 
GetCpuFlags function call which returns NULL in this case. This commit adds additional NULL check for the cpuFlags variable to avoid passing NULL pointer to strstr function.
=> Fix possible NULL dereference when lscpu command fails

src/common/commonutils/DeviceInfoUtils.c
Hardening commonutils!DeviceUtils functions for cases when ExecuteCommand succeeds without any text results.
=> Hardening commonutils!DeviceUtils functions for cases when ExecuteCommand succeeds without any text results

src/common/asb/Asb.c, src/common/commonutils/PassUtils.c
First set of bugfixes found through fuzzing:
* fix leaks in some remediation paths. These remediation functions call audit functions that return an allocated reason string, but the string was not being free'd.
* fix leak of pamModulePath3 in SetPasswordCreationRequirements()
=> First set of bug fixes resulting from fuzzing (work in progress)

src/modules/CMakeLists.txt, src/platform/CMakeLists.txt
Small optimization for compiler check for platform and modules build. Using if-elseif-endif instead of 2x if-endif.
=> Small optimization for compiler check for platform and modules build

src/common/asb/Asb.c
When rule names were last touched in:
- #779 
a typo was introduced in the spelling of `Ensure` (main has `EEnsure`). Fix the typo.
=> asb: Fix typo in spelling Ensure

src/adapters/pnp/CMakeLists.txt
Check if `/etc/aziot` exists before trying to install it during build. This change fixes a build failure on machines when the build is running as non-root. We should never be writing files to /etc/ during building and no one should be building as root.
Ideally this custom command would be removed or moved behind a cmake `option()`.
=> Only install aziot config if the directory exists

src/modules/securitybaseline/src/lib/SecurityBaseline.c
… or earlier
Disabling atomic reference counting for Security Baseline module only when compiler is gcc 4.8 or earlier, in order to not disable in production builds but only in test builds done with gcc 4.8 (and not with clang or newer gcc).
=> Disabling atomic reference counting for Security Baseline module only when compiler is gcc 4.8

src/common/parson/parson.c
Fix a memory leak in parson by adding a missing free in parson's `parse_object_value` implementation. The leak is triggerable from our code through fuzzing and we bundle parson so we're responsible for fixing issues in it.
`get_quoted_string` returns an allocated string and all other branches in the loop contain the call to `parson_free` (which is `free` by default). This fix is based on how upstream parson implemented the bugfix: https://github.com/kgabis/parson/commit/ab7f5e5401d45462f517f204e5ce52d80d7dbcd6.
=> Fix memory leak in parson's parse_object_value()

src/common/commonutils/OtherUtils.c, src/common/tests/CommonUtilsUT.cpp, src/tests/fuzzer/seed_corpus/CheckFileSystemMountingOption-2.target
FormatAllocateString has multiple issues:
- it always allocates at least 512 bytes even when the input is shorter
- once the length of the formatted output exceeds 512 bytes it starts incrementing the buffer size by 1 byte and goes through a `malloc,snprintf,free` loop until it finds the right size. This has an O(n^2) complexity and is slow for longer strings.
- it has an unnecessary `DuplicateString` at the end
Rewrite FormatAllocateString to call `snprintf` once to calculate the required buffer size, then `malloc` the right buffer and then format the string.
This change is motivated by hitting this edge case through fuzzing `CheckFileSystemMountingOption` where a lot of reason strings get added to the reason buffer. I've added a test case for long strings and a fuzzer case whose runtime …
=> Fix FormatAllocateString complexity

devops/scripts/asa/Dockerfile-ubuntu22, devops/scripts/asa/README.md, devops/scripts/asa/run_asa.sh, devops/scripts/asa/scan.sh
Scans are running in the container.
`podman` or `docker` on host system is needed to run the script. 
The Default is `docker`, can be configured in [run_asa.sh](run_asa.sh).
Using instructions are included in the README.md file in this PR.
* For now container image does not include systemd so the service related functionality and related ASA scans are omitted
* ASA scan does not run TPM checks
* Scans are now executed only on Ubuntu 22.04
* Support for running ASA scans in the container with RPM based distro
* Run as a part of the GHA pipeline
=> Add scripts to run microsoft/AttackSurfaceAnalyzer for the azure-osconfig

devops/scripts/asa/Dockerfile-centos8, devops/scripts/asa/Dockerfile-ubuntu22, devops/scripts/asa/README.md, devops/scripts/asa/run_asa.sh
* ASA Scans running on CentOS 8 Added.
* Base container images locked by SHA256 to improve hermeticity.
=> Add ASA scans running on CentOS 8

src/modules/test/Module.c, src/modules/test/main.c
`moduletest` has memory leaks in the test runnner itself that can be seen when running it from a build-tree that has sanitizer enabled (or `-DBUILD_FUZZER=1`). By fixing these leaks in the test runner itself, we won't miss leaks happening inside the tested libraries.
=> Fixing memory leaks in moduletest

.github/workflows/fuzzing.yml
Add a trigger to the fuzzing workflow that runs it nightly. The fuzzing runs will need to be periodically reviewed to see if there are any failures.
=> github: Run fuzzing nightly

.github/workflows/module-test.yml
Restore missing target to the moduletest workflow.
=> Restore Debian 12 to moduletest workflow

.github/workflows/universalnrp-test.yml
* Added Azure storage support to download compliant packages from Azure Storage instead of non-compliant GitHub artifacts. Adds support for `storage://` scheme where it downloads our compliant artifacts and stores them into GitHub artifacts.
=> Added Azure Storage Support for policy packages

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/DeviceInfoUtils.c, src/common/commonutils/FileUtils.c
Several ASB ModuleTest steps have started failing after the release of RHEL 9.5. Looking into them, I found that they are failing due to issues with selinux file contexts. The failure comes from `chage` when changing password expiration settings, after a previous rule modified `/etc/shadow`,`/etc/shadow-`,`/etc/passwd`,`/etc/passwd-`. With additional output from `chage` one can see the following:
```
[2024-11-26 09:00:27] [main.c:604] Step 3 of 16
[2024-11-26 09:00:27] [main.c:614] Running desired test 'SecurityBaseline.remediateEnsurePasswordExpiration'
[2024-11-26 09:00:27] [UserUtils.c:2400] EnsureUsersHaveDatesOfLastPasswordChanges: all users who have passwords have dates of last password changes
[2024-11-26 09:00:27] [UserUtils.c:2289] SetMaxDaysBetweenPasswordChanges: user …
```
=> Restore selinux context when replacing config files

src/common/commonutils/PackageUtils.c
Two issues:
On a freshly configured system (VM/container/server) the apt cache may not be populated initially.  This causes any remediation task that requires package installation to happen to fail. Ensure we update the package cache on the first invocation of a function that attempts to install a package.
With this change `apt-get update` is done once and only on demand. Some remediation functions need to be revised to better interact with this, for example `RemediateEnsureAuditdServiceIsRunning`. `RemediateEnsureAuditdServiceIsRunning` attempts to install 4 different package candidates, some of which may not be available in a distro version at all. Each such probe could trigger an `apt-get update`, even if a later package in the list is already installed. This scenario is not critical …
=> Fix module test failure on Debian 12

src/common/commonutils/SshUtils.c, src/common/tests/CMakeLists.txt, src/common/tests/Helper.c, src/common/tests/Helper.h, src/common/tests/SshUtilsUT.cpp
`BackupSshdConfig()` passes `log` to `SavePayloadToFile()`, but it doesn't take a `log` parameter. This is picking up the function pointer to the log(arithm) function instead. If there is any error in `SavePayloadToFile`, logging segfaults. Add the missing parameter.
To ensure this doesn't regress, added unit tests for internals of `SshUtils`. These will be extended with new test cases.
=> Add missing 'log' argument in BackupSshdConfig

src/common/tests/CMakeLists.txt, src/common/tests/SshUtilsUT.cpp
The file was missing an `#include <system_error>` statement. With this change `commontests` builds on centos 7/rhel 7/oracle linux 7 and ubuntu 14.04 again, so there is no reason to make the include of these files conditional.
=> Fix SshUtilsUT build on GCC 4.8 distros

src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
Updating the custom test policy reference definitions to point them to policy packages for 12/24 manual validation. We are keeping these for now in here and with manual updates because of partners that are already using these definitions from these locations. In the future we may replace this process with an automated one or else, tbd.
=> Updating the custom test policy reference definitions

.github/workflows/universalnrp-test.yml, devops/e2e/cloudtest/almalinux-9.json
Onboard Alma Linux 9 to the universal NRP test workflow. Includes infrastructure changes to onboard the Alma Linux 9 managed image to our pool.
=> Add Alma Linux 9 to universal NRP tests

.github/workflows/module-test.yml, src/common/asb/Asb.h, src/common/commonutils/DeviceInfoUtils.c, src/common/commonutils/FileUtils.c, src/common/commonutils/PackageUtils.c, src/common/tests/CommonUtilsUT.cpp
Stabilization fixes during manual validation, including:
- Consolidation of the friendly distro name constants in Asb.h.
- Replaced Check* function with local ExecuteCommand for DetectSelinux() function in order to simplify and do not log extra.
- The ExecuteCommand call for IsCommodore does not need to format results for JSON.
- CheckFileExists, CheckFileNotFound need to return ENOENT instead EEXIST when file not found.
- Making  SetEtcConfValue fail with ENOENT in case of file not found instead of 0 and masking the remediation failure in logs.
- Added zypper refresh and forced uninstall functionality for Red Hat based distros (similar to apt-get update for Ubuntu/Debian).
- Temporarily removing RTHEL 7 from ModuleTest run: CommandRunner does not build there.
=> Stabilization fixes for hardening and optimization found during current manual Azure Policies validation for ASB v2

src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json, src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
Updating the reference custom test policy definitions in the existing locations, where our partners expect them to be found:
- Updating the policy package hashes to point to current securely built test policy packages.
- Correcting formatting for the 2 SSH definitions to expand tabs to 2 spaces instead of 4 spaces per tab.
=> Updating the reference custom test policy definitions

src/common/asb/Asb.c, src/common/tests/CommonUtilsUT.cpp
Making auto-validation for rule UUIDs case insensitive to allow future easy changes between lowercase and uppercase UUIDs in ASB MOF. Keeping case sensitive comparison for rule names.
=> Making auto-validation for rule UUIDs case insensitive to allow future easy changes between lowercase and uppercase UUIDs in ASB MOF

devops/e2e/cloudtest/build-infra.json
* Universal NRP Tests failed because the `build-infra` image did not have the `bc` package installed. It seems the base image regressed (1ES PT - Ubuntu 22.04 - vNext) so explicitly added `bc` package.
* Image has already been tested and works (https://github.com/Azure/azure-osconfig/actions/runs/12658469701)
=> Added bc to build-infra image

.github/workflows/module-test.yml, .github/workflows/universalnrp-test.yml
* Removed EOL distros rhel-7 and debian-10 (EOL June 30, 2024) from e2e automation (Module and UniversalNRP Tests)
=> Removed EOL distros rhel-7 debian-10

.github/workflows/module-test.yml, .github/workflows/universalnrp-test.yml
* Removed CentOS8 from automated e2e tests (MC + nrp tests)
=> Remove centos-8 from e2e automated tests

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Updating CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md to refer to 'dev' branch instead of 'main'.
=> Updating CONTRIBUTING.md to use 'dev' branch instead of 'main'

.github/actions/check-perf/action.yml, src/common/commonutils/PerfUtils.c
- Fixing one corner case bug in GetPerfClockTime() where elapsed times won't be properly recorded.
- Small improvement to LogPerfClock() to log decimals for minutes and seconds.
- Typo fix in the 'Check performance' GitHub action YML.
=> Stabilization for the execution speed performance automation

.github/actions/check-perf/action.yml, .github/actions/check-size/action.yml, .github/workflows/universalnrp-test.yml
New GitHub action to check policy package size added to existing Universal NRP workflow. Today our two packages are ~ 280 kB each. The current limit is 290 kB. We'll see how this goes in CI and adjust (increase) later if justified (for example, for the future CIS baseline).
=> New simple action to check policy package size

devops/e2e/cloudtest/debian-10.json, devops/e2e/cloudtest/debian-12.json, devops/e2e/cloudtest/ubuntu-20_04.json, devops/e2e/cloudtest/ubuntu-22_04.json
* Removed .NET 6.0 SDK. from images this was a previous requirement for the dotnet e2e tests but they are no longer being used.
=> Removing EOL .NET 6 SDK

src/common/parson/cgmanifest.json
Adding component governance manifest for parson.
=> Adding manifest for component governance

src/adapters/mc/OsConfigResource.c
Fix crashes in MC adapter for SecurityBaseline when AsbMmiGet fails:
- set proper MI_RESULT when AsbMmiGet failed
- initialize OsConfigResource_TestTargetResource so that we won't try to destroy based on undefined memory
=> Fix crashes in MC adapter for SecurityBaseline when AsbMmiGet fails

src/adapters/mc/OsConfig.schema.mof, src/adapters/mc/OsConfigResource.c, src/adapters/mc/OsConfigResource.h, src/adapters/mc/schema.c
Add ProcedureObjectName and ProcedureObjectValue fields to OsConfig schema and OsConfigResource
Add support for multiple Components in OsConfigResource.
=> Add ProcedureObjectName and ProcedureObjectValue to OsConfig Schema

src/modules/test/recipes/SecurityBaselineTests.json
Temporarily removing 'auditd' related tests from Module Test pass as they do not give reliable results. Keeping them only in MC test pass for now.
=> Temporarily removing auditd related tests from Module Test pass

.devcontainer/devcontainer.json
* Added pre-commit to devcontainer
* Removed `postCreateCommand` from the devcontainer as the `submodule update --init` should be done on the host when initially cloning
=> Added pre-commit to devcontainer, removed postCreateCommand

src/adapters/mc/CMakeLists.txt, src/adapters/mc/compliance/Baseline.c, src/adapters/mc/compliance/CMakeLists.txt, src/modules/CMakeLists.txt, src/modules/compliance/CMakeLists.txt, src/modules/compliance/src/CMakeLists.txt, src/modules/compliance/src/lib/CMakeLists.txt, src/modules/compliance/src/lib/ComplianceInterface.cpp, src/modules/compliance/src/lib/ComplianceInterface.h, src/modules/compliance/src/so/CMakeLists.txt, src/modules/compliance/src/so/ComplianceModule.c, src/modules/compliance/tests/CMakeLists.txt, src/modules/compliance/tests/ComplianceTests.cpp
This PR introduces basic, mostly empty placeholders for the Compliance module and MC adapter. The goal is to have a clear starting point and separate the work done for POC into smaller, digestible bits.
This PR contains work done by @wupeka.
=> Compliance module and MC adapter skeleton

src/modules/test/recipes/SecurityBaselineTests.json
Temporarily disable EnsureCronServiceIsEnabled (audit and remediation) test cases for Module Test. These are unreliable and randomly fail on several distros during Module Test CI. For now they will remain in the MC CI tests.
=> Temporarily disable EnsureCronServiceIsEnabled (audit and remediation) test cases for Module Test

src/modules/test/CMakeLists.txt
Currently when invoking 'make clean' command, SecurityBaselineTest.json module test recipe is removed. Fix this behavior by attaching to a stamp file output.
=> Fix cleanup of SecurityBaseline module test recipe

.github/workflows/build-containers.yml, .github/workflows/ci.yml, .github/workflows/module-test.yml, .github/workflows/universalnrp-test.yml, devops/docker/azurelinux-3-amd64/Dockerfile, devops/e2e/cloudtest/azurelinux-3.json
* Added cloudtest definition for azurelinux-3
* Onboarded to both Universal NRP Tests + ModuleTests
* Added missing almalinux-9 in module tests
* Changed container build policy to build on merge to `dev` instead of `main`
=> Onboarding Azure Linux 3 into CI automation tests

src/common/logging/Logging.h
Logging.h file uses types from stdio and is missing inclusion.
=> Add missing stdio.h include

src/adapters/mc/OsConfigResource.c, src/common/asb/Asb.c, src/common/commonutils/FileUtils.c, src/common/logging/Logging.c
Previously the default used for various text files (config, log, temporary) as well as unix sockets was 06774. This has more permissions than necessary and also some bits set that are unexpected for text files:
- x77x makes the log files owner/group executable
- 6xxx means set user id + set group id. These bits are for privilege elevation.
Change the default permissions to 0660 for `RestrictFileAccessToCurrentAccountOnly` and 0644 for NRP. This maintains the intended access to these files.
=> Narrow file permissions used when creating text files

src/adapters/mc/compliance/CMakeLists.txt, src/tests/fuzzer/CMakeLists.txt
At the moment builds with fuzzer enabled fail due to rigorous link-time checks. This commit fixes the issue.
=> Fix building Compliance MC adapter with fuzzer enabled

.github/actions/defer-tests/action.yml, .github/workflows/module-test-run.yml, .github/workflows/universalnrp-test.yml, src/modules/test/recipes/SecurityBaselineTests.json
This PR adds some waits and disables daily jobs on debian-based systems. The tests were failing due to races between module tests which use apt for package management and other system services: azsecd and daily update jobs.
We add 2 additional stages to the module test:
- disablement of daily jobs
- waiting for packages that are automatically installed on specific distros, mainly azsec-bpftrace
We revert temporarily disabled module tests.
=> Fix module tests failures caused by apt-get race conditions

src/common/logging/Logging.h, src/modules/compliance/src/lib/Engine.h
This commit fixes a small regression introduced by merging PRs #872 #863.
Thie #872 fixed missing inclusion of stdio, but I did not handle the merge of #863 properly and the change from #872 got reverted unintentionally.
=> Fix stdio inclusion regression

src/modules/compliance/src/lib/ComplianceInterface.cpp, src/modules/compliance/src/lib/Engine.cpp, src/modules/compliance/src/lib/Engine.h, src/modules/compliance/src/lib/Evaluator.cpp, src/modules/compliance/src/lib/Evaluator.h, src/modules/compliance/src/lib/MmiResults.h, src/modules/compliance/tests/ComplianceTest.cpp, src/modules/compliance/tests/EngineTest.cpp, src/modules/compliance/tests/EvaluatorTest.cpp
Simplify ExecuteAudit by encapsulating payload in the result. Previously used AuditResult type used char array with size, this has been changed to std::string for simplification. ExecuteAudit calls no longer require output parameters and return the payload in the function result.
=> Simplify ExecuteAudit by encapsulating payload in the result

.clang-format
The .clang-format file contains a duplicated entry which fails for some versions of clang-format tool. This PR drops the duplicated entry.
=> Drop a duplicated entry in the .clang-format file

src/modules/compliance/src/lib/Engine.cpp, src/modules/compliance/src/lib/Engine.h, src/modules/compliance/src/so/ComplianceModule.c, src/modules/compliance/tests/EngineTest.cpp
Due to code rearrangements the Compliance module did not properly open log file in the RC/DC scenario. This PR moves log file initialization to the ComplianceModule.c and unifies compliance::Engine class initalization. The changes were tested manually.
=> Fix missing OpenLog call in RC/DC scenario

.github/workflows/fuzzing-run.yml, .github/workflows/fuzzing.yml, src/tests/fuzzer/target.cpp
Currently fuzzer CI action is only run on manual or scheduled dispatch. Enable the action on pull request in build-only mode.
Fix existing fuzzer issues once again after recent merges.
Removing Evaluator fuzzing targets as they no longer support custom procedure map.
=> Include fuzzer build in pipeline and fix issues

src/common/commonutils/DaemonUtils.c
EnableAndStartDaemon improperly handles errors, fix it.
=> Fix EnableAndStartDaemon: properly propagate failure

src/modules/test/recipes/SecurityBaselineTests.json
Auditd clashes with auoms service installed on Azure VMs. This causes auditd service to fail to run due already-existing PID file shared with auoms.
Some failed module test executions show that auditd fails on pidfile creation. In such cases, the following show what's the PID file content:
```
[2025-03-05 13:00:49][INFO][Asb.c:3024] -------------------------------- auditctl -s -----------------------------------------
[2025-03-05 13:00:49][INFO][Asb.c:3026] enabled 1
failure 1
pid 5587
rate_limit 0
backlog_limit 10240
lost 0
backlog 0
backlog_wait_time 1
backlog_wait_time_actual 0
loginuid_immutable 0 unlocked
```
Here we can see the PID is 5587. Excerpt of `ps auxf` output in this case shows the following:
```
root        2197  0.6  0.2 1175784 20008 ?       Ssl  12:56   0:01 …
```
=> Permanently disable auditd module tests

.pre-commit-config.yaml, devops/docker/almalinux-9-amd64/Dockerfile, devops/docker/amazonlinux-2-amd64/Dockerfile, devops/docker/centos-7-amd64/Dockerfile, devops/docker/centos-8-amd64/Dockerfile, devops/docker/oraclelinux-7-amd64/Dockerfile, devops/docker/oraclelinux-8-amd64/Dockerfile, devops/docker/rhel-9-amd64/Dockerfile, devops/docker/rockylinux-9-amd64/Dockerfile, devops/docker/sles-15-amd64/Dockerfile, devops/docker/ubuntu-14.04-amd64/Dockerfile
* Removes the `devops/docker/.*/Dockerfile` exclusion from the `trailing-whitespace` and `mixed-line-ending` pre-commit hooks in the `.pre-commit-config.yaml
=> Remove dockerfiles from pre-commit exclusion

.github/workflows/universalnrp-test.yml, src/adapters/mc/OsConfigResource.c, src/common/asb/Asb.c, src/common/logging/Logging.c, src/common/logging/Logging.h
Adding logging option to disable console logging from the OSConfig Universal NRP. Since the NRP runs loaded in an MC worker process started by the MC agent and not directly loaded into the MC agent process we cannot rely on the daemon check.
=> Adding logging option to disable console logging from the OSConfig Universal NRP

.github/actions/defer-tests/action.yml
There was a case where defer-tests action would end up in an infinite loop state on Marinuer 2 distro. This PR adds a 5-minute timeout to the wait loop to prevent the action from hanging indefinitely.
=> Introduce timeout for wait loop in tests

src/common/commonutils/CommandUtils.c, src/common/commonutils/CommonUtils.h, src/common/tests/CommonUtilsUT.cpp
Rework ExecuteCommand:
- use only single fork() instead of three.
- read stdout/stderr via a pipe and not via a temporary file, reducing IO overhead
- reduce number of possible failure points
- simplify the function flow and increase readability
=> Rework ExecuteCommand - use single fork, read stdout/stderr via a pipe

.github/workflows/build-containers.yml
The th-actions/change-files version we use is vunrable to cve 
https://www.cve.org/CVERecord?id=CVE-2025-30066
Update to the not vunrable one
=> pipeline: update tj-actions/change-files to post cve

.clang-tidy, .pre-commit-config.yaml, src/common/commonutils/CommonUtils.h, src/modules/compliance/src/lib/Base64.cpp, src/modules/compliance/src/lib/ComplianceInterface.cpp, src/modules/compliance/src/lib/Engine.cpp, src/modules/compliance/src/lib/Engine.h, src/modules/compliance/src/lib/Evaluator.cpp, src/modules/compliance/src/lib/Evaluator.h, src/modules/compliance/src/lib/JsonWrapper.cpp, src/modules/compliance/src/lib/JsonWrapper.h, src/modules/compliance/src/lib/Optional.h, src/modules/compliance/src/lib/Procedure.cpp, src/modules/compliance/src/lib/Procedure.h, src/modules/compliance/src/lib/Result.h, src/modules/compliance/src/lib/TypeTraits.h, src/modules/compliance/src/lib/procedures/ensureFilePermissions.cpp, src/modules/compliance/src/lib/procedures/ensureFilesystemOption.cpp, src/modules/compliance/tests/Base64Test.cpp, src/modules/compliance/tests/EngineTest.cpp, src/modules/compliance/tests/EvaluatorTest.cpp, src/modules/compliance/tests/OptionalTest.cpp, src/modules/compliance/tests/ResultTest.cpp, src/modules/compliance/tests/procedures/ensureFilesystemOptionTest.cpp, src/tests/clang-tidy/run-clang-tidy.py
Introduce clang-tidy to the project. Currently it only works on the src/modules/compliance directory.
=> Introduce clang-tidy

src/common/commonutils/PackageUtils.c
Make tdnf, dnf and yum run commands run with '--cacheonly' and only once per instance update the cache with 'check-update'.
=> Make tdnf, dnf and yum run commands run with '--cacheonly' and only once per instance update the cache with 'check-update'

src/common/tests/CommonUtilsUT.cpp
Add CheckPackageManagerNotThrottling test to detect package manager throttling (error 429) when 'is installed' command are executed in as fast as possible sequence. This is for related PR #917.
=> Add CheckPackageManagerNotThrottling test

src/common/commonutils/CommandUtils.c, src/common/tests/CommonUtilsUT.cpp
- Fix a bug in ExecuteCommand tests re: cancelation
- Limit the size of the logged too long command to 100 characters
=> Execute command test and logging fixes.

src/common/tests/CommonUtilsUT.cpp
Add CheckPackageManagerNotThrottling test (#924)
(cherry picked from commit 7eb7da9ac9d1316fa66cd5be948a947e5f5904bd)
The test companion for cherry pick PR #923.
=> Add CheckPackageManagerNotThrottling test (#924)

src/CMakeLists.txt, src/adapters/mc/OsConfigResource.c, src/adapters/mc/README.md, src/cmake/templates/version.h.in
Current nrp logs lack any version information. Log a line with NRP version information during `Load()`. Extend the version string used for this purpose to include the git commit. The version string now looks like this:
```
1.0.5.20250314-g32f48703
```
This is the same convention used by `git describe.`
The version string is also in an ELF section called `.version.info` so that it is possible to extract it from an existing SO with command line utilities easily:
```
$ readelf -p .version.info build/adapters/mc/compliance/libOsConfigResourceCompliance.so 
String dump of section '.version.info':
[     0]  1.0.5.20250314-g32f48703
```
=> Log NRP version including git commit

src/common/commonutils/DeviceInfoUtils.c
This code is executed on every package related operation on RedHat-like systems and results in many lines in the log that say something like:
[2025-03-19 13:25:42][INFO][DeviceInfoUtils.c:826] Running on 'AlmaLinux 9.5 (Teal Serval)' which is Red Hat based
Reduce the number of log messages by caching the state of this check.
=> common: Cache IsRedHatBased calculation

.vscode/settings.json, src/modules/compliance/src/lib/ComplianceInterface.cpp, src/modules/compliance/src/lib/Engine.cpp, src/modules/compliance/tests/EngineTest.cpp
At the moment the compliance engine accepts only base64-encoded JSON input. For RC/DC scenario we want to support also plain JSON object payload. This is useful for compliance module tests as well.
=> Support plain JSON object payload in RC/DC scenario

.clang-format, src/modules/compliance/src/lib/Engine.cpp, src/modules/compliance/src/so/ComplianceModule.c
This change results in more readable multiline strings, because they no longer get indented all the way to the '=' sign. Refreshed formatting on all files in src/modules/compliance, which also caught an include ordering change.
=> clang-format: Adjust AlwaysBreakBeforeMultilineStrings setting

src/modules/test/recipes/SecurityBaselineTests.json
Module tests are now broken due to a bug in EnsureUnnecessaryAccountsAreRemoved rule remediation. This PR disables the tests TEMPORARILY to bring up all the module tests. When the issue is fixed, this change can be reverted.
=> Temporarily disable EnsureUnnecessaryAccountsAreRemoved module tests

src/modules/compliance/src/lib/procedures/ensureFilePermissions.cpp, src/modules/compliance/src/lib/procedures/ensureFilePermissions.schema.json, src/modules/compliance/tests/procedures/ensureFilePermissionsTest.cpp
1. Use "owner" and not "user" parameter
2. Change behaviour of mask and permissions - mask has bits that must be cleared, permissions has bits that must be set
3. Full suite of unit tests
=> Fixes and tests for ensureFilePermissions procedures

src/common/commonutils/CommandUtils.c, src/common/commonutils/CommonUtils.h
Add functionality that allows mocking ExecuteCommand calls, to be used in unit tests.
=> Add the ability to mock ExecuteCommand calls

.github/workflows/module-test-run.yml, src/modules/test/main.c
Prepare module tests to run compliance module tests which are intended to be split into separate recipe files. This PR separates work included in #913 as asked: https://github.com/Azure/azure-osconfig/pull/913#discussion_r2001793137
- Allow to run module tests from a subdirectory (use find command)
- Allow to verify if NULL has been reported as the output payload (helps testing failures)
This PR depends on #934 as currently module tests are broken.
=> Prepare module tests to run compliance tests

src/modules/compliance/src/lib/payload.schema.json, src/modules/compliance/src/lib/procedures/ensureNoUserHasPrimaryShadowGroup.cpp, src/modules/compliance/src/lib/procedures/ensureNoUserHasPrimaryShadowGroup.schema.json, src/modules/test/recipes/compliance/ensureNoUserHasPrimaryShadowGroup.json
Introduce a procedure to check if any of the system users has the shadow group as their primary group. The CIS rule consists of 2 checks which are done separately:
- check if shadow is a supplementary group for anyone - this is done by fileRegexMatch procedure, not included in this PR
- check if shadow is a primary group for anyone - this new procedure covers this case.
=> CIS Ubuntu 22.04 7.2.4: ensureNoUserHasPrimaryShadowGroup procedure

src/modules/CMakeLists.txt
The jsonschema is giving DeprecationWarning as below
DeprecationWarning: The jsonschema CLI is deprecated and will be removed in a future version. Please use check-jsonschema instead, which can be installed from https://pypi.org/project/check-jsonschema/
*Describe your changes in as much detail as possible. Provide a link/reference to the issue solved with this request if any.*
=> build: change jsonschema to check-jsonschema

src/common/asb/Asb.c, src/common/commonutils/CommandUtils.c, src/common/commonutils/PackageUtils.c
Adding safety timeouts for package manager operations (30 minutes, which can act during RC/DC where we do not have overall timeouts like Azure Policy) and increasing the test limit for remediations (5 minutes per rule, this being the actual fix to the random CI failures, problem being that we just had too strict limits there, which we expected and now thanks to such findings we are adjusting).
=> Adding safety timeouts for package manager operations and increasing the test limit for remediations 

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/PackageUtils.c, src/common/tests/CommonUtilsUT.cpp
We are unintendedly blocking the package managers during ASB audit by invoking the package managers at every rule to check if one of more packages are installed, one by one. We can speed up the overall ASB audit time and also avoid blocking the package managers so much by listing all installed packages once per session and saving to a cache buffer, then when looking to see if a package is installed, to search in that buffer without making any new package manager request. 
We refresh this cache when installing and uninstalling packages during automatic remediation (where we still need to do one package at a time, but nobody complained yet about that, and also remediation does not happen continuously like audit, being executed only once in most cases). In audit-only case however, there …
=> [Hot Fix] Optimizing auditing presence of packages 

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/PackageUtils.c, src/common/tests/CommonUtilsUT.cpp
We are unintendedly blocking the package managers during ASB audit by invoking the package managers at every rule to check if one of more packages are installed, one by one. We can speed up the overall ASB audit time and also avoid blocking the package managers so much by listing all installed packages once per session and saving to a cache buffer, then when looking to see if a package is installed, to search in that buffer without making any new package manager request.
We refresh this cache when installing and uninstalling packages during automatic remediation (where we still need to do one package at a time, but nobody complained yet about that, and also remediation does not happen continuously like audit, being executed only once in most cases). In audit-only case however, there shall …
=> [Hot Fix] Optimizing auditing presence of packages (cherry pick)

.pre-commit-config.yaml
By default pre-commit hooks for multiple files are launched in parallel. Since we're rewriting the payload.schema.json in place, if more than one file affected the schema was changed there was a race condition in which one of the executions opened the file for writing (truncating it), while another one tried to read it, leading to failure.
Serialize the execution of JSON schema generation to avoid races.
=> Serialize the execution of JSON schema generation to avoid races.

src/modules/compliance/src/lib/ComplianceInterface.cpp, src/modules/compliance/tests/ComplianceTest.cpp
Currently, MmiSet/MmiGet error for a single audit causes the whole benchmark to stop. Only return an error when it's really critical.
=> Don't throw an Mmi{Get,Set} error on an audit/remediation non-critical error

src/common/commonutils/CommandUtils.c
ExecuteCommand was crashing if using MockCommand and textResult was null.
=> Fix mock ExecuteCommand crash when textResult is null

src/modules/compliance/src/lib/Procedure.cpp, src/modules/compliance/src/lib/procedures/testingProcedures.cpp, src/modules/compliance/src/lib/procedures/testingProcedures.schema.json, src/modules/compliance/tests/EngineTest.cpp, src/tests/fuzzer/seed_corpus/ProcedureUpdateUserParameters.target, src/tests/fuzzer/target.cpp
For the compliance module we accept a basic syntax for key-value pairs as input for init and remediation functions:
`key1=value1 key2=value2`
Currently we only split string by space which is obviously not enough for cases where the value contains spaces or equality sign.
This PR introduces a possibility to quote values:
`key1="value1" key2='value2'`
Both single quote and double quote are supported.
To handle cases where the quote itself is part of the value, we allow escaping it with a backslash:
`key1="value1\"s" key2="value2"`
To fulfill this, we also support escaping the backslash itself:
`key1="value1\\" key2=value2`
Here the value for KEY1 is `value1\`.
Special thanks to Jeremi for adding fuzzing target for this feature.
=> Introduce user-defined parameters quoting

src/modules/compliance/src/lib/Evaluator.h, src/modules/compliance/src/lib/GenProcedureMap.sh, src/modules/compliance/src/lib/procedures/ensureAllGroupsFromEtcPasswdExistInEtcGroup.cpp, src/modules/compliance/src/lib/procedures/ensureAllGroupsFromEtcPasswdExistInEtcGroup.schema.json, src/modules/compliance/src/lib/procedures/ensureFilePermissions.cpp, src/modules/compliance/src/lib/procedures/ensureFilePermissions.schema.json, src/modules/compliance/src/lib/procedures/ensureFilesystemOption.cpp, src/modules/compliance/src/lib/procedures/ensureFilesystemOption.schema.json, src/modules/compliance/src/lib/procedures/ensureKernelModule.cpp, src/modules/compliance/src/lib/procedures/ensureKernelModule.schema.json, src/modules/compliance/src/lib/procedures/ensureNoDuplicateEntriesExist.cpp, src/modules/compliance/src/lib/procedures/ensureNoDuplicateEntriesExist.schema.json, src/modules/compliance/src/lib/procedures/ensureNoUserHasPrimaryShadowGroup.cpp, src/modules/compliance/src/lib/procedures/ensureNoUserHasPrimaryShadowGroup.schema.json, src/modules/compliance/src/lib/procedures/fileRegexMatch.cpp, src/modules/compliance/src/lib/procedures/fileRegexMatch.schema.json, src/modules/compliance/src/lib/procedures/packageInstalled.cpp, src/modules/compliance/src/lib/procedures/packageInstalled.schema.json, src/modules/compliance/src/lib/procedures/testingProcedures.cpp, src/modules/compliance/src/lib/procedures/testingProcedures.schema.json, src/modules/compliance/tests/EvaluatorTest.cpp, src/modules/compliance/tests/procedures/ensureFilePermissionsTest.cpp, src/modules/compliance/tests/procedures/ensureFilesystemOptionTest.cpp, src/modules/compliance/tests/procedures/ensureKernelModuleTest.cpp, src/modules/compliance/tests/procedures/fileRegexMatchTest.cpp, src/modules/test/recipes/compliance/EnsureAllGroupsFromEtcPasswdArePresentInEtcGroup.json, src/modules/test/recipes/compliance/EnsureNoDuplicateEntriesExist.json, src/modules/test/recipes/compliance/EnsureNoUserHasPrimaryShadowGroup.json, src/modules/test/recipes/compliance/FileRegexMatch.json
To comply with our own naming convention, we should drop underscores from function names and use CamelCase.
=> Normalize compliance procedure names

src/modules/compliance/src/lib/procedures/ensureFilePermissions.cpp, src/modules/compliance/tests/procedures/ensureFilePermissionsTest.cpp, src/modules/test/recipes/compliance/EnsureFilePermissions.json
Add a bunch of module tests and fix some issues popped up during testing:
- Do not allow passing both permissions and mask parameters to ensureFilePermissions
- Fix mask handling
- Do not report error but return failure if a user/group does not exist
=> EnsureFilePermissions compliance check module tests

src/modules/compliance/src/lib/procedures/ensureNoDuplicateEntriesExist.cpp, src/modules/compliance/src/lib/procedures/ensureNoDuplicateEntriesExist.schema.json
Add missing schema decorators for AUDIT_FN macro which causes failures of the JSON schema validator in Augmentation Engine pipeline.
=> Fix EnsureNoDuplicateEntriesExist schema

src/modules/compliance/src/lib/CMakeLists.txt, src/modules/compliance/src/lib/Engine.cpp, src/modules/compliance/src/lib/procedures/ensureFilePermissions.cpp
Add -Wshadow=local to prevent coding error
Enable -Wshadow to utilize compiler checks better when local variables shadows some wider scope variable it usually can lead to an error.
I spend some time debugging code due the fact of pasting code sniped that I added during refactoring. 
```
int value = 0;
if (importantThing != end) {
int value = *importatntThing;
ExecuteStuff(value);
}
return value;
```
=> Add -Wshadow=local to prevent coding errors

src/modules/compliance/src/lib/GenJSONSchemas.py, src/modules/compliance/src/lib/payload.schema.json, src/modules/compliance/src/lib/procedures/ensureSysctl.cpp, src/modules/compliance/src/lib/procedures/ensureSysctl.schema.json, src/modules/compliance/src/lib/procedures/testingProcedures.cpp, src/modules/compliance/src/lib/procedures/testingProcedures.schema.json, src/modules/compliance/tests/EngineTest.cpp, src/modules/compliance/tests/procedures/ensureSysctlTest.cpp, src/modules/test/recipes/SecurityBaselineTests_EnsureSyctl.json
EnsureSysctl validates the runtime sysctl value by reading /proc/sys/sysctl and if that is compliant validates the configuration values to make sure system stays compliant upon next reboot.
The configuration validation is done using
/lib/systemd/systemd-sysctl --cat-config
=> EnsureSysctl: Initial implementation

src/modules/compliance/src/lib/CMakeLists.txt, src/modules/compliance/src/lib/Result.cpp, src/modules/compliance/src/lib/Result.h, src/modules/compliance/src/lib/procedures/ensureKernelModule.cpp, src/modules/compliance/tests/procedures/ensureKernelModuleTest.cpp
In the container environment that we test in lsmod is not always available. This may also be the case on customer machines. /proc/modules is guaranteed to be present (it is also the underlying data source for lsmod), and has the same (pretty much) layout (modulename at the start of the line). Switch to parsing cat /proc/modules output.
=> EnsureKernelModule: Use /proc/modules for data

src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json
Updating the ASB test policy definition with the new parameter for configuring the logging level. Validated this definition in our test subscription, with the test package published at https://github.com/Azure/azure-osconfig/releases/tag/test_policy_package (anyone who wants, can also give it a try). The logging level for Azure OSConfig running on each Arc server under audit can be configured at time of the policy assignment to any one of the 7 possible values.
=> Updating the ASB test policy definition with the new parameter for configuring the logging level

src/adapters/pnp/daemon/osconfig.json, src/common/asb/Asb.c, src/common/commonutils/Internal.h, src/common/commonutils/UserUtils.c
The changes in this PR increase customer's privacy in case that the Azure OSConfig logs are sent back to Microsoft, redacting out from logging things such as:
- usernames for real, human user accounts.
- group names for real user accounts.
- home directory names for real user accounts.
Users and groups are now mainly identified by their numeric UID and GID.
The only private information may remain at Debug (7) logging level, where raw output (that we do not directly control) of system commands is logged for debugging purposes. For this the logs warn the user:
'Debug logging is enabled and this may include private information such as unredacted usernames'
Here are examples of redacted logging.
During users enumeration, debug level traces that redact real usernames and homes:
```
[2025-04-22 …
```
=> Redacting out from ASB logging usernames, group names, home directory names, etc. for real user accounts (as opposed to system users)

src/modules/compliance/src/lib/GenJSONSchemas.py
Improve AUDIT_FN parsing and add more contet to errors raised.
When AUDIT_FN(EnsureFoo, "arg1:some arg stuff:M", ) is valid it shows
vauge description of error. Check if last arg tokken is empty and rasie
ValueError.
When args are improperly quotes add all args to ValueError
=> GenJSONSchemas: Improve error reporting, handle trailing comma and add info on quote

src/modules/test/recipes/compliance/EnsureSyctl.json
Fix & enable  sysctl module tests revert (#975) 
This reverts commit b3ea690f78ffddd6be4890a56b5459ef70d0686f.
The CBL Mariner had and issue with sysctl net.ipv4.ip_forward - some agent changed the settings during test and in turn the test keep failing randomly.  This fixes this by changing tested sysctl so the CBL Mariner test works.
=>  Fix & enable  sysctl module tests revert (#975) 

src/common/asb/Asb.c
The auoms service is part of Microsoft's Operations Management Suite (OMS) and is used for collecting audit events from Linux systems. The auoms service conflicts with auditd service which is required under ASB to be enabled and running. To mitigate this conflict, during remediateEnsureAuditdServiceIsRunning we try to stop and disable auoms and if that is not possible, we log a warning, and during auditEnsureAuditdServiceIsRunning we fail the audit if we find auoms running.
=> Mitigating conflict between the auoms and auditd services during ASB remediation

.github/workflows/static-analysis.yml, devops/docker/centos-8-amd64/Dockerfile, devops/docker/ubuntu-22.04-amd64/Dockerfile, src/adapters/mc/OsConfigResource.c, src/adapters/pnp/PnpAgent.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/ConfigUtils.c, src/common/commonutils/DaemonUtils.c, src/common/commonutils/DeviceInfoUtils.c, src/common/commonutils/FileUtils.c, src/common/commonutils/OtherUtils.c, src/common/commonutils/PackageUtils.c, src/common/commonutils/PassUtils.c, src/common/commonutils/SshUtils.c, src/common/commonutils/UserUtils.c, src/common/logging/Logging.c, src/common/mpiclient/MpiClient.c, src/common/tests/CommonUtilsUT.cpp, src/modules/compliance/src/lib/CMakeLists.txt, src/modules/compliance/tests/OptionalTest.cpp, src/modules/compliance/tests/ResultTest.cpp, src/modules/compliance/tests/procedures/EnsureFilePermissionsTest.cpp, src/modules/test/Module.c, src/platform/Main.c, src/platform/MmiClient.c, src/platform/ModulesManager.c, src/platform/MpiServer.c
Add clang static analysis to our CI. This relies on clang's internal analyzer, called through a script shipped with clang called analyze-build (there exists also a helper tool called scan-build).
This PR also fixes all of the findings. The findings were (in quantity)
* dead stores (writes to variables that are never used or read)
* memory leaks (missing frees on some paths through functions)
* destroying uninitialized objects (OsConfigResource.c)
* mismatched new[]/delete[] (mmi payloads should be free'd using the modules free function)
* use after move in tests disabled using ifdef __clang_analyzer__ (the tests intentionally test to move constructor).
If there are findings in the future, the best way is to download the artifact from the workflow, unpack and open index.html which provides …
=> Add clang static analysis worfklow

devops/e2e/cloudtest/mariner-2.json
* Updated `mariner-2` base image to use a Gen2 VM as there seems to be disk-space issues with the previous image Gen1 image. Already tested new ES image which fixed previously failing test runs.
=> Updated base image for mariner-2

.github/workflows/universalnrp-test.yml, devops/docker/ubuntu-24.04-amd64/Dockerfile, devops/e2e/cloudtest/ubuntu-24_04.json
This PR adds recipes for an Ubuntu 24.04 worker pool image and a build container. After the PR is merged, the worker pool needs to be created manually and then we can add testing to CI jobs. Adding Ubuntu 24.04 to testing is needed for CIS but will also help us validate things in preparation for when Ubuntu 24.04 is added to the ASB support matrix.
Sidenote: `Canonical:ubuntu-24_04-lts:server:latest` is a Gen2 image.
```
$ az vm image show --urn Canonical:ubuntu-24_04-lts:server:latest --query 'hyperVGeneration' --output tsv
V2
```
=> Add ubuntu 24.04 ci images

.vscode/settings.json, src/modules/compliance/src/lib/Regex.h, src/modules/compliance/src/lib/RegexFallback.h, src/modules/compliance/src/lib/procedures/EnsureKernelModule.cpp, src/modules/compliance/src/lib/procedures/EnsureSshdOption.cpp, src/modules/compliance/src/lib/procedures/FileRegexMatch.cpp, src/modules/compliance/tests/CMakeLists.txt, src/modules/compliance/tests/RegexFallbackTest.cpp, src/modules/compliance/tests/RegexTest.cpp
We have a fallback solution for non-functional std::regex on old and unsupported distributions (RHEL-7/8 and derivatives). This PR adds sub-pattern matching drop-in replacement matching `std::smatch` and adds support for `regex_search(t, m, r)`, previously we only supported `regex_search(t, r)`.
_Note_: Naming convention (CamelCase etc.) is not held on purpose to keep in line with `std::` equivalents.
=> Add regular expressions sub-pattern functionality fallback

src/modules/compliance/src/lib/procedures/EnsureFilePermissions.cpp, src/modules/compliance/tests/procedures/EnsureFilePermissionsTest.cpp, src/modules/test/recipes/compliance/EnsureFilePermissions.json
CIS considers a missing file to be compliant for file mode/group/user checks. See this output from a test:
```
<xccdf:check-content>
<command_result href="sce/nix_owner_chk.sh"
xccdf="pass"
script="(...)/sce/nix_owner_chk.sh"
exit-value="101">
<out>
<l/>
<l>- Audit Result:</l>
<l>  ** PASS **</l>
<l> - "/boot/grub/grub.cfg" doesn't exist</l>
</out>
<err/>
<env/>
</command_result>
</xccdf:check-content>
```
Adjust `EnsureFilePermissions` and test to match that behavior.
I considered whether it makes sense to add a parameter (eg. `allowMissing`) to control this behavior but since we map `nix_(owner|group|mode)chk.sh` to `EnsureFilePermissions` and this is their semantic, I don't see us needing the current behavior (non-compliant on missing).
=> EnsureFilePermissions: Return Compliant on missing file

devops/docker/ubuntu-24.04-amd64/Dockerfile
The version of gtest that comes with Ubuntu 24.04 requires C++14 and we still intend to support C++11 for some time. So switch to a building gtest from source, to match other distributions we test on. Only after this is merged, we'll be able to add 24.04 to CI jobs.
This is a action where I tested the Ubuntu 24.04 container: https://github.com/Azure/azure-osconfig/actions/runs/14858148831/job/41716256749#step:5:1065
```
analyze-build-18: INFO: In file included from /__w/azure-osconfig/azure-osconfig/src/modules/deviceinfo/tests/DeviceInfoTests.cpp:4:
analyze-build-18: INFO: In file included from /usr/include/gtest/gtest.h:64:
analyze-build-18: INFO: In file included from /usr/include/gtest/gtest-assertion-result.h:46:
analyze-build-18: INFO: In file included from …
```
=> devops: ubuntu-24.04: Install gtest manually

src/modules/compliance/src/lib/CommonContext.cpp
When context::ExecuteCommand fails because the command failed (returned non-zero status code) provide the combined stdout/stderr as the error message.
=> Provide output from ExecuteCommand in case of error

src/modules/compliance/src/lib/procedures/EnsureFilePermissions.cpp, src/modules/compliance/src/lib/procedures/EnsureFilePermissions.schema.json, src/modules/compliance/tests/procedures/EnsureFilePermissionsTest.cpp, src/modules/test/recipes/compliance/EnsureFilePermissions.json
Alternative version of EnsureFilePermission that instead of filename argument takes a directory and "extension" (e.g. '*.exe')
=> Add 'Collection' mode to EnsureFilePermission audit and remediation procedures

src/common/asb/Asb.c
This ASB rule: { "Ensure that postfix network listening is disabled", "d0cc4e35-70a1-4ee5-b572-3b969201562e", "EnsurePostfixNetworkListeningIsDisabled" }, needs to be fixed to pass audit (and skip remediation) when the postfix package is not installed.
=> Fix ASB rule "Ensure that postfix network listening is disabled" to pass audit when postfix package is not installed

src/common/asb/Asb.c
Fix for ASB's "Ensure permissions on bootloader config are configured (CIS: L1 - Server - 1.4.1)" rule by adding a missing GRUB configuration file which is necessary on Azure Linux 3.
=> Fix for ASB's "Ensure permissions on bootloader config are configured (CIS: L1 - Server - 1.4.1)" rule

src/adapters/mc/OsConfigResource.c, src/common/commonutils/FileUtils.c, src/common/logging/Logging.c
Cherry-pick of #877 to main: remove the SUID/SGID/EXEC bits from log files as they may alarm users.
=> Narrow file permissions used when creating text files (#877) to main

src/common/commonutils/CMakeLists.txt
CommonUtils.h includes Logging.h. Mark `logging` as a PUBLIC dependency of `commonutils` so that this information is propagated to dependent targets.
This doesn't chang anything because all existing targets linking to commonutils must also link to logging.
=> Mark logging as PUBLIC dependency of commonutils

src/common/commonutils/PassUtils.c
The change in this PR applies a fix for Azure Linux where the rule "{ "Ensure password reuse is limited (CIS: L1 - Server - 5.3.3)", "57bdeae2-863e-14fb-a463-d6ee64816b33", "EnsurePasswordReuseIsLimited" }". The implementation of this rule sets an option in separate PAM files for Debian and RedHad based systems. This PR adds a 3rd file choice necessary for Azure Linux 3.
=> On Azure Linux '/etc/pam.d/system-password' is expected to exist and should be used for password reuse

src/common/commonutils/SshUtils.c, src/modules/test/recipes/SecurityBaselineTests.json
This fixes the { "Ensure that the SSH warning banner is configured (CIS: L1 - Server - 5.2.19)", "9e240540-5e0a-4b60-beb2-57421c65a0b9", "EnsureSshWarningBannerIsEnabled" } rule audit making it check only that there is a banner file set as banner with the SSH server and that the file exists. Previous implementation was requiring specific file name and content, which were meant to come from policy parameters, but ASB does not expose any and this makes this bad experience for customers. We still keep the same automatic remediation.
=> Fix for ASB's "Ensure that the SSH warning banner is configured (CIS: L1 - Server - 5.2.19)" rule

src/modules/compliance/src/lib/procedures/EnsureRootPath.cpp, src/modules/compliance/tests/procedures/EnsureRootPathTest.cpp
- Eliminate static analysis detected potential memleak
- Add a comment about the sudo usage
=> A minor fix to the EnsureRootPath test

src/modules/compliance/src/lib/CMakeLists.txt, src/modules/compliance/src/lib/FactExistenceValidator.cpp, src/modules/compliance/src/lib/FactExistenceValidator.h, src/modules/compliance/src/lib/GenJSONSchemas.py, src/modules/compliance/src/lib/RegexFallback.h, src/modules/compliance/src/lib/procedures/EnsureSysctl.schema.json, src/modules/compliance/src/lib/procedures/FileRegexMatch.cpp, src/modules/compliance/src/lib/procedures/FileRegexMatch.schema.json, src/modules/compliance/tests/CMakeLists.txt, src/modules/compliance/tests/FactExistenceValidatorTest.cpp, src/modules/compliance/tests/procedures/FileRegexMatchTest.cpp, src/modules/test/recipes/compliance/FileRegexMatch.json
Rework and rebase #997 
procedure used to test the state pattern against the full line. In general, the state pattern should match against a captured value with a given instance. **The instance is for now skipped and will be added later based on actual needs, for now it defaults to 1.** <- **WARNING**
*Describe your changes in as much detail as possible. Provide a link/reference to the issue solved with this request if any.*
=> FileRegexMatchTest introduce match sub pattern and behaviors

src/modules/compliance/src/lib/procedures/SystemdUnitState.cpp, src/modules/compliance/src/lib/procedures/SystemdUnitState.schema.json, src/modules/compliance/tests/procedures/SystemdUnitStateTest.cpp
SystemdUnitState: add Unit parameter 
This is to support Systemd.timer.
Systemd.timer has Unit= parameter which indicates systemd unit to activate when systemd.timer expires.
=> SystemdUnitState: add Unit parameter

src/modules/complianceengine/src/lib/procedures/EnsureSysctl.cpp, src/modules/complianceengine/src/lib/procedures/EnsureSysctl.schema.json, src/modules/complianceengine/tests/procedures/EnsureSysctlTest.cpp, src/modules/test/recipes/compliance/EnsureSyctl.json
- Make the checks more verbose
- Use context for proper mocking, get rid of fake procfs
- Check ufw configuration if the value is missing in systemd-sysctl
=> EnsureSysctl procedure fixes:

src/modules/complianceengine/src/lib/ComplianceEngineInterface.cpp, src/modules/test/recipes/complianceengine/ExecuteCommandGrep.json
We have a graceful way of handling non-critical incompliance messages in the `ComplianceEngineMmiGet` function. This functionality prevents from prematurely aborting audit runs and allows GC worker to continue evaluation if a single rule fails.
The Augmentation Engine parses the outputs reported in the reason field and used to match against a 'failed to' string. However, this is incorrect as the messages vary and rely strictly on the procedures' outputs.
This PR adds a static prefix that we can attach to instead of the 'failed to' which is too generic and can be used in compliant cases.
=> Add a prefix to a non-critical incompliance message

.github/workflows/ci-sanitizers.yml, src/CMakeLists.txt, src/common/commonutils/FileUtils.c, src/modules/samples/cpp/src/lib/Sample.cpp, src/modules/samples/cpp/src/lib/Sample.h, src/modules/samples/cpp/tests/SampleTests.cpp
Fix sanitizers unit tests workflow. Previously, we would pass wrong arguments to the cmake command due to double quote escaping.
=> Fix sanitizers unit tests workflow

src/modules/complianceengine/src/lib/FilePermissionsHelpers.cpp, src/modules/test/recipes/complianceengine/EnsureFilePermissions.json
If no 'mask' argument is provided, we currently show spurious compliant message, e.g.: '/etc/crontab mask matches expected mask 0'.
=> Fix compliance message in EnsureFilePermissions

src/modules/complianceengine/src/lib/procedures/EnsureGroupIsOnlyGroupWith.cpp, src/modules/complianceengine/src/lib/procedures/EnsureGroupIsOnlyGroupWith.schema.json, src/modules/complianceengine/src/lib/procedures/EnsureUserIsOnlyAccountWith.cpp, src/modules/complianceengine/src/lib/procedures/EnsureUserIsOnlyAccountWith.schema.json
Fix an error I have introduced by merging #1080. The invalid pattern causes json schema validation issues on the augmentation engine side.
=> Fix the numeric pattern

src/common/commonutils/SshUtils.c
Add SSH ands ASB special 'none' case for rule 'Ensure that the SSH warning banner is configured'
=> Add SSH ands ASB special 'none' case for rule 'Ensure that the SSH warning banner is configured'

src/adapters/mc/asb/CMakeLists.txt, src/adapters/mc/ssh/CMakeLists.txt
Splitting the policy packages for SSH and ASB into Get and Set parts. We need this cherry picked to main to allow us to release the package updates for 2506.
=> Splitting the policy packages for SSH and ASB into Get and Set parts

src/common/commonutils/DeviceInfoUtils.c
Fixing one remaining case in which ASB's EnsureCoreDumpsAreRestricted rule audit can end in audit failure without a reason phrase.
=> Fixing one remaining case in which ASB's EnsureCoreDumpsAreRestricted rule audit can end in audit failure without a reason phrase

.github/workflows/module-test.yml, .github/workflows/universalnrp-test.yml
Our CI is down for some time now due to consistent failures of Mariner 2 self-hosted VMs provisioning.
Disable temporarily - if it's possible to restore these machines then we can revert this PR.
=> Temporarily disable Mariner 2 builds

src/modules/complianceengine/src/lib/FilePermissionsHelpers.cpp, src/modules/test/recipes/complianceengine/EnsureFilePermissions.json
Improve indicator content for EnsureFilePermissions rule.
=> Improve EnsureFilePermissions mask mismatch indicator

src/modules/complianceengine/src/lib/KernelModuleTools.cpp, src/modules/complianceengine/src/lib/procedures/ExecuteCommandGrep.cpp, src/modules/complianceengine/tests/MockContext.h, src/modules/complianceengine/tests/procedures/EnsureKernelModuleTest.cpp
Use opendir/fts directory traverse instead of find to search filesystem for modules
Allow 'arch' command in ExecuteCommandGrep
=>  Use opendir/fts directory traverse instead of find to search filesystem for modules

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/FileUtils.c, src/common/tests/CommonUtilsUT.cpp
This PR includes a fix for all ASB rules that search under '/etc/modprobe.d'. This fixes a bug where no-op files such as README.md ones could fool us. The fix ensures that we only look at '.conf' files. Plus few other improvements and also extending the automation test cases accordingly.
=> ASB fix for rules that search under '/etc/modprobe.d'

src/common/asb/Asb.c, src/common/commonutils/UserUtils.c, src/common/commonutils/UserUtils.h, src/common/tests/CommonUtilsUT.cpp, src/modules/test/recipes/SecurityBaselineTests.json
This PR contains hardening for 2 ASB rules:
- EnsureAllRsyslogLogFilesAreOwnedByAdmGroup
- EnsureAllRsyslogLogFilesAreOwnedBySyslogUser
(both audit and remediation)
The hardening consists in checking if group 'adm' and user 'syslog' exist, and if not, to warn the user that automatic validation is not possible (we do not want to blindly create the group and/or account and risk breaking the local security).
=> Hardening 2 ASB rules (EnsureAllRsyslogLogFilesAreOwnedByAdmGroup and EnsureAllRsyslogLogFilesAreOwnedBySyslogUser)

src/modules/complianceengine/src/lib/ComplianceEngineInterface.cpp, src/modules/complianceengine/src/so/ComplianceEngineModule.c
Loading JSON configuration file was missing for Compliance Engine module. It's done the same way as it was for Security Baseline module.
=> Load configuration from json config file in Compliance Engine initialization

src/common/asb/Asb.c, src/common/commonutils/UserUtils.c, src/common/commonutils/UserUtils.h, src/common/tests/CommonUtilsUT.cpp, src/modules/test/recipes/SecurityBaselineTests.json
This PR adds fix for the ASB's EnsureAllRsyslogLogFilesAreOwnedByAdmGroup and EnsureAllRsyslogLogFilesAreOwnedBySyslogUser rules remediations:
- When the 'syslog' user does not exist, add it as a system, non-login user.
- When 'adm' does not exist, add it as a system group.
=> ASB fix for EnsureAllRsyslogLogFilesAreOwnedByAdmGroup and EnsureAllRsyslogLogFilesAreOwnedBySyslogUser remediations

src/common/logging/Logging.c
Adding GMT offset to logged times. We used to have this in the past and maybe it was not merged as it is still missing. This allows us to see real times from Virtual Machines especially that show time in GMT only.
Produces date and time stamps like this:
[2025-09-26 15:49:55-0700]
=> Adding GMT offset to logged times

.github/workflows/universalnrp-test.yml
* Fixed broken Universal NRP Test - images still must be updated to have Git v2.18+ but this unblocks the workflow
PR #1116 broke the tests
=> Fixed broken git checkout on universal nrp test

src/common/commonutils/CommonUtils.h, src/common/commonutils/OtherUtils.c, src/common/tests/CommonUtilsUT.cpp
Slight hardening FREE_MEMORY macro:
- Check for not just non-null, but also for: misalignment, low addresses, and out-of-range values.
- Reset pointer to null before freeing.
=> Hardening the FREE_MEMORY macro

src/common/asb/Asb.c, src/common/commonutils/CommonUtils.h, src/common/commonutils/OtherUtils.c
Fix for ASB's EnsureDefaultDenyFirewallPolicyIsSet rule: add a fallback case using firewalld when iptables is not present, as both methods are equivalent in function.
=> Fix for ASB's EnsureDefaultDenyFirewallPolicyIsSet rule 
