Azure/azure-osconfig

src/modules/networking/src/lib/Networking.cpp
src/modules/networking/src/lib/Networking.h
src/modules/networking/tests/NetworkingTests.cpp

Restored the Networking module to request and process IP data in the default format. The prior implementation that used the ip(8) '-json' flag was found to have a support gap on Debian 9, where the flag is unavailable.

Restored the Networking module to request IP data in the default format

---

src/tests/e2etest/TpmTests.cs

Add tpm e2e tests

---

README.md
docs/modules.md

Added to documentation in modules.md content about arrays and maps.

Adding to arrays and maps to documentation

---

docs/architecture.md
docs/modules.md

Documentation updates for MIM arrays and maps

Documentation updates for MIM arrays and maps

---

devops/pipeline/e2etest.yaml

Update E2E test Ubuntu 20.04 VM image version to `latest.

Update ubuntu image version to latest

---

src/CMakeLists.txt
src/modules/CMakeLists.txt
src/modules/samples/CMakeLists.txt
src/modules/samples/cpp/CMakeLists.txt
src/modules/samples/cpp/src/CMakeLists.txt
src/modules/samples/cpp/src/lib/CMakeLists.txt
src/modules/samples/cpp/src/lib/Sample.cpp
src/modules/samples/cpp/src/lib/Sample.h
src/modules/samples/cpp/src/so/CMakeLists.txt
src/modules/samples/cpp/src/so/SampleModule.cpp
src/modules/samples/cpp/tests/CMakeLists.txt
src/modules/samples/cpp/tests/SampleTests.cpp

Implement a sample module in `C++` in `src/modules/samples`. This module contains a basic implementation of a module written in `C++` to demonstrate best practices and act as a starting point for new module developers (*.so, module lib, testing, CMake).

Create sample C++ module

---

src/CMakeLists.txt

Bump version from `0.4.1` to `0.5.0`.

Bump version to 1.0.0

---

src/common/logging/Logging.c
src/modules/samples/cpp/tests/SampleTests.cpp
src/modules/ztsi/src/lib/Ztsi.cpp
src/modules/ztsi/src/lib/Ztsi.h
src/modules/ztsi/src/so/ZtsiModule.cpp
src/modules/ztsi/tests/ZtsiTests.cpp

Refactor ZTSI module to apply patterns from sample module.

Update ZTSI module

---

CONTRIBUTING.md

Adding information on submitting a PR to CONTRIBUTING.md

Adding information on submitting a PR to CONTRIBUTING.md

---

src/modules/mim/sample.json
src/modules/samples/cpp/src/lib/Sample.cpp
src/modules/samples/cpp/src/lib/Sample.h
src/modules/samples/cpp/tests/SampleTests.cpp

Add a MIM JSON for the sample module (and all future samples) to implement. Updated sample module to match MIM.

Add sample module MIM JSON

---

src/modules/schema/mmi-payload.schema.json
src/platform/modulesmanager/inc/ManagementModule.h
src/platform/modulesmanager/src/ManagementModule.cpp
src/platform/modulesmanager/tests/ModuleManagerTests/src/ModulesManagerTests.cpp

Add JSON schema for validating [MMI payloads](https://github.com/Azure/azure-osconfig/blob/main/docs/modules.md#323-serialized-mim-payload-at-run-time).

Add MMI payload schema

---

docs/architecture.md
docs/modules.md

Documentation clarification on the DC/RC MIM payload JSON format

Documentation clarification on the DC/RC MIM payload JSON format

---

docs/modules.md

One realistic example of a component MIM JSON to assist module developers

One realistic example of a component MIM JSON to assist module developers

---

src/platform/modulesmanager/tests/ModuleManagerTests/src/ModulesManagerTests.cpp

Removed some failing tests for further investigation

Removed failing tests temporarily

---

docs/modules.md
src/modules/mim/sample.json
src/modules/schema/mim.schema.json

+ a similar cosmetic update to the MIM schema

Consistent lowercase names of JSON array, map, object in documentation and samples

---

src/modules/commandrunner/src/so/CommandRunnerModule.cpp

CommandRunner.CommandArguments.Timeout and SingleLineTextResult are all optional

---

src/modules/settings/tests/CommonUtilsUT.cpp

Update the unit tests for commonutils!ExecuteCommand to fix failures on Arm

Update the unit tests for commonutils!ExecuteCommand to fix failure on Arm

---

src/CMakeLists.txt

Rev'ed OSConfig to 1.0.1.x

---

src/agents/pnp/PnpAgent.c
src/agents/pnp/PnpUtils.c
src/agents/pnp/inc/PnpAgent.h
src/agents/pnp/inc/PnpUtils.h

Use local proxy environment variable to connect to IoT Hub

Use local proxy environment variable to connect to IoT Hub

---

src/agents/pnp/PnpAgent.c
src/common/commonutils/CommonUtils.c
src/modules/settings/tests/CommonUtilsUT.cpp

Continued work for http proxy parsing

Continued work for http proxy parsing

---

src/common/commonutils/CommonUtils.c
src/modules/settings/tests/CommonUtilsUT.cpp

Adding http prefix to host name parsed from http proxy data

Adding http prefix to host name parsed from http proxy data

---

src/agents/pnp/PnpAgent.c
src/agents/pnp/PnpUtils.c
src/agents/pnp/inc/PnpUtils.h
src/common/commonutils/CommonUtils.c
src/modules/settings/tests/CommonUtilsUT.cpp

Queueing for later desired twin payload to not block during twin callback

---

README.md
src/agents/pnp/CMakeLists.txt
src/agents/pnp/PnpAgent.c
src/agents/pnp/PnpUtils.c
src/agents/pnp/daemon/osconfig.json
src/agents/pnp/inc/AgentCommon.h
src/agents/pnp/inc/PnpAgent.h
src/agents/pnp/inc/PnpUtils.h

Making MQTT and MQTT over Web Socket selection user configurable

---

devops/pipeline/binary_package.yaml
devops/pipeline/source_packaging.yaml
devops/pipeline/stages/binary_build.yaml
devops/pipeline/stages/source_build.yaml

* Refactored pipelines into stages (see /devops/pipelines/stages)
*  binary_build.yaml - Produces binaries + packages, performs tests and code coverage
*  source_build.yaml - Produces SOURCE packages (tar.gz) and RPM spec file and signatures.json
* Removed matrix-strategy builds in-favor of steps - provides the ability to re-run, better analytics/statistics
* Package build pipeline (binary_package.yaml) - refactored to use stages template
* Continuous integration pipeline (source_package.yaml) - refactored to use stages template
*  Added Ubuntu 18.04 ARM/ARM64 variants to CI validation
* Added MSFT copyright to pipelines and added descriptions to the pipelines
* ## Checklist

Refactored pipelines

---

devops/pipeline/binary_package.yaml
devops/pipeline/stages/binary_signing.yaml
devops/scripts/create_esrp_job.ps1

Adding code signing stage to package build pipeline (default: false) for published builds
Adding PowerShell script devops/scripts/create_esrp_job.ps1 that creates the ESRP signing job request JSON

Added ESRP signing to package build pipeline

---

docs/modules.md

Updating modules.md for MmiSet handling identical payloads

Updating modules.md for MmiSet handling identical payloads

---

devops/pipeline/binary_package.yaml

* Enabled code signing by default

Enabled code signing by default

---

devops/pipeline/binary_package.yaml
src/agents/pnp/PnpAgent.c
src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/modules/settings/tests/CommonUtilsUT.cpp

Adding IoT Hub telemetry with information about the device where OSConfig runs

Adding IoT Hub telemetry with information about the device where OSConfig runs

---

src/agents/pnp/PnpAgent.c
src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/modules/settings/tests/CommonUtilsUT.cpp

Publishing more functions for commonutils library and increasing unit-test coverage

---

devops/scripts/validate_msft_signing.sh
devops/scripts/validate_signing.sh

* Added script that validates a package was signed by the MSFT release key.

Added codesigning validation script

---

src/agents/pnp/PnpUtils.c
src/platform/modulesmanager/src/ModulesManager.cpp

Removing few traces that have no real use

---

src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/modules/settings/tests/CommonUtilsUT.cpp

Adding commonutils!UrlDecode to complete commonutils!UrlEncode

---

src/modules/mim/packagemanagerconfiguration.json

The purpose of this PR is to update the MIM file for the PackageManagerConfiguration module.

Update MIM file for PackageManagerConfiguration module

---

README.md
src/agents/pnp/PnpAgent.c
src/agents/pnp/daemon/osconfig.json
src/common/logging/Logging.c
src/common/logging/Logging.h

Adding logging!IsLocalManagementEnabled to improve logging for MpiSetDesired and MpiGetReported

---

README.md
src/agents/pnp/PnpAgent.c
src/common/logging/Logging.c
src/common/logging/Logging.h

Removing logging!IsLocalManagementEnabled (we decided to take another route) and completing README documentation for local management

---

src/common/commonutils/CommonUtils.cpp

Logging invalid MIM object payloads when full logging is enabled

---

src/agents/pnp/PnpAgent.c
src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/common/tests/CommonUtilsUT.cpp
src/modules/ztsi/src/lib/Ztsi.cpp
src/modules/ztsi/src/lib/Ztsi.h

Adding LockFile and UnlockFile to commonutils

---

README.md
src/agents/pnp/daemon/osconfig.service

Updating instructions how to use a proxy for connection to IoT Hub

---

src/CMakeLists.txt
src/cmake/templates/osconfig.spec.in

* Bumped OSConfig to v1.0.2.x
* Updated spec file

Bumped version to 1.0.2.x

---

src/modules/schema/mim.object.schema.json
src/modules/schema/mpi.schema.json
src/modules/schema/rcdc.schema.json

Create JSON schema for local RC/DC files

---

src/agents/pnp/PnpAgent.c
src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/common/tests/CommonUtilsUT.cpp

Replacing the non Linux standard, Posix, strdup with a new commonutils DuplicateString

---

src/agents/pnp/PnpAgent.c
src/agents/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.c
src/modules/commandrunner/src/lib/CommandRunner.cpp
src/modules/deviceinfo/src/lib/DeviceInfo.c
src/modules/firewall/src/so/FirewallModule.cpp
src/modules/networking/src/so/NetworkingModule.cpp
src/modules/pmc/src/lib/PmcBase.cpp
src/modules/settings/src/so/SettingsModule.cpp
src/modules/tpm/src/so/TpmModule.cpp
src/modules/ztsi/src/lib/Ztsi.cpp

Stabilizing DeviceInfo, adjusting traces and consolidating MmiGetInfo responses for modules

---

src/agents/pnp/daemon/osconfig.json

Updating the OSConfig model version to 6 to include DeviceInfo

---

src/modules/hostname/src/lib/HostNameBase.cpp

Fix HostName module reporting during `MpiGetReported()`.

Fix hostname reporting during MpiGetReported

---

src/tests/e2etest/CommandRunnerTests.cs
src/tests/e2etest/FirewallTests.cs
src/tests/e2etest/HostNameTests.cs
src/tests/e2etest/NetworkingTests.cs
src/tests/e2etest/SettingsTests.cs
src/tests/e2etest/TpmTests.cs
src/tests/e2etest/ZtsiTests.cs

Fixing camel casing for E2E tests

---

README.md

Fixing a typo and couple of formatting bugs in README.md

---

src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.cpp
src/common/commonutils/CommonUtils.h
src/common/tests/CommonUtilsUT.cpp
src/modules/firewall/src/lib/Firewall.cpp

Adding commonutils!PersistentHashString to be used by Firewall, PMC and others

---

src/modules/deviceinfo/src/lib/DeviceInfo.c

Increasing the payload buffer size for DeviceInfo!MmiGet to account for snprintf behavior

---

devops/pipeline/stages/source_build.yaml

* Missing SOURCES from package build pipeline artifact

Fixed missing SOURCES from package build pipeline

---

src/agents/pnp/PnpAgent.c

* Updating release to include #159

Update release branch 1.0.2

---

devops/pipeline/stages/source_build.yaml

* Including #155 into release/1.0.2

Fixed missing SOURCES from package build pipeline (#155)

---

src/tests/e2etest/TpmTests.cs

Fixing the E2E TPM test

---

devops/pipeline/stages/source_build.yaml

* Fixed source package missing 2-digits to be in sync with binary packages

Fixed source package version

---

devops/pipeline/binary_package.yaml
devops/pipeline/stages/binary_signing.yaml

* Fixed missing signed packages by adding an explicit dependency on all package stages

Fixed missing signed packages

---

devops/pipeline/source_packaging.yaml
devops/pipeline/stages/dotnet_validate.yaml
src/tests/e2etest/CommandRunnerTests.cs
src/tests/e2etest/E2ETest.cs
src/tests/e2etest/NetworkingTests.cs
src/tests/e2etest/ZtsiTests.cs

* Added dotnet build validation to CI  in order to prevent e2etest regressions

Added dotnet build validation

---

src/cmake/templates/osconfig.spec.in

* Update spec changelog version string

Updated spec version string

---

src/common/commonutils/CommonUtils.c
src/common/tests/CommonUtilsUT.cpp

Fix CommonUtils issues causing inconsistent unit test results.

Fix CommonUtils unit test errors

---

src/common/commonutils/CommonUtils.c
src/common/tests/CommonUtilsUT.cpp

Completing the previous fix for random CI CommonUtils unit test errors

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

- Update devcontainer to use `azure-osconfig` for workspace name and mounts
- Add VSCode extensions for git/GitHub tools
- Update default shell in container

Update devcontainer.json and Dockerfile

---

README.md
src/agents/pnp/ConfigUtils.c
src/agents/pnp/PnpAgent.c
src/agents/pnp/daemon/osconfig.json
src/agents/pnp/inc/ConfigUtils.h

Removing LocalPriority from configuration (running as it were always disabled)

---

src/agents/pnp/MpiProxy.c
src/agents/pnp/PnpAgent.c
src/agents/pnp/inc/MpiProxy.h
src/platform/inc/Mpi.h
src/platform/modulesmanager/src/ModulesManager.cpp
src/platform/modulesmanager/tests/MpiTests.cpp

Changing MpiSetDesired and MpiGetReported to use an MPI handle instead of a client name (part one)

---

src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/common/tests/CommonUtilsUT.cpp

Adding a new commonutils!ReadUriFromSocket to be used by Platform and others

---

src/agents/pnp/MpiProxy.c

Removing temporary workaround to enable MPI REST API in full internally

---

src/agents/pnp/MpiProxy.c

Work on the MPI REST API on Client side: removing double quotes for MPI handle strings and improving tracing

---

src/platform/orchestrator/src/MpiApi.cpp

Clean up MPI REST API and add log traces for errors

---

src/agents/pnp/MpiProxy.c
src/common/commonutils/CommonUtils.c

Reducing logging noise for MPI Client

---

src/agents/pnp/CMakeLists.txt
src/agents/pnp/MpiClient.c
src/agents/pnp/MpiProxy.c
src/agents/pnp/PnpAgent.c
src/agents/pnp/PnpUtils.c
src/agents/pnp/inc/MpiClient.h

Stabilizing the MPI REST API client

---

src/agents/pnp/MpiClient.c

MPI client fix for longer named requests such as MpiGetReported and MpiSetDesired

---

src/platform/orchestrator/src/MpiServer.cpp

Stabilize server and improve logging

---

src/common/CMakeLists.txt
src/common/parson/CMakeLists.txt
src/common/parson/parson.c
src/common/parson/parson.h

Add parson to common as static lib

---

README.md
docs/roadmap.md
src/agents/pnp/PnpAgent.c

Updating documentation for the separate Platform daemon process

---

src/agents/pnp/MpiClient.c
src/agents/pnp/PnpAgent.c
src/agents/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.cpp
src/platform/Main.c
src/platform/MpiServer.cpp

Limiting access to OSConfig MPI socket to root clients and other fixes

---

.github/workflows/deploy-e2etest-prod.yml
.github/workflows/deploy-github-main.yml
devops/e2e/prod.json

* Added some missing test metadata for the `e2e-prod` workflow

Fixed E2E tests

---

src/agents/pnp/PnpAgent.c
src/agents/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/common/tests/CommonUtilsUT.cpp
src/modules/deviceinfo/src/lib/DeviceInfo.c
src/modules/mim/deviceinfo.json

Adding totalMemory property to DeviceInfo and IotHub Telemetry

---

src/agents/pnp/daemon/osconfig.json

Incrementing the model to 9

---

src/agents/pnp/PnpAgent.c
src/common/commonutils/CommonUtils.c
src/common/commonutils/CommonUtils.h
src/common/tests/CommonUtilsUT.cpp
src/modules/deviceinfo/src/lib/DeviceInfo.c
src/modules/mim/deviceinfo.json

Backup commands for getting device vendor and model plus other minor improvements

---

src/platform/MpiServer.c

Fix status in MPI server worker

---

src/platform/ModulesManager.cpp
src/platform/MpiServer.c
src/platform/inc/MpiServer.h

Platform and MPI server bug fixes

---

devops/debian/postinst

* Added check for AIS before copying the identity over

Allow install without AIS

---

src/platform/Main.c
src/platform/ManagementModule.cpp
src/platform/ModulesManager.cpp
src/platform/MpiServer.c
src/platform/inc/ManagementModule.h
src/platform/inc/ModulesManager.h
src/platform/inc/MpiServer.h
src/platform/inc/PlatformCommon.h
src/platform/tests/ManagementModuleTests.cpp
src/platform/tests/MockManagementModule.cpp
src/platform/tests/MockManagementModule.h
src/platform/tests/MockModulesManager.cpp
src/platform/tests/MockModulesManager.h
src/platform/tests/ModulesManagerTests.cpp
src/platform/tests/MpiTests.cpp

Continued stabilization for MPI API server

---

src/platform/MpiServer.c

Fix MPI server worker 

---

devops/STATUS.md

* Add workflow status page to be used to track our workflows

Add Workflow status page

---

devops/debian/postinst
devops/debian/prerm
src/cmake/templates/osconfig.spec.in

* Start the platform deamon post-install. Added to debian `postinst` and rpm spec

Start platform daemon post-install

---

src/platform/MpiServer.c
src/platform/inc/MpiServer.h
src/platform/tests/CMakeLists.txt
src/platform/tests/MpiServerTests.cpp

Add unit tests for MPI server

---

src/agents/pnp/daemon/osconfig.json
src/modules/deviceinfo/src/lib/DeviceInfo.c
src/modules/deviceinfo/tests/DeviceInfoTests.cpp
src/modules/mim/deviceinfo.json

DeviceInfo v3 adding support for OSConfig version plus more

---

src/agents/pnp/PnpAgent.c
src/agents/pnp/PnpUtils.c
src/agents/pnp/inc/PnpAgent.h

Detecting when the Platform is running, restarting and refreshing MPI session when necessary

---

src/common/commonutils/CommonUtils.cpp
src/common/tests/CommonUtilsUT.cpp

Update product info template for validating client name

---

src/modules/commandrunner/src/lib/CommandRunner.cpp

Stabilize CommandRunner when writing to the cache

---

src/agents/pnp/PnpAgent.c
src/agents/pnp/PnpUtils.c

Retrying MpiSet and MpiSetDesired when the platform and MPI session need to be restarted

---

src/common/commonutils/DeviceInfoUtils.c

Using alternate command for product version

---

src/agents/pnp/PnpAgent.c
src/agents/pnp/PnpUtils.c
src/agents/pnp/inc/PnpAgent.h

Not reissuing failed MPI calls when the platform is active

---

src/modules/deviceinfo/tests/DeviceInfoTests.cpp
src/modules/test/Common.h
src/modules/test/MimParser.cpp
src/modules/test/MimParser.h
src/modules/test/RecipeInvoker.cpp
src/modules/test/RecipeInvoker.h
src/modules/test/TestRecipeParser.cpp
src/modules/test/TestRecipeParser.h
src/modules/test/main.cpp
src/modules/test/unit-tests/MimParserTests.cpp
src/modules/test/unit-tests/TestRecipeParserTests.cpp

COmpleting DeviceInfo unittest and consolidating incuded headers for the moldules functional test

---

src/agents/pnp/MpiClient.c
src/agents/pnp/PnpAgent.c

Log incoming configuration from DC file

---

src/common/commonutils/CommandUtils.c
src/common/commonutils/CommonUtils.cpp
src/common/commonutils/DeviceInfoUtils.c
src/common/tests/CommonUtilsUT.cpp

Replacing single use global macros in commonutils with local constants

---

.github/workflows/deploy-github-main.yml
.github/workflows/e2etest-run-tests.yml
devops/e2e/github-main.json
devops/terraform/host/GenericRunnerHost.tf

* Performs both CPU and Memory checks to make sure they are not above the `cpuThreshold` and `memThreshold`. Currently set to 50% of the target machine resources
* Adds `perf-logs` per distro to view both CPU & Memory statistics during e2e test runs
* Fails the e2e workflow if any of the thresholds defined are passed

Added performance tests

---

devops/docker/debian9-amd64/Dockerfile
devops/docker/debian9-arm/Dockerfile
devops/docker/debian9-arm64/Dockerfile
devops/docker/ubuntu18.04-amd64/Dockerfile
devops/docker/ubuntu18.04-arm/Dockerfile
devops/docker/ubuntu18.04-arm64/Dockerfile
devops/docker/ubuntu20.04-amd64/Dockerfile
devops/docker/ubuntu20.04-arm/Dockerfile
devops/docker/ubuntu20.04-arm64/Dockerfile

* Added `bc` to build containers in order to perform floating point arithmetic in workflows

Add basic calculator (bc) to containers

---

src/CMakeLists.txt
src/cmake/templates/osconfig.spec.in

* Bumping to v1.0.3.x
* Updated SPEC

Bumping to v1.0.3.x

---

.github/workflows/deploy-e2etest-prod.yml
.github/workflows/e2etest-run-tests.yml

* adds the platform logs as being optional for performance

Fixes e2e tests performance conditions

---

src/common/commonutils/DeviceInfoUtils.c

Fixing reversed DeviceInfo systemConfiguration and systemCapabilities

---

.github/workflows/deploy-e2etest-prod.yml
.github/workflows/deploy-insiders-fast.yml

* Added `provision-hub` job dependency for host VMs.

Fixed e2e prod/insiders-fast job ordering

---

src/modules/test/main.cpp

* Changed test fixture to be consistent with application name `ModulesTest`

Changed fixture name from TestRecipe to ModulesTest

---

README.md
src/agents/pnp/ConfigUtils.c
src/agents/pnp/PnpAgent.c
src/agents/pnp/daemon/osconfig.json
src/agents/pnp/inc/ConfigUtils.h

Renaming in OSConfig configuration and related instructions 'Protocol' to 'IotHubProtocol'

---

.github/workflows/deploy-github-main.yml

* Added additional trigger for e2e tests when performing any e2e test target changes

Added additional trigger to e2e tests

---

src/common/commonutils/CommandUtils.c
src/common/tests/CommonUtilsUT.cpp

Allowing CommandRunner to execute multiple commands and capture their output in same commandArguments write

---

src/common/tests/CommonUtilsUT.cpp

Consolidating and expanding coverage of the commonutils unit tests for commands with text results 

---

src/agents/pnp/MpiClient.c

Replacing missed strdup instance with commonutils!DuplicateString

---

src/agents/pnp/CMakeLists.txt
src/cmake/templates/osconfig.spec.in
src/common/commonutils/CommandUtils.c
src/common/commonutils/DaemonUtils.c
src/common/commonutils/DeviceInfoUtils.c
src/common/commonutils/SocketUtils.c

* Fixes building the package when using `azure-iot-sdk-c` as package by adding the missing `PLATFORM_INC_DIR` CMake variable.
* Cleanup some unused variables

Added missing include dirs + fixes

---

src/common/tests/CommonUtilsUT.cpp

Refactoring the CommonUtilsTest.ExecuteMultipleCommandsAsOneCommandWithTextResult test case a bit to help investigate a curious CI failure

---

src/modules/test/ManagementModule.cpp
src/modules/test/recipes/DeviceInfoTests.json

Adding complete test recipe for DeviceInfo

---

src/common/tests/CommonUtilsUT.cpp

New change to investigate CI unit test case failure

---

src/modules/test/CMakeLists.txt

Added symlink to build root for modulestest

---

src/modules/test/README.md

Added modulestest known limitations

---

docs/modules.md

Simplifying the Module Test Recipe sample to match existing recipes

---

src/modules/mim/tpm.json
src/modules/test/recipes/NetworkingTests.json
src/modules/test/recipes/TpmTests.json

Extended module test recipe for Tpm. Added cases to validate the result code for each reported object in the Tpm MIM, and cases for MMI argument validation.

Tpm module test recipe

---

.github/workflows/deploy-github-main.yml

* Temporarily disabling E2E test environment cleanup to collect additional IotHub telemetry

Temporarily disabled e2e environment cleanup

---

src/modules/mim/firewall.json

Draft of the Firewall v3 MIM for creating, deleting, and listing firewall rules using the following schema to represent a rule:
```
{ 
"action": 0,                        // none = 0, addRule = 1, deleteRule = 2                  
"ruleAction": 0,                    // none= 0, allowTraffic = 1, denyTraffic= 2
"inbound": true,                    // outbound = false
"protocol": 0,                      // all = 0, tcp = 1, udp = 2, icmp = 3
"sourceAddress": "<ip_address>",    // ex: "20.43.132.131/24"
"sourcePort": <port_number>,        // ex: 1234
"destinationAddress": "<ip_address>",
"destinationPort": <port_number>
}
```

Firewall v3 MIM

---

.github/workflows/deploy-github-main.yml

re-enabling e2e environment teardown

---

src/modules/test/recipes/FirewallTests.json

Firewall test recipe improvements

---

.github/workflows/deploy-reliability-modules.yml

* Removed verbosity from modulestest test reports
* Corrected `checkResult` to fail workflow on failure

Removed modulestest verbosity from reliability tests

---

.github/workflows/build-containers.yml

Update build-containers workflow triggers to include future/**

---

docs/modules.md
src/common/commonutils/CommonUtils.cpp
src/modules/schema/mim.object.schema.json
src/modules/schema/mim.schema.json

Adding support for enumeration of strings to MIM documentation and schemas

---

src/modules/samples/rust/src/common.rs

Unified formatting in common.rs

Uniformed formatting

---

src/modules/mim/firewall.json

Update Firewall v3 MIM

---

src/modules/firewall/src/lib/Firewall.cpp
src/modules/firewall/src/lib/Firewall.h
src/modules/firewall/src/so/FirewallModule.cpp
src/modules/firewall/tests/FirewallTests.cpp

Update/refactor firewall module in preparation for upcoming work. These changes maintain the current functionality of the firewall module (and tests).

Refactoring parts of Firewall module

---

.devcontainer/Dockerfile
devops/docker/debian9-amd64/Dockerfile
devops/docker/debian9-arm/Dockerfile
devops/docker/debian9-arm64/Dockerfile
devops/docker/ubuntu18.04-amd64/Dockerfile
devops/docker/ubuntu18.04-arm/Dockerfile
devops/docker/ubuntu18.04-arm64/Dockerfile
devops/docker/ubuntu20.04-amd64/Dockerfile
devops/docker/ubuntu20.04-arm/Dockerfile
devops/docker/ubuntu20.04-arm64/Dockerfile

* Adding `jsonschema` tooling needed for validating JSON schemas, another PR will be making use of the tooling

Add jsonschema tooling to build environments

---

src/modules/samples/rust/src/sample.rs

Added String enums to the sample rust module

Added String enums to the sample rust module

---

src/modules/mim/daemonconfiguration.json
src/modules/samples/rust/src/lib.rs

Added the MIM for the Daemon Configuration Module

Daemon Config Module MIM

---

src/modules/samples/rust/src/sample.rs

Renamed a variable and removed print debug line

Sample rust module cleanup

---

src/modules/CMakeLists.txt

Fixed build break when jq isn't present

---

src/modules/test/README.md

* Updated `modulestest` readme

Updated modulestest readme

---

src/modules/mim/firewall.json

Remove "reject" from default policy action

---

src/modules/samples/rust/Cargo.toml

Added settings in cargo.toml to optimize size

Sample rust module optimize package size

---

.github/workflows/deploy-e2etest-prod.yml
.github/workflows/deploy-github-main.yml
.github/workflows/deploy-modulestest.yml
.github/workflows/deploy-reliability-modules.yml
.github/workflows/deploy-reliability-platform.yml
.github/workflows/e2etest-provision-ais.yml
.github/workflows/e2etest-provision-hosts.yml
.github/workflows/e2etest-provision-hub.yml
.github/workflows/e2etest-run-modulestest.yml
devops/e2e/build-debian-stretch-cloud-init.tpl
devops/e2e/build-ubuntu-bionic-cloud-init.tpl
devops/e2e/build-ubuntu-focal-arm64-cloud-init.tpl
devops/e2e/build-ubuntu-focal-cloud-init.tpl
devops/e2e/modulestest.json

* Added modulestest to be run on a separate workflow
* Refactored AIS device identity creation out of the provision-host
* Added new `modulestest.json` test target environment definition and cloud-init scripts for our current supported distros

Run modulestest in separate workflow

---

.github/workflows/deploy-reliability-platform.yml
.github/workflows/e2etest-run-tests.yml

* Fixed error messages in workflow to be displayed properly
* Disabled memory profiling on reliability tests

Fixed error msg in workflow

---

src/modules/samples/rust/src/common.rs
src/modules/samples/rust/src/sample.rs

Added a new payload size exceeded error type and message.

Sample rust module payload size exceeded

---

.github/workflows/e2etest-run-modulestest.yml

Fixed git reference on pull requests

---

.github/workflows/ci.yml

Removed modulestest from container CI

---

src/modules/firewall/src/lib/Firewall.cpp
src/modules/firewall/tests/FirewallTests.cpp
src/modules/mim/firewall.json

Firewall v3: change "notPresent" to "absent"

---

dtmi/osconfig/README.md
src/agents/pnp/daemon/osconfig.json

Incrementing OSConfig model version to 11

---

dtmi/osconfig/firewall-4.json
src/agents/pnp/daemon/osconfig.json
src/modules/firewall/src/lib/Firewall.cpp
src/modules/firewall/src/lib/Firewall.h
src/modules/firewall/tests/FirewallTests.cpp
src/modules/mim/firewall.json
src/modules/test/recipes/FirewallTests.json
src/tests/e2etest/FirewallTests.cs

*E2E test changes have been validated locally*

Standardize Firewall object naming pattern

---

dtmi/osconfig/firewall-4.json

Re-adding name changes lost in previous merge for Firewall DTDL

---

src/modules/test/Common.h
src/modules/test/RecipeInvoker.h
src/modules/test/RecipeModuleSessionLoader.cpp

Changed modulestest clientName to use default clientName

---

src/modules/test/RecipeInvoker.cpp
src/modules/test/main.cpp

* Instead of removing the cache in between test executions, remove cache before starting the test execution.

Fixed command runner cache removal race-condition

---

src/modules/test/Common.h
src/modules/test/RecipeModuleSessionLoader.cpp

* Added full client name `Azure OSConfig [Model#];[VersionString]` for use in modulestest

Added model number to client name

---

src/common/mpiclient/MpiClient.c

Making the MPI Client attempt to read the response when the request fails

---

src/CMakeLists.txt

Bumping version to `v1.0.4` in preparation for next release.

Bump version to v1.0.4.x

---

src/modules/firewall/src/lib/Firewall.cpp

Fix firewall module behavior for adding rules

---

src/modules/firewall/src/lib/Firewall.cpp

Pull fixes from release/1.0.4

---

README.md
docs/modules.md

Fixing incorrect casing and other documentation issues

---

dtmi/osconfig/deviceosconfiguration-12.json
dtmi/osconfig/pmc-1.json
src/agents/pnp/daemon/osconfig.json

Adding the Pmc interface and bumping OSConfig model version to 12

---

src/tests/e2etest/E2ETest.cs
src/tests/e2etest/FirewallTests.cs

Add firewall v3 E2E tests

---

src/modules/samples/cpp/src/lib/Sample.cpp
src/modules/samples/cpp/src/lib/Sample.h
src/modules/test/recipes/SampleTests.json

Add test recipe for sample module

---

src/modules/test/recipes/SampleTests.json

Disable Sample recipe reportedIntegerObject until failures are fixed

---

devops/pipeline/binary_package.yaml
devops/pipeline/stages/source_build.yaml

This pipeline stage was mistakenly removed in #260. This PR adds the missing stage back as it was before.

Re-add missing sources build stage for Azure Pipelines package build

---

src/cmake/templates/osconfig.spec.in

Release v1.0.4 update spec file template

---

README.md
src/agents/pnp/CMakeLists.txt
src/cmake/templates/osconfig.spec.in

Completing removal of ADHS telemetry

---

dtmi/osconfig/configuration-2.json
dtmi/osconfig/deviceosconfiguration-15.json
src/agents/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.h
src/modules/configuration/src/lib/Configuration.c
src/modules/configuration/tests/ConfigurationTests.cpp
src/modules/mim/configuration.json
src/modules/test/Common.h
src/modules/test/recipes/ConfigurationTests.json
src/tests/e2etest/AdhsTests.cs

Flattening desired for Configuration model and changing Hub protocol to enum of strings

---

src/common/commonutils/DeviceInfoUtils.c

Fixing potential memory leak

---

.github/actions/footprint-check/action.yml

* Fixes packaging workflow for missing changes in #421

Fixed step output for arch in footprint validation

---

dtmi/osconfig/deviceosconfiguration-16.json
src/agents/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.h

Publishing ZTSI v3 and incrementing model version to 16

---

devops/e2e/build-debian-stretch-cloud-init.tpl
devops/e2e/build-ubuntu-bionic-cloud-init.tpl
devops/e2e/build-ubuntu-focal-arm64-cloud-init.tpl
devops/e2e/build-ubuntu-focal-cloud-init.tpl
devops/e2e/debian-stretch-cloud-init-insiders-fast.tpl
devops/e2e/debian-stretch-cloud-init.tpl
devops/e2e/ubuntu-bionic-cloud-init-insiders-fast.tpl
devops/e2e/ubuntu-bionic-cloud-init.tpl
devops/e2e/ubuntu-focal-arm64-cloud-init-insiders-fast.tpl
devops/e2e/ubuntu-focal-arm64-cloud-init.tpl
devops/e2e/ubuntu-focal-cloud-init-insiders-fast.tpl
devops/e2e/ubuntu-focal-cloud-init.tpl

* Removed package upgrade from e2e targets to improve apt stability

Removed package upgrades from e2e targets

---

src/agents/gc/CMakeLists.txt
src/agents/gc/Common.h
src/agents/gc/OSConfig_Proto_Policy.metaconfig.json
src/agents/gc/OSConfig_Proto_Policy.mof
src/agents/gc/OSConfig_PrototypeResource.c

Various stabilization fixes and improvements for the OSConfig GC NRP PoC

---

src/modules/firewall/src/lib/Firewall.cpp

Update firewall version info returned by GetInfo

---

src/agents/pnp/daemon/osconfig.json

Update ZTSI reported objects in agent configuration file

---

src/agents/gc/README.md

Adding a README.md for the NRP prototype

---

src/agents/gc/OSConfig_Proto_Policy.metaconfig.json
src/agents/gc/OSConfig_Proto_Policy.mof
src/agents/gc/OSConfig_PrototypeResource.c
src/agents/gc/README.md

Fixing remediation (Set) path for the PoC NRP

---

src/agents/gc/OSConfig_PrototypeResource.c
src/agents/gc/README.md

Setting max payload value to avoid bug in HostName module and documenting local Get verification

---

src/agents/gc/OSConfig_Proto_Policy.mof
src/agents/gc/OSConfig_PrototypeResource.c
src/agents/gc/README.md

Updating the PoC GC NRP with several fixes including stabilization for Test method

---

src/agents/gc/README.md

Adding instructions for the MC prototype to be tested end to end over Azure Policy

---

src/agents/gc/README.md

Updating the README.md for the GC PoC

---

src/modules/test/Module.c
src/modules/test/README.md
src/modules/test/main.c
src/modules/test/recipes/CommandRunnerTests.json

Fix moduletest payload parsing and JSON names

---

.github/workflows/e2etest-run-modulestest.yml

Fix path for listing test recipes in workflow

---

.github/workflows/build-containers.yml

Update build-containers.yml workflow triggers

---

src/CMakeLists.txt
src/cmake/templates/osconfig.spec.in

Bump version number and update spec file template in preparation for release of `v1.0.5`

Bump version to v1.0.5

---

.github/workflows/ci.yml
.github/workflows/test-report.yml

Update CI test report to run in the context of the repository's main branch with the read/write token permissions necessary for publishing a check-run containing the markdown report.

Update CI test report workflow

---

.github/workflows/ci.yml

Remove unused coverage job

---

dtmi/osconfig/securitybaseline-1.json
src/adapters/pnp/daemon/osconfig.json
src/modules/mim/securitybaseline.json
src/modules/securitybaseline/src/lib/SecurityBaseline.c
src/modules/securitybaseline/tests/SecurityBaselineTests.cpp
src/modules/test/recipes/SecurityBaselineTests.json

Adding 1 more Security Baseline check related to previous 19 (file permissions)

---

dtmi/osconfig/securitybaseline-1.json
src/adapters/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.h
src/common/commonutils/DeviceInfoUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/mim/securitybaseline.json
src/modules/securitybaseline/src/lib/SecurityBaseline.c
src/modules/securitybaseline/tests/SecurityBaselineTests.cpp
src/modules/test/recipes/SecurityBaselineTests.json

Adding a new (21st) Security Baseline check for: Kernel support for the XD/NX processor feature should be enabled

---

dtmi/osconfig/securitybaseline-1.json
src/adapters/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/commonutils/Internal.h
src/modules/mim/securitybaseline.json
src/modules/securitybaseline/src/lib/SecurityBaseline.c
src/modules/securitybaseline/tests/SecurityBaselineTests.cpp
src/modules/test/recipes/SecurityBaselineTests.json

Adding 11 more Security Baseline auditing checks related to filesystem mounting options

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp

Adding functional (simulating /etc/fstab) unit-tests for commonutils!CheckFileSystemMountingOption and stabilizing

---

dtmi/osconfig/securitybaseline-1.json
src/adapters/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/mim/securitybaseline.json
src/modules/securitybaseline/src/lib/SecurityBaseline.c
src/modules/securitybaseline/tests/SecurityBaselineTests.cpp
src/modules/test/recipes/SecurityBaselineTests.json

Adding 22 more Security Baseline checks via 15 new MIM objects for a total of 54 checks so far

---

dtmi/osconfig/securitybaseline-1.json
src/adapters/mc/README.md
src/adapters/pnp/daemon/osconfig.json
src/common/commonutils/CommonUtils.h
src/common/commonutils/DeviceInfoUtils.c
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/mim/securitybaseline.json
src/modules/securitybaseline/src/lib/SecurityBaseline.c
src/modules/securitybaseline/tests/SecurityBaselineTests.cpp
src/modules/test/recipes/SecurityBaselineTests.json

Adding 1 more Security Baseline check (55 total so far), expanding remediation for 15 checks, and other fixes following validation via Azure Policy

---

src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h

Adding to SecurityBaseline ability to read password encryption, expiration times and more

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c

Combining recently added functions for checking and setting file and directory access and ownership

---

devops/e2e/github-main.json
devops/e2e/insiders-fast.json
devops/e2e/modulestest.json
devops/e2e/prod.json
src/tests/e2etest/datasource/LocalDataSource.cs

* Updated arm64 tags for e2e workflows
* Fixed logging in e2e tests for LocalDataSource (RC file)

Updated arm64 image tags + logging

---

.github/workflows/ci.yml
src/modules/pmc/tests/PmcTests.cpp
src/platform/tests/ModulesManagerTests.cpp

Temporarily skip failing tests while bug is under investigation so that current work does not loose ARM coverage (skipped tests are only failing on ARM builds).

Update CI matrix

---

.github/workflows/ci.yml

Fix status check functions in CI

---

dtmi/osconfig/deviceosconfiguration-12.json
dtmi/osconfig/deviceosconfiguration-13.json
dtmi/osconfig/deviceosconfiguration-14.json
dtmi/osconfig/deviceosconfiguration-15.json
dtmi/osconfig/deviceosconfiguration-16.json
dtmi/osconfig/deviceosconfiguration-17.json
dtmi/osconfig/deviceosconfiguration-18.json
dtmi/osconfig/packagemanager-1.json
src/adapters/pnp/daemon/osconfig.json
src/cmake/templates/osconfig.spec.in
src/modules/mim/pmc.json
src/modules/pmc/README.md
src/modules/pmc/src/lib/PmcBase.cpp
src/modules/pmc/src/so/PmcModule.cpp
src/modules/pmc/tests/PmcTests.cpp
src/modules/test/recipes/PmcTests.json
src/tests/e2etest/PmcTests.cs

Renaming the 'PMC' component name to 'PackageManager'

---

src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 10 more audit Security Baseline checks for a total of 100 done so far

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 1 more audit Security Baseline check for a total of 101

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 3 more Security Baseline audit checks (total 104) plus some clean-up for previous ones

---

src/modules/test/main.c

Enumerate failures after running module tests

---

src/common/commonutils/FileUtils.c
src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 4 more Security Baseline audit checks for a total so far of 108

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 5 more Security Baseline audit checks for a total so far of 113

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 10 more Security Baseline audit checks for a total so far of 123

---

src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp

Stabilizing the search for file lines that exist not being commented out

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 14 more Security Baseline audit checks for a total of 152

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 17 more Security Baseline audit checks for a total so far of 169

---

.github/workflows/ci.yml

Update OS names in CI test matrix

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding 4 more Security Baseline audit checks for a total of 174

---

.github/workflows/codeql.yml

Adds CodeQL static code analysis checks to all PRs and scheduled checks against the default `main` branch.

Add CodeQL analysis

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/DaemonUtils.c
src/common/commonutils/FileUtils.c
src/common/commonutils/ProxyUtils.c

Experimenting with a small cleanup PR

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

One fix and one addition for check completion for Security Baseline

---

src/common/commonutils/FileUtils.c
src/common/commonutils/Internal.h
src/common/tests/CommonUtilsUT.cpp

Hardening file and directory access audit and remediation for Security Baseline

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Fixing AuditEnsureDotDoesNotAppearInRootsPath check for Security Baseline

---

src/common/commonutils/FileUtils.c
src/modules/securitybaseline/README.md
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Adding a README.md for SecurityBaseline plus couple of small stabilization fixes

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stabilizing security baseline check for auditEnsureAllWirelessInterfacesAreDisabled

---

src/common/commonutils/FileUtils.c
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Improving auditEnsureDotDoesNotAppearInRootsPath and other environment variable checks for Security Baseline

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Expanding coverage for auditEnsureDotDoesNotAppearInRootsPath and auditEnsureCoreDumpsAreRestricted

---

src/adapters/pnp/Watcher.c
src/common/commonutils/CommonUtils.cpp
src/common/commonutils/FileUtils.c
src/common/commonutils/OtherUtils.c
src/common/commonutils/UserUtils.c

Fixing SecurityBaseline checks for malformed shadow, passwd and group system files under etc

---

src/common/commonutils/FileUtils.c
src/common/commonutils/UserUtils.c
src/modules/securitybaseline/src/lib/SecurityBaseline.c

This PR includes stabilization fixes for the following audit checks: 
auditEnsureMountingOfUsbStorageDevicesIsDisabled, 
auditEnsureDisabledInstallationOfCramfsFileSystem, 
auditEnsureDisabledInstallationOfFreevxfsFileSystem, 
auditEnsureDisabledInstallationOfHfsFileSystem, 
auditEnsureDisabledInstallationOfHfsplusFileSystem, 
auditEnsureDisabledInstallationOfJffs2FileSystem SecurityBaseline, 
auditEnsurePasswordExpiration,
auditEnsureMaxDaysBetweenPasswordChanges

Continuation of the Security Baseline audit checks stabilization

---

src/common/commonutils/UserUtils.c

Security Baseline stabilization for password expiration audit (CheckPasswordExpirationLessThan)

---

src/adapters/mc/LinuxOsConfigResource.c
src/adapters/pnp/PnpAgent.c
src/common/commonutils/CommonUtils.h
src/common/commonutils/DaemonUtils.c
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stabilizing the AuditEnsureUsersCannotSetSshEnvironmentOptions audit check for SecurityBaseline

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stablilization for auditEnsureOnlyApprovedMacAlgorithmsAreUsed and auditEnsureSshIdleTimeoutIntervalIsConfigured SecurityBaseline audit checks

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/commonutils/OtherUtils.c
src/common/commonutils/UserUtils.c
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stabilization for the auditEnsureSyslogRotaterServiceIsEnabled SecurityBaseline audit check

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stabilizing the auditEnsureRsynServiceIsDisabled and auditEnsureRshClientNotInstalled Security Baseline audit checks

---

src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stabilization for the auditEnsureUsersDotFilesArentGroupOrWorldWritable Security Baseline audit check

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stabilizing auditEnsureRpcgssdServiceIsDisabled and auditEnsureRpcidmapdServiceIsDisabled Security Baseline audit checks

---

src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Stabilization for auditEnsureRestrictedUserHomeDirectories and auditEnsureUsersDotFilesArentGroupOrWorldWritable Security Baseline audit checks

---

src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Refactoring auditEnsureUnnecessaryAccountsAreRemoved and adding remediateEnsureUnnecessaryAccountsAreRemoved Security Baseline checks

---

src/common/commonutils/DeviceInfoUtils.c

Stabilizing auditEnsureKernelCompiledFromApprovedSources SecurityBaseline audit check for Debian 10/11

---

src/modules/securitybaseline/README.md

Updating README.md for the SecurityBaseline module

---

src/adapters/mc/Common.h
src/adapters/mc/OsConfig.schema.mof
src/adapters/mc/OsConfigResource.c
src/adapters/mc/OsConfigResource.h
src/adapters/mc/ReasonClass.h
src/adapters/mc/codegen.cmd
src/adapters/mc/schema.c
src/common/logging/Logging.h
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Enabling the OSConfig Universal NRP to report audit reasons for the Linux Azure Security Baseline checks to be done later

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Hardening the auditEnsureBluetoothHiddNotInstalled and remediateEnsureBluetoothHiddNotInstalled Security Baseline checks

---

src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Improving the partition mounting check audits and auditEnsurePasswordReuseIsLimited for Security Baseline

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/DeviceInfoUtils.c
src/common/commonutils/FileUtils.c
src/common/commonutils/UserUtils.c
src/modules/securitybaseline/src/lib/SecurityBaseline.c

Continuing improvement for ways to collect reasons for failed audit Security Baseline checks and other coverage

---

.github/workflows/codeql.yml

Add C# to CodeQL workflow for scanning E2E tests.

Add C# to CodeQL workflow

---

src/adapters/mc/OsConfigResource.c
src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/commonutils/SshUtils.c

Continued stabilization for the SSH policy ran by the Universal NRP and the Security Baseline module, including bug fixes and improvements.

Continued stabilization for the SSH policy ran by the Universal NRP and the Security Baseline module

---

src/common/commonutils/FileUtils.c
src/common/commonutils/SshUtils.c

Continued stabilization for the SSH policy executed by the Universal NRP and the Security Baseline module, including bug fixes and improvements for the case when the SSH server is not installed on the device.

Continued stabilization for the SSH policy executed by the Universal NRP and the Security Baseline module

---

src/common/commonutils/SshUtils.c

Small polishing changes for consistency, etc. for fit and finish issues observed during deep validation.

Continuing stabilization for the SSH policy executed by the Universal NRP and the Security Baseline module 

---

src/common/commonutils/SshUtils.c

Consolidating access for the SSH server banner file for audit and automatic remediation

---

src/common/commonutils/UserUtils.c

Improving use of the getgrouplist function to avoid Security Baseline audit failures on systems with abnormal number of groups per user

---

src/adapters/mc/OsConfigResource.c
src/common/commonutils/SshUtils.c

Stabilizing the SSH Policy implementation

---

src/adapters/mc/OsConfigResource.c
src/adapters/mc/README.md

Adding a bug fix and a documentation update for the Universal NRP

---

src/adapters/mc/OsConfigResource.c
src/common/commonutils/SshUtils.c

Fixing collision between SSH fallback and OSConfig initialization routes

---

src/adapters/mc/OsConfigPolicy_DeployIfNotExists.json
src/adapters/mc/README.md

- [x ] I submitted this PR against the `main` branch.

Adding the current SSH policy definition with the SAS token and file hash removed and updating the Universal NRP documentation to reference it

---

devops/docker/ubuntu-22.04-amd64/Dockerfile

* Updated image to use the right version

Fixed ubuntu 22.04 amd64 image

---

src/adapters/pnp/PnpUtils.c

Protecting against potential integer overflow for payload size received from IoT Hub

---

src/adapters/mc/CMakeLists.txt
src/adapters/mc/OsConfigPolicy.mof

Updating the artifacts package name and the ConfigurationName in the policy MOF for the SSH server policy

---

src/modules/securitybaseline/src/lib/SecurityBaseline.c

Fixing SecurityBaseline overwrite of EnsurePermissionsOnEtcSshSshdConfig with EnsureSshHostbasedAuthenticationIsDisabled

---

devops/docker/mariner-2-amd64/Dockerfile

* Added new Mariner amd64 build container

Adding Azure Linux (Mariner 2) AMD64 container

---

src/common/commonutils/SshUtils.c

Stabilizing checking SSH protocol depending on server's OpenSSH version 

---

src/adapters/mc/OsConfigResource.c

This PR fixes a subtle bug showing only in the SSH fallback mode caused by a leftover local variable no longer properly initialized and messing up the audit results.

Fixing SSH fallback initialization

---

src/common/commonutils/SshUtils.c

Improving parsing for OpenSSH server responses and not overwriting UsePAM

---

src/adapters/mc/sshpreview/OsConfigPolicy_DeployIfNotExists.json

Publishing the SSH policy definition for the 2402 preview

---

src/adapters/mc/sshpreview/OsConfigPolicy_DeployIfNotExists.json

Updating the display name for the preview SSH policy definition

---

src/adapters/mc/sshpreview/refresh_for_preview.sh

Adding a bash script to reinstall openssh & update osconfig. This script will be useful in validation across various distros.

Adding a bash script to reinstall the openssh server and update osconfig

---

src/adapters/mc/OsConfigPolicy.mof
src/adapters/mc/OsConfigPolicy_DeployIfNotExists.json

Updating the SSH policy definition and MOF to expand customizable parameters for all 20 checks 

---

src/adapters/mc/OsConfigPolicy_DeployIfNotExists.json

Updating the SSH policy definition

---

src/common/commonutils/SshUtils.c

Stabilizing the SSH policy: empty string values in sshd_config can block sshd from starting

---

devops/docker/almalinux-9-amd64/Dockerfile
devops/docker/amazonlinux-2-amd64/Dockerfile
devops/docker/centos-7-amd64/Dockerfile
devops/docker/centos-8-amd64/Dockerfile
devops/docker/oraclelinux-7-amd64/Dockerfile
devops/docker/oraclelinux-8-amd64/Dockerfile
devops/docker/rhel-7-amd64/Dockerfile
devops/docker/rhel-8-amd64/Dockerfile
devops/docker/rhel-9-amd64/Dockerfile
devops/docker/rockylinux-9-amd64/Dockerfile
devops/docker/sles-15-amd64/Dockerfile
devops/rpm/changelog

* Adding new distro build containers (amd64) (retagged images requested for those missing)
* Alma Linux 9
* Amazon Linux 2
* CentOS 7, 8
* Oracle Linux 7, 8
* RHEL 7, 8 ,9
* Rocky Linux 9
* SLES 15

Adding new distro support containers

---

devops/docker/rhel-9-amd64/Dockerfile

* Added missing libs to RHEL 9 container

Adding libcurl for RHEL 9

---

.github/workflows/ci.yml
.github/workflows/insiders-fast.yml

* Remove AlmaLinux from build/test/publish workflows

Removing for now (to re-add if needed later) AlmaLinux from build/test/publishing

---

README.md
devops/README.md

* Added instructions on using pre-built binary packages including enlistment instructions for both `insiders-fast` and `prod` channels.

Updating documentation for newly added binary packages

---

.github/workflows/insiders-fast.yml
.github/workflows/module-test.yml

* Added Rocky Linux 9 to `insiders-fast` publishing and test recipe workflows (module test)

Adding Rocky Linux 9

---

src/adapters/mc/OsConfigResource.c

Making cleanup failures for the Universal NRP recoverable

---

devops/README.md

* Updated Installation docs for Debian 11, 12 insiders-fast onboarding instructions

Updating Debian 11, 12 distro instructions

---

.devcontainer/devcontainer.json
.github/workflows/build-containers.yml

* Added ability to rebuild specific containers via workflow `distro_list`
* Added `rebuild_all` option to rebuild all distro dev containers
* Added additional helper tooling to devcontainer

Adding container rebuild options

---

src/adapters/mc/OsConfigPolicy_DeployIfNotExists.json
src/adapters/mc/sshpreview/OsConfigPolicy_DeployIfNotExists.json

Fit and finish for the backup SSH Control Posture policy definition copies.

Changing parameter names to camelCase from PascalCase and removing the Disabled value for the effect parameter

---

devops/README.md

* Added `AlmaLinux-9` installation instructions

Added AlmaLinux to docs

---

.github/workflows/universalnrp-test-report.yml

* Fixed Universal NRP Test Report, trigger was not on root workflow so it was never triggered

Fixed Universal NRP Test Report

---

.github/workflows/universalnrp-test-run.yml

* Corrected the test report path for the Universal NRP Tests

Fixed Universal NRP test report path

---

.github/workflows/ci.yml
.github/workflows/insiders-fast.yml
.github/workflows/package-build.yml

* Adding tag container support so we can be explicit about the container to run in

Added tag container support

---

.github/workflows/insiders-fast.yml
.github/workflows/package-build.yml
.github/workflows/publish.yml

* Fixed `insiders-fast` publishing

Fixed insiders-fast publishing

---

.github/workflows/universalnrp-test-run.yml
devops/README.md

* Included all distro logs for UniversalNRP test workflow
* Updated enlistment instructions for `insiders-fast` repository

Added all distro logs to Universal NRP workflow and updated AzureLinux insiders-fast enlistment instructions

---

.github/workflows/universalnrp-test-run.yml
.github/workflows/universalnrp-test.yml

* Updated `Universal NRP Test` to only include the SSH security baseline.

Updated Universal NRP test

---

.vscode/settings.json
README.md
devops/README.md
devops/e2e/cloudtest/centos-8.json

* Updated centos-8 to also include omi
* Updated vscode settings to default to jsonc (JSON with comments)
* Updated README to include test badges for CI + Integration Test workflow status

Updated centos-8 image + added README status badges for test status

---

src/common/asb/Asb.c
src/common/commonutils/CommonUtils.h
src/common/commonutils/DeviceInfoUtils.c
src/common/commonutils/FileUtils.c
src/common/commonutils/MountUtils.c
src/common/commonutils/SshUtils.c
src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h
src/common/tests/CommonUtilsUT.cpp

Several advancements for Security Baseline remediation check implementations (in various areas, including users and groups, passwords, etc.), improvements and fixes to audit checks (mounting options, etc.), including advancing completion for remediation utilities.  Not listing here all affected checks or what new utilities were added, they are evident from the code changes.

Continuing work for Security Baseline remediation implementation and audit improvements

---

src/adapters/mc/asb/OsConfigPolicy.mof
src/common/commonutils/FileUtils.c
src/common/commonutils/UserUtils.c
src/common/tests/CommonUtilsUT.cpp

Adding few stabilization fixes for Azure Security Baseline v2 audit implementation

---

src/common/asb/Asb.c
src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c

Completing implementation for the following Security Baseline remediation checks:
RemediateEnsurePostfixNetworkListeningIsDisabled
RemediateEnsureRpcsvcgssdServiceIsDisabled
RemediateEnsureSmbWithSambaIsDisabled
RemediateEnsureRloginServiceIsDisabled

Completing remediation for 4 more Security Baseline checks

---

src/common/asb/Asb.c
src/common/commonutils/FileUtils.c
src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h

Improved for the Security Baseline the following audit checks: 
AuditEnsureAutomountingDisabled
AuditEnsureLockoutForFailedPasswordAttempts
AuditEnsureSyslogPackageIsInstalled.
Completed implementation for the following remediation checks:
RemediateEnsureSuRestrictedToRootGroup
RemediateEnsureDefaultUmaskForAllUsers
RemediateEnsureAutomountingDisabled

Completing implementation for 3 more Security Baseline remediation checks

---

.github/workflows/universalnrp-test-run.yml
.github/workflows/universalnrp-test.yml
src/tests/universal-nrp-e2e/UniversalNRP.Tests.ps1

* Added `LinuxSecurityBaselinePolicy.zip` to the NRP tests
* Added `pull_request` trigger

Updating for CI the ASB v2 NRP MC PS tests

---

src/common/CMakeLists.txt
src/common/asb/Asb.c
src/common/commonutils/CommonUtils.h
src/common/commonutils/OtherUtils.c
src/common/tests/CommonUtilsUT.cpp

Improving wireless interfaces presence detection and suppression, plus completing implementation for the following remediation checks:
RemediateEnsureDotDoesNotAppearInRootsPath
RemediateEnsureRemoteLoginWarningBannerIsConfigured
RemediateEnsureLocalLoginWarningBannerIsConfigured

Continuing implementation for ABS v2 remediation and audit stabilization

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/DaemonUtils.c
src/common/commonutils/FileUtils.c
src/common/commonutils/MountUtils.c
src/common/commonutils/UserUtils.c
src/common/tests/CommonUtilsUT.cpp

Continuing stabilization for ASB v2 implementation. Fixing log traces, skipping unnecessary writes to mounting tables, skipping unnecessary copy with access ops for temp files.

Continuing stabilization for ASB v2 implementation

---

src/common/asb/Asb.c
src/common/commonutils/UserUtils.c

Improving detection of users to be removed for ASB v2 audit and remediation

---

src/common/commonutils/DaemonUtils.c
src/common/commonutils/PassUtils.c

Fixing case for RemediateEnsurePasswordReuseIsLimited and RemediateEnsurePasswordCreationRequirements, and adding extra logging to help diagnose RemediateEnsureSyslogRotaterServiceIsEnabled.

Continued stabilization for ASB v2 audit and remediation

---

src/common/asb/Asb.c

Continued stabilization for ASB v2: AuditEnsureCronServiceIsEnabled

---

.github/workflows/universalnrp-test-run.yml
.github/workflows/universalnrp-test.yml
src/common/asb/Asb.c
src/common/commonutils/FileUtils.c
src/common/commonutils/SshUtils.c

In this PR, the following improvements are done:
- For the SSH part of the ASB (and also going towards SSH Posture Control RTM), fixing one instance where sshd_config is written directly, replacing that with a secure write where changes are written to a temporary file, then in one atomic step renamed to the system file, preventing file corruption in case of unexpected power down, for example.
- Tuning down the error chatter that happens at the first initialization of the NRP on a machine, when the backup copy of fstab is made.
- Continuing to stabilize the automation CI for the NRP MC PS tests.

Continued stabilization for ASB v2 audit and remediation and the CI test automation

---

.github/workflows/universalnrp-test-run.yml
src/common/commonutils/UserUtils.c
src/modules/test/main.c

Stabilizing ASB v2's auditEnsureUnnecessaryAccountsAreRemoved and remediateEnsureUnnecessaryAccountsAreRemoved for all targeted distributions.

Stabilizing ASB v2's auditEnsureUnnecessaryAccountsAreRemoved and remediateEnsureUnnecessaryAccountsAreRemoved

---

src/common/asb/Asb.c
src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp
src/modules/test/main.c

Stabilizing ASB v2's auditEnsureZeroconfNetworkingIsDisabled and remediateEnsureZeroconfNetworkingIsDisabled.

Stabilizing ASB v2's auditEnsureZeroconfNetworkingIsDisabled and remediateEnsureZeroconfNetworkingIsDisabled 

---

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json
src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
src/common/asb/Asb.c
src/common/commonutils/UserUtils.c

Follow-up stabilization fix for ASB v2's remediateEnsurePasswordExpiration. Plus test policy definition updates.

Follow-up stabilization fix for ASB v2's remediateEnsurePasswordExpiration

---

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json
src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
src/common/commonutils/UserUtils.c

For ASB v2, adding special case when checking for user password expiration for missing last password change record (when for example there is a new user account that's still using its first password). 
Also simplifying a bit the way local memory allocations for system commands is performed.

For ASB v2, adding special case when checking for user password expiration for missing last password change record

---

src/adapters/mc/asb/LinuxSecurityBaseline_DeployIfNotExists.json
src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json

Updating the test policy definitions for ASB v2 and SSH Posture Control to keep in sync with the policy packages released today.

Updating the test policy definitions for ASB v2 and SSH Posture Control

---

.github/workflows/package-publish.yml

* Updated publishing pipelines to use AME infrastructure

Migrated to AME infrastructure

---

src/adapters/mc/README.md

Documentation fixes, no code was changed and no code behaviour was altered

Fixing readme for the Universal NRP adapter

---

src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json
src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json

Updating test policy definitions for ASB v2 and SSH for latest policy rule names and ids as per most recent functional requirement. testing with deployed test policies.

Updating test policy definitions for ASB v2 and SSH for latest policy rule names and ids

---

src/CMakeLists.txt
src/cmake/templates/version.h.in
src/common/tests/CommonUtilsUT.cpp
src/modules/CMakeLists.txt
src/modules/commandrunner/src/lib/Command.h
src/platform/CMakeLists.txt

Fix some issues reported by clang compiler.

Enabling build with clang compiler for fuzzing

---

src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json
src/adapters/mc/ssh/19params/LinuxSshServerSecurityBaseline_DeployIfNotExists.json
src/adapters/mc/ssh/LinuxSshServerSecurityBaseline_DeployIfNotExists.json

Updating test policy definitions to match most current policy packages built from main today 11/04/2024

Updating test policy definitions to match most current policy packages built from main today 11/04/2024

---

src/adapters/mc/asb/CMakeLists.txt
src/adapters/mc/ssh/CMakeLists.txt

* Normalized creation of MC packages using seperate stage_create_zip/create_zip for usage in signing MC packages

Normalized stage_create_zip/create_zip

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/FileUtils.c
src/common/tests/CommonUtilsUT.cpp

Optimizing ASB v2's commonutils!AppendPayloadToFile implementation following feedback from [robertwoj-microsoft](https://github.com/robertwoj-microsoft) and team (thanks!)

Optimizing ASB v2's commonutils!AppendPayloadToFile implementation

---

.github/workflows/fuzzing-run.yml
.github/workflows/fuzzing.yml
.github/workflows/package-build.yml

CI workflow for fuzzing.
*Note:* Reopened https://github.com/Azure/azure-osconfig/pull/792 after rebasing with main. There is no dependency on https://github.com/Azure/azure-osconfig/pull/791 now and these changes can be merged.

CI workflow for fuzzing

---

.github/workflows/prod.yml

* Removed trigger for `prod` publishing workflow

Remove prod workflow trigger

---

.github/workflows/universalnrp-test.yml

* Added `policyPackageList ` as NRP input
```json
[
{
"policy-package-short-name": "ASB",
"resource-count": 8,
"policy-package-url": "https://example.com/AzureLinuxBaseline.zip"
}
]
```

Added policyPackageList as NRP test input

---

.github/workflows/fuzzing-run.yml

Run fuzzer inside a container for better isolation and to execute in the same environment as build container.

Run fuzzer inside a container

---

.github/workflows/package-build.yml
.github/workflows/universalnrp-test.yml

Update test matrix and add module tests to NRP test workflow.

Update test matrix and add module tests to NRP test workflow

---

src/common/parson/cgmanifest.json

* Adding Component Governance manifest to the main branch.

Adding manifest for component governance (#848) to main

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Moving to README.md instructions how to install pre-commit, kept to CONTRIBUTING.md only the instruction how to run pre-commit (to keep it simple and clear), and suggested a way to add a new line to the PULL_REQUEST_TEMPLATE.md.

Updating README.md, CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md for pre-commit

---

devops/e2e/cloudtest/README.md
src/tests/universal-nrp-e2e/README.md
src/tests/universal-nrp-e2e/StartLocalTest.sh
src/tests/universal-nrp-e2e/StartTests.sh
src/tests/universal-nrp-e2e/StartVMTest.sh

* Added Amazon Linux 2 to local tests
* Removed the need to provide a resource/instance count
* Removed verbosity and added test summary

Added Amazon Linux 2, reduced verbosity and removed instance/resource count

---

src/modules/mim/compliance.json

This commit introduces the MIM model for defining compliance benchmarks. It contains all the rules known at the generation time. Contents of this file are subject to infrequent changes when new rules are introduced by CIS.

Define Compliance Benchmarks MIM model

---

.vscode/settings.json
src/common/logging/Logging.h
src/modules/compliance/src/lib/Base64.cpp
src/modules/compliance/src/lib/Base64.h
src/modules/compliance/src/lib/CMakeLists.txt
src/modules/compliance/src/lib/Engine.cpp
src/modules/compliance/src/lib/Engine.h
src/modules/compliance/src/lib/Procedure.cpp
src/modules/compliance/src/lib/Procedure.h
src/modules/compliance/tests/Base64Test.cpp
src/modules/compliance/tests/CMakeLists.txt
src/modules/compliance/tests/EngineTest.cpp
src/tests/fuzzer/CMakeLists.txt
src/tests/fuzzer/seed_corpus/Base64Decode.target
src/tests/fuzzer/target.cpp

Import the Engine class which implements mmiGet and mmiSet functions of the compliance module.
This PR includes work done by @wupeka.

Import Engine class

---

src/adapters/mc/compliance/Baseline.c
src/modules/compliance/src/lib/ComplianceInterface.cpp
src/modules/compliance/src/lib/Engine.cpp
src/modules/compliance/src/lib/Engine.h
src/modules/compliance/tests/ComplianceTest.cpp

Add calls from NRP adapter to the compliance engine.

Link Baseline.c with the compliance module

---

src/adapters/mc/compliance/CMakeLists.txt
src/adapters/mc/compliance/ComplianceShell.metaconfig.json
src/adapters/mc/compliance/ComplianceShell.mof

Build ComplianceShell.zip - a proper policy package with no policies, just the compiled library, to be used to build other policy packages externally.

ComplianceShell.zip - compliance library zip with an empty MOF

---

src/adapters/mc/compliance/CMakeLists.txt

* Fixed Compliance MC package staging directory to use the correct directory for staging

Fix staging dir for compliance mc package

---

src/adapters/mc/asb/PrivatePreviewRemediation/AzureLinuxBaseline_DeployIfNotExists.json

Updating with documentation link the draft custom policy definition for ASB remediation. Please note the link does not resolve yet. This will be fixed before this definition will be given to customers. Also, please note we will not internally publish from this location, here being only the draft kept.  Internal publishing will be via a new special release on the project.

Updating with documentation link the draft custom policy definition for ASB remediation

---

src/modules/compliance/src/lib/ComplianceInterface.cpp
src/modules/compliance/src/lib/Engine.cpp
src/modules/compliance/src/lib/Engine.h
src/modules/compliance/src/lib/Evaluator.cpp
src/modules/compliance/src/lib/JsonWrapper.cpp
src/modules/compliance/src/lib/JsonWrapper.h
src/modules/compliance/src/lib/Procedure.cpp
src/modules/compliance/tests/Base64Test.cpp
src/modules/compliance/tests/ComplianceTest.cpp
src/modules/compliance/tests/EngineTest.cpp
src/modules/compliance/tests/EvaluatorTest.cpp

Use json string properly in compliance/mmi* functions

Use json string properly in compliance/mmi* functions

---

.github/workflows/universalnrp-test.yml
src/adapters/mc/OsConfigResource.c
src/common/asb/Asb.c
src/common/logging/Logging.c
src/common/logging/Logging.h

Cherry-pick merge from dev branch:
Adding logging option to disable console logging from the OSConfig Universal NRP (#904)

Adding logging option to disable console logging from the OSConfig Universal NRP (#904)

---

.github/workflows/build-containers.yml

cherry pick #912 to `main`
* pipeline: update tj-actions/change-files to post cve
* pipeline: update tj-actions/change-files to post cve, to latest version

pipeline: update tj-actions/change-files to post cve (#912)

---

src/adapters/mc/compliance/CMakeLists.txt
src/modules/compliance/src/lib/CMakeLists.txt
src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/ensureFilePermissions.schema.json
src/modules/compliance/src/lib/procedures/ensureFilesystemOption.schema.json
src/modules/compliance/src/lib/procedures/packageInstalled.schema.json
src/modules/compliance/src/lib/procedures/testingProcedures.cpp
src/modules/compliance/src/lib/procedures/testingProcedures.schema.json

json schema for the whole payload and manually written schemas for the procedures we already have.

Preliminary json schema for compliance payload

---

src/modules/test/main.c

As module tests for compliance engine can become complex quickly, allow to use comments to describe intents of particular sections.

Allow comments in module test recipes

---

src/modules/compliance/src/lib/procedures/SCE.cpp

This PR introduces placeholder procedures for bash SCE scripts handling. They are needed for the compliance augmentation engine to be properly tested through our pipelines.

Add placeholder SCE procedures

---

devops/scripts/run-module-tests-int.sh
devops/scripts/run-module-tests.sh

Simple scripts for local testing of compliance module in docker environment.

Simple scripts for local testing of compliance module.

---

.clang-format
src/CMakeLists.txt
src/common/CMakeLists.txt
src/modules/compliance/src/lib/Regex.h
src/modules/compliance/src/lib/procedures/ensureKernelModule.cpp
src/modules/compliance/src/lib/procedures/ensureKernelModule.schema.json
src/modules/compliance/tests/procedures/ensureKernelModuleTest.cpp

ensureKernelModuleUnavailable audit. Tests require #936 to be merged.

ensureKernelModule audit procedure.

---

src/modules/compliance/src/lib/ComplianceInterface.cpp
src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/ensureAllGroupsFromEtcPasswdExistInEtcGroup.cpp
src/modules/compliance/src/lib/procedures/ensureAllGroupsFromEtcPasswdExistInEtcGroup.schema.json
src/modules/test/recipes/compliance/EnsureAllGroupsFromEtcPasswdArePresentInEtcGroup.json

This PR adds support for ensureAllGroupsFromEtcPasswdExistInEtcGroup compliance procedure used by CIS Ubuntu 22.04 7.2.3

CIS Ubuntu 22.04 7.2.3: ensureAllGroupsFromEtcPasswdExistInEtcGroup procedure

---

src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/SCE.schema.json
src/modules/compliance/src/lib/procedures/ensureFilesystemOption.schema.json

Minor fixes to compliance json schema

Minor fixes to the schemas, including missing schema for SCE

---

src/common/asb/Asb.c
src/common/commonutils/UserUtils.c
src/common/commonutils/UserUtils.h
src/modules/test/recipes/SecurityBaselineTests_EnsureUnnecessaryAccountsAreRemoved.json

Derived from #911 and #939 as we don't agree on design. This PR only fixes the existing bug and doesn't do any improvements from the PRs as they are not desired.

Fix RemoveUserAccounts

---

.pre-commit-config.yaml
src/modules/compliance/src/lib/Evaluator.h
src/modules/compliance/src/lib/GenJSONSchemas.py
src/modules/compliance/src/lib/GenProcedureMap.sh
src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/SCE.cpp
src/modules/compliance/src/lib/procedures/ensureAllGroupsFromEtcPasswdExistInEtcGroup.schema.json
src/modules/compliance/src/lib/procedures/ensureFilePermissions.cpp
src/modules/compliance/src/lib/procedures/ensureFilePermissions.schema.json
src/modules/compliance/src/lib/procedures/ensureFilesystemOption.cpp
src/modules/compliance/src/lib/procedures/ensureFilesystemOption.schema.json
src/modules/compliance/src/lib/procedures/ensureKernelModule.cpp
src/modules/compliance/src/lib/procedures/ensureKernelModule.schema.json
src/modules/compliance/src/lib/procedures/ensureNoDuplicateEntriesExist.schema.json
src/modules/compliance/src/lib/procedures/ensureNoUserHasPrimaryShadowGroup.schema.json
src/modules/compliance/src/lib/procedures/packageInstalled.cpp
src/modules/compliance/src/lib/procedures/testingProcedures.cpp
src/modules/compliance/src/lib/procedures/testingProcedures.schema.json

Scripts to regenerate schemas for compliance payloads. To be used manually when anything changes with the schema.

Schema regeneration scripting

---

src/modules/compliance/src/lib/Regex.h
src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/fileRegexMatch.cpp
src/modules/compliance/src/lib/procedures/fileRegexMatch.schema.json
src/modules/compliance/tests/procedures/fileRegexMatchTest.cpp
src/modules/test/recipes/compliance/FileRegexMatch.json

One of the rules used by CIS to perform audits.

Introduce fileRegexMatch compliance procedure

---

src/modules/compliance/src/lib/Evaluator.cpp
src/modules/compliance/src/lib/Evaluator.h
src/modules/compliance/src/lib/GenProcedureMap.sh
src/modules/compliance/src/lib/procedures/SCE.cpp
src/modules/compliance/src/lib/procedures/ensureAllGroupsFromEtcPasswdExistInEtcGroup.cpp
src/modules/compliance/src/lib/procedures/ensureFilePermissions.cpp
src/modules/compliance/src/lib/procedures/ensureFilesystemOption.cpp
src/modules/compliance/src/lib/procedures/ensureKernelModule.cpp
src/modules/compliance/src/lib/procedures/ensureNoDuplicateEntriesExist.cpp
src/modules/compliance/src/lib/procedures/ensureNoUserHasPrimaryShadowGroup.cpp
src/modules/compliance/src/lib/procedures/packageInstalled.cpp
src/modules/compliance/src/lib/procedures/testingProcedures.cpp
src/modules/compliance/tests/EngineTest.cpp
src/modules/compliance/tests/procedures/ensureFilePermissionsTest.cpp
src/modules/compliance/tests/procedures/ensureFilesystemOptionTest.cpp
src/modules/compliance/tests/procedures/ensureKernelModuleTest.cpp

This PR does not include adding the actual log entries, but a capability to do so.

Add OsConfigLogHandle parameter to compliance procedures

---

src/modules/compliance/src/lib/procedures/fileRegexMatch.cpp
src/modules/compliance/tests/procedures/fileRegexMatchTest.cpp

PRs #916 and #952 were merged one after another, but the latter was not rebased after the first one, so the builds may fail.

Fix build after improper merging #952 and #916

---

src/modules/compliance/src/lib/GenJSONSchemas.py
src/modules/compliance/src/lib/procedures/ensureFilePermissions.schema.json
src/modules/compliance/src/lib/procedures/fileRegexMatch.schema.json

The schema needs to allow for arguments, verify the default value too.

Allow for arguments in schema

---

.github/workflows/build-containers.yml

Rebuild all containers on changes (remove 3rd party action - related to #912)

Rebuild all containers on changes

---

src/modules/compliance/src/lib/GenJSONSchemas.py

rebuild the parser from regex into a semi-state-machine, proper quoting of parameters

Fix JSON Schema generator issues

---

src/adapters/mc/asb/AzureLinuxBaseline_DeployIfNotExists.json

Updating the ASB test policy definition for the most current ASB test package

Updating the ASB test policy definition for the most current ASB test package

---

src/modules/compliance/src/lib/GenJSONSchemas.py

When adding AUDIT_FN, REMEDIATE_FN patterns it's easy to add pattern
that is invalid regex.
Raise Value Error if any pattern encountered is invalid.
Signed-off-by: Krzysztof Kanas <kkanas@microsoft.com>
*Describe your changes in as much detail as possible. Provide a link/reference to the issue solved with this request if any.*

GenJSONSchemas: validate all AUDIT_FN,REMEDIATE_FN regex pattern

---

src/tests/universal-nrp-e2e/StartTests.sh
src/tests/universal-nrp-e2e/StartVMTest.sh

* Added `-h` hostname argument for starting VM tests
* Fixed incorrect parameter from `p` to `r` as documented in the usage function

Added hostname argument + argument fixes

---

src/modules/compliance/src/lib/procedures/packageInstalled.cpp
src/modules/compliance/src/lib/procedures/packageInstalled.schema.json
src/modules/compliance/tests/MockContext.h
src/modules/compliance/tests/procedures/packageInstalledTest.cpp
src/modules/test/recipes/compliance/PackageInstalled.json

New packageInstalled procedure:
- support for both dpkg and rpm, with autodetection and override
- support for caching of package list
- full test suite

New packageInstalled procedure

---

src/modules/compliance/tests/CMakeLists.txt
src/modules/compliance/tests/CommonContextTest.cpp

Add unit tests for the CommonContext class.

compliance/tests: Add test for CommonContext

---

src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/ufwStatus.cpp
src/modules/compliance/src/lib/procedures/ufwStatus.schema.json
src/modules/compliance/tests/procedures/ufwStatusTest.cpp

A simple check running "ufw status" to see if the ufw firewall is enabled.

A check for ufw status

---

src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/EnsureSshdOption.cpp
src/modules/compliance/src/lib/procedures/EnsureSshdOption.schema.json
src/modules/compliance/tests/procedures/EnsureSshdOptionTest.cpp

EnsureSshdOption audit procedure

EnsureSshdOption audit procedure

---

src/modules/compliance/src/lib/procedures/UfwStatus.cpp
src/modules/compliance/src/lib/procedures/UfwStatus.schema.json
src/modules/compliance/tests/procedures/ufwStatusTest.cpp

Allow more checks of the ufw status output

Allow UfwStatus to check anything from status.

---

src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/SystemdUnitState.cpp
src/modules/compliance/src/lib/procedures/SystemdUnitState.schema.json
src/modules/compliance/tests/procedures/SystemdUnitStateTest.cpp
src/modules/test/recipes/compliance/SystemdUnitState.json

Initial EnsureSystemdUnit to check systed managd service state

EnsureSystemdUnit

---

src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/ExecuteCommandGrep.cpp
src/modules/compliance/src/lib/procedures/ExecuteCommandGrep.schema.json
src/modules/compliance/tests/procedures/ExecuteCommandGrepTest.cpp
src/modules/test/recipes/compliance/ExecuteCommandGrep.json

Add a meta-procedure that allows launching a command (from a predefined list) and grepping the output

ExecuteCommandGrep audit meta-procedure

---

.github/workflows/ci.yml
.github/workflows/insiders-fast.yml
.github/workflows/module-test.yml

* Added Ubuntu 24.04 to CI
* Added Ubuntu 24.04 to Module Tests
* Added Ubuntu 24.04 to publish to `insiders-fast` ring

Add Ubuntu 24.04 to CI/Module Tests/insiders-fast

---

src/modules/compliance/src/lib/procedures/EnsureKernelModule.cpp
src/modules/compliance/tests/procedures/EnsureKernelModuleTest.cpp

- To be on par with the assesor, ignore modprobe failures instead of failing on them.
- Make unit tests for EnsureKernelModule less implementation focused by using WillRepeatedly, not WillOnce.

EnsureKernelModule - don't treat modprobe failures as errors, just ignore them

---

src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/EnsureMountPointExists.cpp
src/modules/compliance/src/lib/procedures/EnsureMountPointExists.schema.json
src/modules/compliance/tests/procedures/EnsureMountPointExistsTest.cpp
src/modules/test/recipes/compliance/EnsureMountPointExists.json

EnsureMountPointExists audit procedure

EnsureMountPointExists audit procedure

---

src/modules/compliance/src/lib/payload.schema.json
src/modules/compliance/src/lib/procedures/EnsureRootPath.cpp
src/modules/compliance/src/lib/procedures/EnsureRootPath.schema.json
src/modules/compliance/tests/procedures/EnsureRootPathTest.cpp

Audit procedure for ensureRootPath

Audit procedure for ensureRootPath

---

src/modules/compliance/src/lib/FactExistenceValidator.cpp
src/modules/compliance/src/lib/FactExistenceValidator.h
src/modules/compliance/src/lib/procedures/FileRegexMatch.cpp
src/modules/compliance/src/lib/procedures/PackageInstalled.cpp
src/modules/compliance/tests/FactExistenceValidatorTest.cpp
src/modules/compliance/tests/procedures/FileRegexMatchTest.cpp
src/modules/test/recipes/compliance/FileRegexMatch.json

- dpkg issue with package name with arch
- FileRegexMatch behaviour fixes

Small fixes for audits

---

src/modules/complianceengine/src/lib/procedures/ExecuteCommandGrep.cpp
src/modules/complianceengine/src/lib/procedures/ExecuteCommandGrep.schema.json
src/modules/complianceengine/tests/procedures/ExecuteCommandGrepTest.cpp

Add optional awk transform to ExecuteCommandGrep

Add optional awk transform to ExecuteCommandGrep

---

src/modules/complianceengine/src/lib/CMakeLists.txt
src/modules/complianceengine/src/lib/NetworkTools.cpp
src/modules/complianceengine/src/lib/NetworkTools.h
src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureFirewallOpenPorts.cpp
src/modules/complianceengine/src/lib/procedures/EnsureFirewallOpenPorts.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureMTAsLocalOnly.cpp
src/modules/complianceengine/src/lib/procedures/EnsureMTAsLocalOnly.schema.json
src/modules/complianceengine/tests/CMakeLists.txt
src/modules/complianceengine/tests/NetworkToolsTest.cpp
src/modules/complianceengine/tests/procedures/EnsureFirewallOpenPortsTest.cpp
src/modules/complianceengine/tests/procedures/EnsureMTAsLocalOnlyTest.cpp

- Ensure that MTAs work only on local ports
- Ensure that firewall has all the open ports listed

Firewall-related audits

---

src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/SystemdConfig.cpp
src/modules/complianceengine/src/lib/procedures/SystemdConfig.schema.json
src/modules/complianceengine/tests/procedures/SystemdConfigTest.cpp

SystemdParameters check

---

src/modules/test/main.c

Fix a memleak in the module test runner.

Minor fix for a leak in module test

---

src/modules/complianceengine/src/lib/procedures/PackageInstalled.cpp
src/modules/complianceengine/src/lib/procedures/PackageInstalled.schema.json
src/modules/complianceengine/tests/procedures/PackageInstalledTest.cpp
src/modules/test/recipes/complianceengine/PackageInstalled.json

Add minPackageVersion option to PackageInstalled check

Add minimum package version support

---

.github/workflows/universalnrp-test.yml
devops/e2e/cloudtest/ubuntu-24_04.json
src/tests/universal-nrp-e2e/StartLocalTest.sh
src/tests/universal-nrp-e2e/StartTests.sh

Cherry pick of 'Added workflow local test support #1064'

Added workflow local test support (#1064)

---

src/modules/complianceengine/src/lib/CMakeLists.txt
src/modules/complianceengine/src/lib/FilePermissionsHelpers.cpp
src/modules/complianceengine/src/lib/FileTreeWalk.cpp
src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureFilePermissions.cpp
src/modules/complianceengine/src/lib/procedures/EnsureFilePermissions.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureLogfileAccess.cpp
src/modules/complianceengine/src/lib/procedures/EnsureLogfileAccess.schema.json
src/modules/complianceengine/tests/CMakeLists.txt
src/modules/complianceengine/tests/procedures/EnsureLogfileAccessTest.cpp
src/modules/test/recipes/complianceengine/EnsureLogfileAccess.json

EnsureLogfileAccess procedure and minor fixes to helpers.

EnsureLogfileAccess procedure

---

src/modules/complianceengine/src/lib/Evaluator.cpp

The node status is already settled at the time of formatting, no need to revert it again.

Fix NOT procedure output

---

.github/workflows/ci.yml
src/modules/complianceengine/src/lib/CMakeLists.txt
src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureShadowContains.cpp
src/modules/complianceengine/src/lib/procedures/EnsureShadowContains.schema.json
src/modules/complianceengine/tests/CMakeLists.txt
src/modules/complianceengine/tests/procedures/EnsureShadowContainsTest.cpp
src/modules/test/recipes/complianceengine/EnsureShadowContains.json

Introduce EnsureShadowContains procedure

Introduce EnsureShadowContains procedure

---

src/modules/complianceengine/src/lib/CMakeLists.txt
src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureApparmorProfiles.cpp
src/modules/complianceengine/src/lib/procedures/EnsureApparmorProfiles.schema.json
src/modules/complianceengine/src/lib/procedures/ExecuteCommandGrep.cpp
src/modules/complianceengine/tests/CMakeLists.txt
src/modules/complianceengine/tests/procedures/EnsureApparmorProfilesTest.cpp

AppArmor profile procedure

---

src/adapters/mc/asb/CMakeLists.txt
src/adapters/mc/ssh/CMakeLists.txt

Cherry pick of splitting the build stages for SSH and AZB ZIP packages

Splitting the build stages for SSH and AZB ZIP packages (#1097)

---

src/adapters/mc/asb/AzureLinuxBaseline.metaconfig.json
src/adapters/mc/ssh/LinuxSshServerSecurityBaseline.metaconfig.json

Cherry pick to main of 'Adding configurationModeFrequencyMins to policy meta-config JSONs #1102'

Adding configurationModeFrequencyMins to policy meta-config JSONs (#1102)

---

src/modules/complianceengine/src/lib/CMakeLists.txt
src/modules/complianceengine/src/lib/ListValidShells.cpp
src/modules/complianceengine/src/lib/ListValidShells.h
src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureAccountsWithoutShellAreLocked.cpp
src/modules/complianceengine/src/lib/procedures/EnsureAccountsWithoutShellAreLocked.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureInteractiveUsersDotFilesAccessIsConfigured.cpp
src/modules/complianceengine/src/lib/procedures/EnsureInteractiveUsersHomeDirectoriesAreConfigured.cpp
src/modules/complianceengine/tests/CMakeLists.txt
src/modules/complianceengine/tests/procedures/EnsureAccountsWithoutShellAreLockedTest.cpp
src/modules/test/recipes/complianceengine/EnsureAccountsWithoutShellAreLocked.json

CIS Ubuntu 22.04 5.4.2.8
Depends on: #1085

Introduce EnsureAccountsWithoutShellAreLocked procedure

---

src/modules/complianceengine/src/lib/CMakeLists.txt
src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureSystemAccountsDoNotHaveValidShell.cpp
src/modules/complianceengine/src/lib/procedures/EnsureSystemAccountsDoNotHaveValidShell.schema.json
src/modules/complianceengine/tests/CMakeLists.txt
src/modules/complianceengine/tests/procedures/EnsureSystemAccountsDoNotHaveValidShellTest.cpp
src/modules/test/recipes/complianceengine/EnsureSystemAccountsDoNotHaveValidShell.json

CIS Ubuntu 22.04 5.4.2.7
Depends on: #1086

Introdue EnsureSystemAccountsDoNotHaveValidShell procedure

---

src/modules/complianceengine/src/lib/CMakeLists.txt
src/modules/complianceengine/src/lib/CommonContext.h
src/modules/complianceengine/src/lib/ContextInterface.h
src/modules/complianceengine/src/lib/FilesystemScanner.cpp
src/modules/complianceengine/src/lib/FilesystemScanner.h
src/modules/complianceengine/src/lib/payload.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureNoUnowned.cpp
src/modules/complianceengine/src/lib/procedures/EnsureNoUnowned.schema.json
src/modules/complianceengine/src/lib/procedures/EnsureNoWritables.cpp
src/modules/complianceengine/src/lib/procedures/EnsureNoWritables.schema.json
src/modules/complianceengine/tests/CMakeLists.txt
src/modules/complianceengine/tests/FilesystemScannerTest.cpp
src/modules/complianceengine/tests/MockContext.h
src/modules/complianceengine/tests/procedures/EnsureNoUnownedTest.cpp
src/modules/complianceengine/tests/procedures/EnsureNoWritablesTest.cpp

Scan the whole filesystem for unowned and/or wrong permissions files.

Filesystem scanner and procedures for it

---

devops/docker/ubuntu-14.04-amd64/Dockerfile

* Added missing Ubuntu 14 (Trusty) dependencies

Added missing Ubuntu 14 (Trusty) dependencies

---

src/common/commonutils/CommonUtils.h
src/common/commonutils/OtherUtils.c
src/common/tests/CommonUtilsUT.cpp

Reverts Azure/azure-osconfig#1150

Revert "Hardening the FREE_MEMORY macro"
